// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: perf_metrics/perf_metrics_service.proto

package esperanto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerfMetricsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TerminalState     string                 `protobuf:"bytes,1,opt,name=terminal_state,json=terminalState,proto3" json:"terminal_state,omitempty"`
	ForegroundStartup bool                   `protobuf:"varint,2,opt,name=foreground_startup,json=foregroundStartup,proto3" json:"foreground_startup,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PerfMetricsRequest) Reset() {
	*x = PerfMetricsRequest{}
	mi := &file_perf_metrics_perf_metrics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfMetricsRequest) ProtoMessage() {}

func (x *PerfMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perf_metrics_perf_metrics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfMetricsRequest.ProtoReflect.Descriptor instead.
func (*PerfMetricsRequest) Descriptor() ([]byte, []int) {
	return file_perf_metrics_perf_metrics_service_proto_rawDescGZIP(), []int{0}
}

func (x *PerfMetricsRequest) GetTerminalState() string {
	if x != nil {
		return x.TerminalState
	}
	return ""
}

func (x *PerfMetricsRequest) GetForegroundStartup() bool {
	if x != nil {
		return x.ForegroundStartup
	}
	return false
}

type PerfMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfMetricsResponse) Reset() {
	*x = PerfMetricsResponse{}
	mi := &file_perf_metrics_perf_metrics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfMetricsResponse) ProtoMessage() {}

func (x *PerfMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perf_metrics_perf_metrics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfMetricsResponse.ProtoReflect.Descriptor instead.
func (*PerfMetricsResponse) Descriptor() ([]byte, []int) {
	return file_perf_metrics_perf_metrics_service_proto_rawDescGZIP(), []int{1}
}

func (x *PerfMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_perf_metrics_perf_metrics_service_proto protoreflect.FileDescriptor

const file_perf_metrics_perf_metrics_service_proto_rawDesc = "" +
	"\n" +
	"'perf_metrics/perf_metrics_service.proto\x12$spotify.perf_metrics.esperanto.proto\"j\n" +
	"\x12PerfMetricsRequest\x12%\n" +
	"\x0eterminal_state\x18\x01 \x01(\tR\rterminalState\x12-\n" +
	"\x12foreground_startup\x18\x02 \x01(\bR\x11foregroundStartup\"/\n" +
	"\x13PerfMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9e\x01\n" +
	"\x12PerfMetricsService\x12\x87\x01\n" +
	"\x0eTerminateState\x128.spotify.perf_metrics.esperanto.proto.PerfMetricsRequest\x1a9.spotify.perf_metrics.esperanto.proto.PerfMetricsResponse\"\x00Bv\n" +
	"(com.spotify.performance.perfmetricsprotoZJgithub.com/pyrorhythm/libspot/api/spotify/perf_metrics/esperanto;esperantob\x06proto3"

var (
	file_perf_metrics_perf_metrics_service_proto_rawDescOnce sync.Once
	file_perf_metrics_perf_metrics_service_proto_rawDescData []byte
)

func file_perf_metrics_perf_metrics_service_proto_rawDescGZIP() []byte {
	file_perf_metrics_perf_metrics_service_proto_rawDescOnce.Do(func() {
		file_perf_metrics_perf_metrics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perf_metrics_perf_metrics_service_proto_rawDesc), len(file_perf_metrics_perf_metrics_service_proto_rawDesc)))
	})
	return file_perf_metrics_perf_metrics_service_proto_rawDescData
}

var file_perf_metrics_perf_metrics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_perf_metrics_perf_metrics_service_proto_goTypes = []any{
	(*PerfMetricsRequest)(nil),  // 0: spotify.perf_metrics.esperanto.proto.PerfMetricsRequest
	(*PerfMetricsResponse)(nil), // 1: spotify.perf_metrics.esperanto.proto.PerfMetricsResponse
}
var file_perf_metrics_perf_metrics_service_proto_depIdxs = []int32{
	0, // 0: spotify.perf_metrics.esperanto.proto.PerfMetricsService.TerminateState:input_type -> spotify.perf_metrics.esperanto.proto.PerfMetricsRequest
	1, // 1: spotify.perf_metrics.esperanto.proto.PerfMetricsService.TerminateState:output_type -> spotify.perf_metrics.esperanto.proto.PerfMetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_perf_metrics_perf_metrics_service_proto_init() }
func file_perf_metrics_perf_metrics_service_proto_init() {
	if File_perf_metrics_perf_metrics_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perf_metrics_perf_metrics_service_proto_rawDesc), len(file_perf_metrics_perf_metrics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_perf_metrics_perf_metrics_service_proto_goTypes,
		DependencyIndexes: file_perf_metrics_perf_metrics_service_proto_depIdxs,
		MessageInfos:      file_perf_metrics_perf_metrics_service_proto_msgTypes,
	}.Build()
	File_perf_metrics_perf_metrics_service_proto = out.File
	file_perf_metrics_perf_metrics_service_proto_goTypes = nil
	file_perf_metrics_perf_metrics_service_proto_depIdxs = nil
}
