// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mft_state.proto

package list_player

import (
	timeline_reporter "github.com/pyrorhythm/libspot/api/spotify/timeline_reporter"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SequenceSpecItemType int32

const (
	SequenceSpecItemType_SEQUENCE_SPEC_ITEM_TYPE_UNKNOWN        SequenceSpecItemType = 0
	SequenceSpecItemType_SEQUENCE_SPEC_ITEM_TYPE_LIST           SequenceSpecItemType = 1
	SequenceSpecItemType_SEQUENCE_SPEC_ITEM_TYPE_RECOMMENDATION SequenceSpecItemType = 2
)

// Enum value maps for SequenceSpecItemType.
var (
	SequenceSpecItemType_name = map[int32]string{
		0: "SEQUENCE_SPEC_ITEM_TYPE_UNKNOWN",
		1: "SEQUENCE_SPEC_ITEM_TYPE_LIST",
		2: "SEQUENCE_SPEC_ITEM_TYPE_RECOMMENDATION",
	}
	SequenceSpecItemType_value = map[string]int32{
		"SEQUENCE_SPEC_ITEM_TYPE_UNKNOWN":        0,
		"SEQUENCE_SPEC_ITEM_TYPE_LIST":           1,
		"SEQUENCE_SPEC_ITEM_TYPE_RECOMMENDATION": 2,
	}
)

func (x SequenceSpecItemType) Enum() *SequenceSpecItemType {
	p := new(SequenceSpecItemType)
	*p = x
	return p
}

func (x SequenceSpecItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SequenceSpecItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_mft_state_proto_enumTypes[0].Descriptor()
}

func (SequenceSpecItemType) Type() protoreflect.EnumType {
	return &file_mft_state_proto_enumTypes[0]
}

func (x SequenceSpecItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SequenceSpecItemType.Descriptor instead.
func (SequenceSpecItemType) EnumDescriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{0}
}

type PlayedItemsSource int32

const (
	PlayedItemsSource_PLAYED_ITEMS_SOURCE_UNKNOWN  PlayedItemsSource = 0
	PlayedItemsSource_PLAYED_ITEMS_SOURCE_LIST     PlayedItemsSource = 1
	PlayedItemsSource_PLAYED_ITEMS_SOURCE_QUEUE    PlayedItemsSource = 2
	PlayedItemsSource_PLAYED_ITEMS_SOURCE_AUTOPLAY PlayedItemsSource = 3
	PlayedItemsSource_PLAYED_ITEMS_SOURCE_MFT      PlayedItemsSource = 4
)

// Enum value maps for PlayedItemsSource.
var (
	PlayedItemsSource_name = map[int32]string{
		0: "PLAYED_ITEMS_SOURCE_UNKNOWN",
		1: "PLAYED_ITEMS_SOURCE_LIST",
		2: "PLAYED_ITEMS_SOURCE_QUEUE",
		3: "PLAYED_ITEMS_SOURCE_AUTOPLAY",
		4: "PLAYED_ITEMS_SOURCE_MFT",
	}
	PlayedItemsSource_value = map[string]int32{
		"PLAYED_ITEMS_SOURCE_UNKNOWN":  0,
		"PLAYED_ITEMS_SOURCE_LIST":     1,
		"PLAYED_ITEMS_SOURCE_QUEUE":    2,
		"PLAYED_ITEMS_SOURCE_AUTOPLAY": 3,
		"PLAYED_ITEMS_SOURCE_MFT":      4,
	}
)

func (x PlayedItemsSource) Enum() *PlayedItemsSource {
	p := new(PlayedItemsSource)
	*p = x
	return p
}

func (x PlayedItemsSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayedItemsSource) Descriptor() protoreflect.EnumDescriptor {
	return file_mft_state_proto_enumTypes[1].Descriptor()
}

func (PlayedItemsSource) Type() protoreflect.EnumType {
	return &file_mft_state_proto_enumTypes[1]
}

func (x PlayedItemsSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayedItemsSource.Descriptor instead.
func (PlayedItemsSource) EnumDescriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{1}
}

type SequenceSpecEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SequenceSpecItemType   `protobuf:"varint,1,opt,name=type,proto3,enum=spotify.list_player.proto.SequenceSpecItemType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceSpecEntry) Reset() {
	*x = SequenceSpecEntry{}
	mi := &file_mft_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceSpecEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceSpecEntry) ProtoMessage() {}

func (x *SequenceSpecEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceSpecEntry.ProtoReflect.Descriptor instead.
func (*SequenceSpecEntry) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{0}
}

func (x *SequenceSpecEntry) GetType() SequenceSpecItemType {
	if x != nil {
		return x.Type
	}
	return SequenceSpecItemType_SEQUENCE_SPEC_ITEM_TYPE_UNKNOWN
}

func (x *SequenceSpecEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SequenceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SequenceSpecEntry   `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceSpec) Reset() {
	*x = SequenceSpec{}
	mi := &file_mft_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceSpec) ProtoMessage() {}

func (x *SequenceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceSpec.ProtoReflect.Descriptor instead.
func (*SequenceSpec) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{1}
}

func (x *SequenceSpec) GetEntries() []*SequenceSpecEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PlayedItemsInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceSpecId *string                `protobuf:"bytes,1,opt,name=sequence_spec_id,json=sequenceSpecId,proto3,oneof" json:"sequence_spec_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayedItemsInfo) Reset() {
	*x = PlayedItemsInfo{}
	mi := &file_mft_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayedItemsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayedItemsInfo) ProtoMessage() {}

func (x *PlayedItemsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayedItemsInfo.ProtoReflect.Descriptor instead.
func (*PlayedItemsInfo) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{2}
}

func (x *PlayedItemsInfo) GetSequenceSpecId() string {
	if x != nil && x.SequenceSpecId != nil {
		return *x.SequenceSpecId
	}
	return ""
}

type PlayedItemsCurrentItem struct {
	state            protoimpl.MessageState                  `protogen:"open.v1"`
	ListItemUid      string                                  `protobuf:"bytes,1,opt,name=list_item_uid,json=listItemUid,proto3" json:"list_item_uid,omitempty"`
	Uri              string                                  `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Source           PlayedItemsSource                       `protobuf:"varint,3,opt,name=source,proto3,enum=spotify.list_player.proto.PlayedItemsSource" json:"source,omitempty"`
	ReportingContext *timeline_reporter.ItemReportingContext `protobuf:"bytes,4,opt,name=reporting_context,json=reportingContext,proto3,oneof" json:"reporting_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayedItemsCurrentItem) Reset() {
	*x = PlayedItemsCurrentItem{}
	mi := &file_mft_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayedItemsCurrentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayedItemsCurrentItem) ProtoMessage() {}

func (x *PlayedItemsCurrentItem) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayedItemsCurrentItem.ProtoReflect.Descriptor instead.
func (*PlayedItemsCurrentItem) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{3}
}

func (x *PlayedItemsCurrentItem) GetListItemUid() string {
	if x != nil {
		return x.ListItemUid
	}
	return ""
}

func (x *PlayedItemsCurrentItem) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *PlayedItemsCurrentItem) GetSource() PlayedItemsSource {
	if x != nil {
		return x.Source
	}
	return PlayedItemsSource_PLAYED_ITEMS_SOURCE_UNKNOWN
}

func (x *PlayedItemsCurrentItem) GetReportingContext() *timeline_reporter.ItemReportingContext {
	if x != nil {
		return x.ReportingContext
	}
	return nil
}

type PlayedItems struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*PlayedItems_ItemsEntry `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	CurrentItem   *PlayedItemsCurrentItem   `protobuf:"bytes,2,opt,name=current_item,json=currentItem,proto3,oneof" json:"current_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayedItems) Reset() {
	*x = PlayedItems{}
	mi := &file_mft_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayedItems) ProtoMessage() {}

func (x *PlayedItems) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayedItems.ProtoReflect.Descriptor instead.
func (*PlayedItems) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{4}
}

func (x *PlayedItems) GetItems() []*PlayedItems_ItemsEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlayedItems) GetCurrentItem() *PlayedItemsCurrentItem {
	if x != nil {
		return x.CurrentItem
	}
	return nil
}

type MftState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListUri       *string                `protobuf:"bytes,1,opt,name=list_uri,json=listUri,proto3,oneof" json:"list_uri,omitempty"`
	SequenceSpec  *SequenceSpec          `protobuf:"bytes,2,opt,name=sequence_spec,json=sequenceSpec,proto3,oneof" json:"sequence_spec,omitempty"`
	PlayedItems   *PlayedItems           `protobuf:"bytes,3,opt,name=played_items,json=playedItems,proto3,oneof" json:"played_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MftState) Reset() {
	*x = MftState{}
	mi := &file_mft_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MftState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MftState) ProtoMessage() {}

func (x *MftState) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MftState.ProtoReflect.Descriptor instead.
func (*MftState) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{5}
}

func (x *MftState) GetListUri() string {
	if x != nil && x.ListUri != nil {
		return *x.ListUri
	}
	return ""
}

func (x *MftState) GetSequenceSpec() *SequenceSpec {
	if x != nil {
		return x.SequenceSpec
	}
	return nil
}

func (x *MftState) GetPlayedItems() *PlayedItems {
	if x != nil {
		return x.PlayedItems
	}
	return nil
}

type PlayedItems_ItemsEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *PlayedItemsInfo       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayedItems_ItemsEntry) Reset() {
	*x = PlayedItems_ItemsEntry{}
	mi := &file_mft_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayedItems_ItemsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayedItems_ItemsEntry) ProtoMessage() {}

func (x *PlayedItems_ItemsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mft_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayedItems_ItemsEntry.ProtoReflect.Descriptor instead.
func (*PlayedItems_ItemsEntry) Descriptor() ([]byte, []int) {
	return file_mft_state_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PlayedItems_ItemsEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PlayedItems_ItemsEntry) GetValue() *PlayedItemsInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_mft_state_proto protoreflect.FileDescriptor

const file_mft_state_proto_rawDesc = "" +
	"\n" +
	"\x0fmft_state.proto\x12\x19spotify.list_player.proto\x1a\x1citem_reporting_context.proto\"h\n" +
	"\x11SequenceSpecEntry\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.spotify.list_player.proto.SequenceSpecItemTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"V\n" +
	"\fSequenceSpec\x12F\n" +
	"\aentries\x18\x02 \x03(\v2,.spotify.list_player.proto.SequenceSpecEntryR\aentries\"U\n" +
	"\x0fPlayedItemsInfo\x12-\n" +
	"\x10sequence_spec_id\x18\x01 \x01(\tH\x00R\x0esequenceSpecId\x88\x01\x01B\x13\n" +
	"\x11_sequence_spec_id\"\x93\x02\n" +
	"\x16PlayedItemsCurrentItem\x12\"\n" +
	"\rlist_item_uid\x18\x01 \x01(\tR\vlistItemUid\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12D\n" +
	"\x06source\x18\x03 \x01(\x0e2,.spotify.list_player.proto.PlayedItemsSourceR\x06source\x12g\n" +
	"\x11reporting_context\x18\x04 \x01(\v25.spotify.timeline_reporter.proto.ItemReportingContextH\x00R\x10reportingContext\x88\x01\x01B\x14\n" +
	"\x12_reporting_context\"\xa4\x02\n" +
	"\vPlayedItems\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.spotify.list_player.proto.PlayedItems.ItemsEntryR\x05items\x12Y\n" +
	"\fcurrent_item\x18\x02 \x01(\v21.spotify.list_player.proto.PlayedItemsCurrentItemH\x00R\vcurrentItem\x88\x01\x01\x1a`\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.spotify.list_player.proto.PlayedItemsInfoR\x05valueB\x0f\n" +
	"\r_current_item\"\xfd\x01\n" +
	"\bMftState\x12\x1e\n" +
	"\blist_uri\x18\x01 \x01(\tH\x00R\alistUri\x88\x01\x01\x12Q\n" +
	"\rsequence_spec\x18\x02 \x01(\v2'.spotify.list_player.proto.SequenceSpecH\x01R\fsequenceSpec\x88\x01\x01\x12N\n" +
	"\fplayed_items\x18\x03 \x01(\v2&.spotify.list_player.proto.PlayedItemsH\x02R\vplayedItems\x88\x01\x01B\v\n" +
	"\t_list_uriB\x10\n" +
	"\x0e_sequence_specB\x0f\n" +
	"\r_played_items*\x89\x01\n" +
	"\x14SequenceSpecItemType\x12#\n" +
	"\x1fSEQUENCE_SPEC_ITEM_TYPE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cSEQUENCE_SPEC_ITEM_TYPE_LIST\x10\x01\x12*\n" +
	"&SEQUENCE_SPEC_ITEM_TYPE_RECOMMENDATION\x10\x02*\xb0\x01\n" +
	"\x11PlayedItemsSource\x12\x1f\n" +
	"\x1bPLAYED_ITEMS_SOURCE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18PLAYED_ITEMS_SOURCE_LIST\x10\x01\x12\x1d\n" +
	"\x19PLAYED_ITEMS_SOURCE_QUEUE\x10\x02\x12 \n" +
	"\x1cPLAYED_ITEMS_SOURCE_AUTOPLAY\x10\x03\x12\x1b\n" +
	"\x17PLAYED_ITEMS_SOURCE_MFT\x10\x04BCZAgithub.com/pyrorhythm/libspot/api/spotify/list_player;list_playerb\x06proto3"

var (
	file_mft_state_proto_rawDescOnce sync.Once
	file_mft_state_proto_rawDescData []byte
)

func file_mft_state_proto_rawDescGZIP() []byte {
	file_mft_state_proto_rawDescOnce.Do(func() {
		file_mft_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mft_state_proto_rawDesc), len(file_mft_state_proto_rawDesc)))
	})
	return file_mft_state_proto_rawDescData
}

var file_mft_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mft_state_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mft_state_proto_goTypes = []any{
	(SequenceSpecItemType)(0),                      // 0: spotify.list_player.proto.SequenceSpecItemType
	(PlayedItemsSource)(0),                         // 1: spotify.list_player.proto.PlayedItemsSource
	(*SequenceSpecEntry)(nil),                      // 2: spotify.list_player.proto.SequenceSpecEntry
	(*SequenceSpec)(nil),                           // 3: spotify.list_player.proto.SequenceSpec
	(*PlayedItemsInfo)(nil),                        // 4: spotify.list_player.proto.PlayedItemsInfo
	(*PlayedItemsCurrentItem)(nil),                 // 5: spotify.list_player.proto.PlayedItemsCurrentItem
	(*PlayedItems)(nil),                            // 6: spotify.list_player.proto.PlayedItems
	(*MftState)(nil),                               // 7: spotify.list_player.proto.MftState
	(*PlayedItems_ItemsEntry)(nil),                 // 8: spotify.list_player.proto.PlayedItems.ItemsEntry
	(*timeline_reporter.ItemReportingContext)(nil), // 9: spotify.timeline_reporter.proto.ItemReportingContext
}
var file_mft_state_proto_depIdxs = []int32{
	0, // 0: spotify.list_player.proto.SequenceSpecEntry.type:type_name -> spotify.list_player.proto.SequenceSpecItemType
	2, // 1: spotify.list_player.proto.SequenceSpec.entries:type_name -> spotify.list_player.proto.SequenceSpecEntry
	1, // 2: spotify.list_player.proto.PlayedItemsCurrentItem.source:type_name -> spotify.list_player.proto.PlayedItemsSource
	9, // 3: spotify.list_player.proto.PlayedItemsCurrentItem.reporting_context:type_name -> spotify.timeline_reporter.proto.ItemReportingContext
	8, // 4: spotify.list_player.proto.PlayedItems.items:type_name -> spotify.list_player.proto.PlayedItems.ItemsEntry
	5, // 5: spotify.list_player.proto.PlayedItems.current_item:type_name -> spotify.list_player.proto.PlayedItemsCurrentItem
	3, // 6: spotify.list_player.proto.MftState.sequence_spec:type_name -> spotify.list_player.proto.SequenceSpec
	6, // 7: spotify.list_player.proto.MftState.played_items:type_name -> spotify.list_player.proto.PlayedItems
	4, // 8: spotify.list_player.proto.PlayedItems.ItemsEntry.value:type_name -> spotify.list_player.proto.PlayedItemsInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_mft_state_proto_init() }
func file_mft_state_proto_init() {
	if File_mft_state_proto != nil {
		return
	}
	file_mft_state_proto_msgTypes[2].OneofWrappers = []any{}
	file_mft_state_proto_msgTypes[3].OneofWrappers = []any{}
	file_mft_state_proto_msgTypes[4].OneofWrappers = []any{}
	file_mft_state_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mft_state_proto_rawDesc), len(file_mft_state_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mft_state_proto_goTypes,
		DependencyIndexes: file_mft_state_proto_depIdxs,
		EnumInfos:         file_mft_state_proto_enumTypes,
		MessageInfos:      file_mft_state_proto_msgTypes,
	}.Build()
	File_mft_state_proto = out.File
	file_mft_state_proto_goTypes = nil
	file_mft_state_proto_depIdxs = nil
}
