// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: es_auth_blob.proto

package esperanto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthBlob struct {
	state                        protoimpl.MessageState        `protogen:"open.v1"`
	UnencryptedStoredCredentials *UnencryptedStoredCredentials `protobuf:"bytes,2,opt,name=unencryptedStoredCredentials,proto3" json:"unencryptedStoredCredentials,omitempty"`
	// Types that are valid to be assigned to Blob:
	//
	//	*AuthBlob_StoredCredentials
	Blob          isAuthBlob_Blob `protobuf_oneof:"blob"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthBlob) Reset() {
	*x = AuthBlob{}
	mi := &file_es_auth_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBlob) ProtoMessage() {}

func (x *AuthBlob) ProtoReflect() protoreflect.Message {
	mi := &file_es_auth_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBlob.ProtoReflect.Descriptor instead.
func (*AuthBlob) Descriptor() ([]byte, []int) {
	return file_es_auth_blob_proto_rawDescGZIP(), []int{0}
}

func (x *AuthBlob) GetUnencryptedStoredCredentials() *UnencryptedStoredCredentials {
	if x != nil {
		return x.UnencryptedStoredCredentials
	}
	return nil
}

func (x *AuthBlob) GetBlob() isAuthBlob_Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *AuthBlob) GetStoredCredentials() *EncryptedStoredCredentials {
	if x != nil {
		if x, ok := x.Blob.(*AuthBlob_StoredCredentials); ok {
			return x.StoredCredentials
		}
	}
	return nil
}

type isAuthBlob_Blob interface {
	isAuthBlob_Blob()
}

type AuthBlob_StoredCredentials struct {
	StoredCredentials *EncryptedStoredCredentials `protobuf:"bytes,1,opt,name=storedCredentials,proto3,oneof"`
}

func (*AuthBlob_StoredCredentials) isAuthBlob_Blob() {}

var File_es_auth_blob_proto protoreflect.FileDescriptor

const file_es_auth_blob_proto_rawDesc = "" +
	"\n" +
	"\x12es_auth_blob.proto\x120spotify.connectivity.auth.common.esperanto.proto\x1a%es_encrypted_stored_credentials.proto\x1a'es_unencrypted_stored_credentials.proto\"\xa5\x02\n" +
	"\bAuthBlob\x12\x92\x01\n" +
	"\x1cunencryptedStoredCredentials\x18\x02 \x01(\v2N.spotify.connectivity.auth.common.esperanto.proto.UnencryptedStoredCredentialsR\x1cunencryptedStoredCredentials\x12|\n" +
	"\x11storedCredentials\x18\x01 \x01(\v2L.spotify.connectivity.auth.common.esperanto.proto.EncryptedStoredCredentialsH\x00R\x11storedCredentialsB\x06\n" +
	"\x04blobB\xa1\x01\n" +
	"4com.spotify.connectivity.auth.common.esperanto.protoZVgithub.com/pyrorhythm/libspot/api/spotify/connectivity/auth/common/esperanto;esperanto\xa2\x02\x10SPTAuthEsperantob\x06proto3"

var (
	file_es_auth_blob_proto_rawDescOnce sync.Once
	file_es_auth_blob_proto_rawDescData []byte
)

func file_es_auth_blob_proto_rawDescGZIP() []byte {
	file_es_auth_blob_proto_rawDescOnce.Do(func() {
		file_es_auth_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es_auth_blob_proto_rawDesc), len(file_es_auth_blob_proto_rawDesc)))
	})
	return file_es_auth_blob_proto_rawDescData
}

var file_es_auth_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_es_auth_blob_proto_goTypes = []any{
	(*AuthBlob)(nil),                     // 0: spotify.connectivity.auth.common.esperanto.proto.AuthBlob
	(*UnencryptedStoredCredentials)(nil), // 1: spotify.connectivity.auth.common.esperanto.proto.UnencryptedStoredCredentials
	(*EncryptedStoredCredentials)(nil),   // 2: spotify.connectivity.auth.common.esperanto.proto.EncryptedStoredCredentials
}
var file_es_auth_blob_proto_depIdxs = []int32{
	1, // 0: spotify.connectivity.auth.common.esperanto.proto.AuthBlob.unencryptedStoredCredentials:type_name -> spotify.connectivity.auth.common.esperanto.proto.UnencryptedStoredCredentials
	2, // 1: spotify.connectivity.auth.common.esperanto.proto.AuthBlob.storedCredentials:type_name -> spotify.connectivity.auth.common.esperanto.proto.EncryptedStoredCredentials
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_es_auth_blob_proto_init() }
func file_es_auth_blob_proto_init() {
	if File_es_auth_blob_proto != nil {
		return
	}
	file_es_encrypted_stored_credentials_proto_init()
	file_es_unencrypted_stored_credentials_proto_init()
	file_es_auth_blob_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthBlob_StoredCredentials)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es_auth_blob_proto_rawDesc), len(file_es_auth_blob_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es_auth_blob_proto_goTypes,
		DependencyIndexes: file_es_auth_blob_proto_depIdxs,
		MessageInfos:      file_es_auth_blob_proto_msgTypes,
	}.Build()
	File_es_auth_blob_proto = out.File
	file_es_auth_blob_proto_goTypes = nil
	file_es_auth_blob_proto_depIdxs = nil
}
