// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: playlist_set_base_permission_request.proto

package playlist_esperanto

import (
	cosmos "github.com/pyrorhythm/libspot/api/spotify/playlist/cosmos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaylistSetBasePermissionRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Uris          []string                         `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	Request       *cosmos.SetBasePermissionRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSetBasePermissionRequest) Reset() {
	*x = PlaylistSetBasePermissionRequest{}
	mi := &file_playlist_set_base_permission_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSetBasePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSetBasePermissionRequest) ProtoMessage() {}

func (x *PlaylistSetBasePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_set_base_permission_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSetBasePermissionRequest.ProtoReflect.Descriptor instead.
func (*PlaylistSetBasePermissionRequest) Descriptor() ([]byte, []int) {
	return file_playlist_set_base_permission_request_proto_rawDescGZIP(), []int{0}
}

func (x *PlaylistSetBasePermissionRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *PlaylistSetBasePermissionRequest) GetRequest() *cosmos.SetBasePermissionRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type PlaylistSetBasePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistSetBasePermissionResponse) Reset() {
	*x = PlaylistSetBasePermissionResponse{}
	mi := &file_playlist_set_base_permission_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistSetBasePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistSetBasePermissionResponse) ProtoMessage() {}

func (x *PlaylistSetBasePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_set_base_permission_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistSetBasePermissionResponse.ProtoReflect.Descriptor instead.
func (*PlaylistSetBasePermissionResponse) Descriptor() ([]byte, []int) {
	return file_playlist_set_base_permission_request_proto_rawDescGZIP(), []int{1}
}

func (x *PlaylistSetBasePermissionResponse) GetStatus() *ResponseStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_playlist_set_base_permission_request_proto protoreflect.FileDescriptor

const file_playlist_set_base_permission_request_proto_rawDesc = "" +
	"\n" +
	"*playlist_set_base_permission_request.proto\x12 spotify.playlist_esperanto.proto\x1a%playlist_set_permission_request.proto\x1a\x15response_status.proto\"\x89\x01\n" +
	" PlaylistSetBasePermissionRequest\x12\x12\n" +
	"\x04uris\x18\x01 \x03(\tR\x04uris\x12Q\n" +
	"\arequest\x18\x02 \x01(\v27.spotify.playlist.cosmos.proto.SetBasePermissionRequestR\arequest\"m\n" +
	"!PlaylistSetBasePermissionResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\v20.spotify.playlist_esperanto.proto.ResponseStatusR\x06statusB{\n" +
	" spotify.playlist.esperanto.protoP\x01ZOgithub.com/pyrorhythm/libspot/api/spotify/playlist_esperanto;playlist_esperanto\xa2\x02\x03ESPb\x06proto3"

var (
	file_playlist_set_base_permission_request_proto_rawDescOnce sync.Once
	file_playlist_set_base_permission_request_proto_rawDescData []byte
)

func file_playlist_set_base_permission_request_proto_rawDescGZIP() []byte {
	file_playlist_set_base_permission_request_proto_rawDescOnce.Do(func() {
		file_playlist_set_base_permission_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playlist_set_base_permission_request_proto_rawDesc), len(file_playlist_set_base_permission_request_proto_rawDesc)))
	})
	return file_playlist_set_base_permission_request_proto_rawDescData
}

var file_playlist_set_base_permission_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_playlist_set_base_permission_request_proto_goTypes = []any{
	(*PlaylistSetBasePermissionRequest)(nil),  // 0: spotify.playlist_esperanto.proto.PlaylistSetBasePermissionRequest
	(*PlaylistSetBasePermissionResponse)(nil), // 1: spotify.playlist_esperanto.proto.PlaylistSetBasePermissionResponse
	(*cosmos.SetBasePermissionRequest)(nil),   // 2: spotify.playlist.cosmos.proto.SetBasePermissionRequest
	(*ResponseStatus)(nil),                    // 3: spotify.playlist_esperanto.proto.ResponseStatus
}
var file_playlist_set_base_permission_request_proto_depIdxs = []int32{
	2, // 0: spotify.playlist_esperanto.proto.PlaylistSetBasePermissionRequest.request:type_name -> spotify.playlist.cosmos.proto.SetBasePermissionRequest
	3, // 1: spotify.playlist_esperanto.proto.PlaylistSetBasePermissionResponse.status:type_name -> spotify.playlist_esperanto.proto.ResponseStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_playlist_set_base_permission_request_proto_init() }
func file_playlist_set_base_permission_request_proto_init() {
	if File_playlist_set_base_permission_request_proto != nil {
		return
	}
	file_response_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playlist_set_base_permission_request_proto_rawDesc), len(file_playlist_set_base_permission_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playlist_set_base_permission_request_proto_goTypes,
		DependencyIndexes: file_playlist_set_base_permission_request_proto_depIdxs,
		MessageInfos:      file_playlist_set_base_permission_request_proto_msgTypes,
	}.Build()
	File_playlist_set_base_permission_request_proto = out.File
	file_playlist_set_base_permission_request_proto_goTypes = nil
	file_playlist_set_base_permission_request_proto_depIdxs = nil
}
