// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/AdEvent.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        *string                `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	AppStartupId     *string                `protobuf:"bytes,2,opt,name=app_startup_id,json=appStartupId" json:"app_startup_id,omitempty"`
	AdId             *string                `protobuf:"bytes,3,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	LineitemId       *string                `protobuf:"bytes,4,opt,name=lineitem_id,json=lineitemId" json:"lineitem_id,omitempty"`
	CreativeId       *string                `protobuf:"bytes,5,opt,name=creative_id,json=creativeId" json:"creative_id,omitempty"`
	Slot             *string                `protobuf:"bytes,6,opt,name=slot" json:"slot,omitempty"`
	Format           *string                `protobuf:"bytes,7,opt,name=format" json:"format,omitempty"`
	Type             *string                `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	Skippable        *bool                  `protobuf:"varint,9,opt,name=skippable" json:"skippable,omitempty"`
	Event            *string                `protobuf:"bytes,10,opt,name=event" json:"event,omitempty"`
	EventSource      *string                `protobuf:"bytes,11,opt,name=event_source,json=eventSource" json:"event_source,omitempty"`
	EventReason      *string                `protobuf:"bytes,12,opt,name=event_reason,json=eventReason" json:"event_reason,omitempty"`
	EventSequenceNum *int32                 `protobuf:"varint,13,opt,name=event_sequence_num,json=eventSequenceNum" json:"event_sequence_num,omitempty"`
	Position         *int32                 `protobuf:"varint,14,opt,name=position" json:"position,omitempty"`
	Duration         *int32                 `protobuf:"varint,15,opt,name=duration" json:"duration,omitempty"`
	InFocus          *bool                  `protobuf:"varint,16,opt,name=in_focus,json=inFocus" json:"in_focus,omitempty"`
	Volume           *float32               `protobuf:"fixed32,17,opt,name=volume" json:"volume,omitempty"`
	ProductName      *string                `protobuf:"bytes,18,opt,name=product_name,json=productName" json:"product_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdEvent) Reset() {
	*x = AdEvent{}
	mi := &file_include_AdEvent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEvent) ProtoMessage() {}

func (x *AdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_include_AdEvent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEvent.ProtoReflect.Descriptor instead.
func (*AdEvent) Descriptor() ([]byte, []int) {
	return file_include_AdEvent_proto_rawDescGZIP(), []int{0}
}

func (x *AdEvent) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *AdEvent) GetAppStartupId() string {
	if x != nil && x.AppStartupId != nil {
		return *x.AppStartupId
	}
	return ""
}

func (x *AdEvent) GetAdId() string {
	if x != nil && x.AdId != nil {
		return *x.AdId
	}
	return ""
}

func (x *AdEvent) GetLineitemId() string {
	if x != nil && x.LineitemId != nil {
		return *x.LineitemId
	}
	return ""
}

func (x *AdEvent) GetCreativeId() string {
	if x != nil && x.CreativeId != nil {
		return *x.CreativeId
	}
	return ""
}

func (x *AdEvent) GetSlot() string {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return ""
}

func (x *AdEvent) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *AdEvent) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AdEvent) GetSkippable() bool {
	if x != nil && x.Skippable != nil {
		return *x.Skippable
	}
	return false
}

func (x *AdEvent) GetEvent() string {
	if x != nil && x.Event != nil {
		return *x.Event
	}
	return ""
}

func (x *AdEvent) GetEventSource() string {
	if x != nil && x.EventSource != nil {
		return *x.EventSource
	}
	return ""
}

func (x *AdEvent) GetEventReason() string {
	if x != nil && x.EventReason != nil {
		return *x.EventReason
	}
	return ""
}

func (x *AdEvent) GetEventSequenceNum() int32 {
	if x != nil && x.EventSequenceNum != nil {
		return *x.EventSequenceNum
	}
	return 0
}

func (x *AdEvent) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *AdEvent) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *AdEvent) GetInFocus() bool {
	if x != nil && x.InFocus != nil {
		return *x.InFocus
	}
	return false
}

func (x *AdEvent) GetVolume() float32 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *AdEvent) GetProductName() string {
	if x != nil && x.ProductName != nil {
		return *x.ProductName
	}
	return ""
}

var File_include_AdEvent_proto protoreflect.FileDescriptor

const file_include_AdEvent_proto_rawDesc = "" +
	"\n" +
	"\x15include/AdEvent.proto\x12\x1aspotify.event_sender.proto\"\x9b\x04\n" +
	"\aAdEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\x0eapp_startup_id\x18\x02 \x01(\tR\fappStartupId\x12\x13\n" +
	"\x05ad_id\x18\x03 \x01(\tR\x04adId\x12\x1f\n" +
	"\vlineitem_id\x18\x04 \x01(\tR\n" +
	"lineitemId\x12\x1f\n" +
	"\vcreative_id\x18\x05 \x01(\tR\n" +
	"creativeId\x12\x12\n" +
	"\x04slot\x18\x06 \x01(\tR\x04slot\x12\x16\n" +
	"\x06format\x18\a \x01(\tR\x06format\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x1c\n" +
	"\tskippable\x18\t \x01(\bR\tskippable\x12\x14\n" +
	"\x05event\x18\n" +
	" \x01(\tR\x05event\x12!\n" +
	"\fevent_source\x18\v \x01(\tR\veventSource\x12!\n" +
	"\fevent_reason\x18\f \x01(\tR\veventReason\x12,\n" +
	"\x12event_sequence_num\x18\r \x01(\x05R\x10eventSequenceNum\x12\x1a\n" +
	"\bposition\x18\x0e \x01(\x05R\bposition\x12\x1a\n" +
	"\bduration\x18\x0f \x01(\x05R\bduration\x12\x19\n" +
	"\bin_focus\x18\x10 \x01(\bR\ainFocus\x12\x16\n" +
	"\x06volume\x18\x11 \x01(\x02R\x06volume\x12!\n" +
	"\fproduct_name\x18\x12 \x01(\tR\vproductNameBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_AdEvent_proto_rawDescOnce sync.Once
	file_include_AdEvent_proto_rawDescData []byte
)

func file_include_AdEvent_proto_rawDescGZIP() []byte {
	file_include_AdEvent_proto_rawDescOnce.Do(func() {
		file_include_AdEvent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_AdEvent_proto_rawDesc), len(file_include_AdEvent_proto_rawDesc)))
	})
	return file_include_AdEvent_proto_rawDescData
}

var file_include_AdEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_AdEvent_proto_goTypes = []any{
	(*AdEvent)(nil), // 0: spotify.event_sender.proto.AdEvent
}
var file_include_AdEvent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_AdEvent_proto_init() }
func file_include_AdEvent_proto_init() {
	if File_include_AdEvent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_AdEvent_proto_rawDesc), len(file_include_AdEvent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_AdEvent_proto_goTypes,
		DependencyIndexes: file_include_AdEvent_proto_depIdxs,
		MessageInfos:      file_include_AdEvent_proto_msgTypes,
	}.Build()
	File_include_AdEvent_proto = out.File
	file_include_AdEvent_proto_goTypes = nil
	file_include_AdEvent_proto_depIdxs = nil
}
