// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/AdOpportunityEvent.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdOpportunityEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TriggerId         *string                `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId" json:"trigger_id,omitempty"`
	TriggerType       *string                `protobuf:"bytes,2,opt,name=trigger_type,json=triggerType" json:"trigger_type,omitempty"`
	DecisionRequestId *string                `protobuf:"bytes,3,opt,name=decision_request_id,json=decisionRequestId" json:"decision_request_id,omitempty"`
	TriggerState      *string                `protobuf:"bytes,4,opt,name=trigger_state,json=triggerState" json:"trigger_state,omitempty"`
	FocusState        *bool                  `protobuf:"varint,5,opt,name=focus_state,json=focusState" json:"focus_state,omitempty"`
	ContentUri        *string                `protobuf:"bytes,6,opt,name=content_uri,json=contentUri" json:"content_uri,omitempty"`
	PlaybackId        *string                `protobuf:"bytes,7,opt,name=playback_id,json=playbackId" json:"playback_id,omitempty"`
	RequestId         *string                `protobuf:"bytes,8,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	DidSkip           *bool                  `protobuf:"varint,9,opt,name=did_skip,json=didSkip" json:"did_skip,omitempty"`
	AppStartupId      *string                `protobuf:"bytes,10,opt,name=app_startup_id,json=appStartupId" json:"app_startup_id,omitempty"`
	UserIsCapped      *bool                  `protobuf:"varint,11,opt,name=user_is_capped,json=userIsCapped" json:"user_is_capped,omitempty"`
	DemandStatus      *string                `protobuf:"bytes,12,opt,name=demand_status,json=demandStatus" json:"demand_status,omitempty"`
	EligibilityStatus *string                `protobuf:"bytes,13,opt,name=eligibility_status,json=eligibilityStatus" json:"eligibility_status,omitempty"`
	SupplyStatus      *string                `protobuf:"bytes,14,opt,name=supply_status,json=supplyStatus" json:"supply_status,omitempty"`
	TriggerOrigin     *string                `protobuf:"bytes,15,opt,name=trigger_origin,json=triggerOrigin" json:"trigger_origin,omitempty"`
	TriggerStates     []string               `protobuf:"bytes,16,rep,name=trigger_states,json=triggerStates" json:"trigger_states,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdOpportunityEvent) Reset() {
	*x = AdOpportunityEvent{}
	mi := &file_include_AdOpportunityEvent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdOpportunityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdOpportunityEvent) ProtoMessage() {}

func (x *AdOpportunityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_include_AdOpportunityEvent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdOpportunityEvent.ProtoReflect.Descriptor instead.
func (*AdOpportunityEvent) Descriptor() ([]byte, []int) {
	return file_include_AdOpportunityEvent_proto_rawDescGZIP(), []int{0}
}

func (x *AdOpportunityEvent) GetTriggerId() string {
	if x != nil && x.TriggerId != nil {
		return *x.TriggerId
	}
	return ""
}

func (x *AdOpportunityEvent) GetTriggerType() string {
	if x != nil && x.TriggerType != nil {
		return *x.TriggerType
	}
	return ""
}

func (x *AdOpportunityEvent) GetDecisionRequestId() string {
	if x != nil && x.DecisionRequestId != nil {
		return *x.DecisionRequestId
	}
	return ""
}

func (x *AdOpportunityEvent) GetTriggerState() string {
	if x != nil && x.TriggerState != nil {
		return *x.TriggerState
	}
	return ""
}

func (x *AdOpportunityEvent) GetFocusState() bool {
	if x != nil && x.FocusState != nil {
		return *x.FocusState
	}
	return false
}

func (x *AdOpportunityEvent) GetContentUri() string {
	if x != nil && x.ContentUri != nil {
		return *x.ContentUri
	}
	return ""
}

func (x *AdOpportunityEvent) GetPlaybackId() string {
	if x != nil && x.PlaybackId != nil {
		return *x.PlaybackId
	}
	return ""
}

func (x *AdOpportunityEvent) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *AdOpportunityEvent) GetDidSkip() bool {
	if x != nil && x.DidSkip != nil {
		return *x.DidSkip
	}
	return false
}

func (x *AdOpportunityEvent) GetAppStartupId() string {
	if x != nil && x.AppStartupId != nil {
		return *x.AppStartupId
	}
	return ""
}

func (x *AdOpportunityEvent) GetUserIsCapped() bool {
	if x != nil && x.UserIsCapped != nil {
		return *x.UserIsCapped
	}
	return false
}

func (x *AdOpportunityEvent) GetDemandStatus() string {
	if x != nil && x.DemandStatus != nil {
		return *x.DemandStatus
	}
	return ""
}

func (x *AdOpportunityEvent) GetEligibilityStatus() string {
	if x != nil && x.EligibilityStatus != nil {
		return *x.EligibilityStatus
	}
	return ""
}

func (x *AdOpportunityEvent) GetSupplyStatus() string {
	if x != nil && x.SupplyStatus != nil {
		return *x.SupplyStatus
	}
	return ""
}

func (x *AdOpportunityEvent) GetTriggerOrigin() string {
	if x != nil && x.TriggerOrigin != nil {
		return *x.TriggerOrigin
	}
	return ""
}

func (x *AdOpportunityEvent) GetTriggerStates() []string {
	if x != nil {
		return x.TriggerStates
	}
	return nil
}

var File_include_AdOpportunityEvent_proto protoreflect.FileDescriptor

const file_include_AdOpportunityEvent_proto_rawDesc = "" +
	"\n" +
	" include/AdOpportunityEvent.proto\x12\x1aspotify.event_sender.proto\"\xdb\x04\n" +
	"\x12AdOpportunityEvent\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\x12!\n" +
	"\ftrigger_type\x18\x02 \x01(\tR\vtriggerType\x12.\n" +
	"\x13decision_request_id\x18\x03 \x01(\tR\x11decisionRequestId\x12#\n" +
	"\rtrigger_state\x18\x04 \x01(\tR\ftriggerState\x12\x1f\n" +
	"\vfocus_state\x18\x05 \x01(\bR\n" +
	"focusState\x12\x1f\n" +
	"\vcontent_uri\x18\x06 \x01(\tR\n" +
	"contentUri\x12\x1f\n" +
	"\vplayback_id\x18\a \x01(\tR\n" +
	"playbackId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12\x19\n" +
	"\bdid_skip\x18\t \x01(\bR\adidSkip\x12$\n" +
	"\x0eapp_startup_id\x18\n" +
	" \x01(\tR\fappStartupId\x12$\n" +
	"\x0euser_is_capped\x18\v \x01(\bR\fuserIsCapped\x12#\n" +
	"\rdemand_status\x18\f \x01(\tR\fdemandStatus\x12-\n" +
	"\x12eligibility_status\x18\r \x01(\tR\x11eligibilityStatus\x12#\n" +
	"\rsupply_status\x18\x0e \x01(\tR\fsupplyStatus\x12%\n" +
	"\x0etrigger_origin\x18\x0f \x01(\tR\rtriggerOrigin\x12%\n" +
	"\x0etrigger_states\x18\x10 \x03(\tR\rtriggerStatesBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_AdOpportunityEvent_proto_rawDescOnce sync.Once
	file_include_AdOpportunityEvent_proto_rawDescData []byte
)

func file_include_AdOpportunityEvent_proto_rawDescGZIP() []byte {
	file_include_AdOpportunityEvent_proto_rawDescOnce.Do(func() {
		file_include_AdOpportunityEvent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_AdOpportunityEvent_proto_rawDesc), len(file_include_AdOpportunityEvent_proto_rawDesc)))
	})
	return file_include_AdOpportunityEvent_proto_rawDescData
}

var file_include_AdOpportunityEvent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_AdOpportunityEvent_proto_goTypes = []any{
	(*AdOpportunityEvent)(nil), // 0: spotify.event_sender.proto.AdOpportunityEvent
}
var file_include_AdOpportunityEvent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_AdOpportunityEvent_proto_init() }
func file_include_AdOpportunityEvent_proto_init() {
	if File_include_AdOpportunityEvent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_AdOpportunityEvent_proto_rawDesc), len(file_include_AdOpportunityEvent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_AdOpportunityEvent_proto_goTypes,
		DependencyIndexes: file_include_AdOpportunityEvent_proto_depIdxs,
		MessageInfos:      file_include_AdOpportunityEvent_proto_msgTypes,
	}.Build()
	File_include_AdOpportunityEvent_proto = out.File
	file_include_AdOpportunityEvent_proto_goTypes = nil
	file_include_AdOpportunityEvent_proto_depIdxs = nil
}
