// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/AudioRateLimit.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioRateLimit struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DriverName            *string                `protobuf:"bytes,1,opt,name=driver_name,json=driverName" json:"driver_name,omitempty"`
	OutputDeviceName      *string                `protobuf:"bytes,2,opt,name=output_device_name,json=outputDeviceName" json:"output_device_name,omitempty"`
	OutputDeviceCategory  *string                `protobuf:"bytes,3,opt,name=output_device_category,json=outputDeviceCategory" json:"output_device_category,omitempty"`
	MaxSize               *int64                 `protobuf:"varint,4,opt,name=max_size,json=maxSize" json:"max_size,omitempty"`
	RefillPerMilliseconds *int64                 `protobuf:"varint,5,opt,name=refill_per_milliseconds,json=refillPerMilliseconds" json:"refill_per_milliseconds,omitempty"`
	FramesRequested       *int64                 `protobuf:"varint,6,opt,name=frames_requested,json=framesRequested" json:"frames_requested,omitempty"`
	FramesAcquired        *int64                 `protobuf:"varint,7,opt,name=frames_acquired,json=framesAcquired" json:"frames_acquired,omitempty"`
	PlaybackId            []byte                 `protobuf:"bytes,8,opt,name=playback_id,json=playbackId" json:"playback_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AudioRateLimit) Reset() {
	*x = AudioRateLimit{}
	mi := &file_include_AudioRateLimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioRateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioRateLimit) ProtoMessage() {}

func (x *AudioRateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_include_AudioRateLimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioRateLimit.ProtoReflect.Descriptor instead.
func (*AudioRateLimit) Descriptor() ([]byte, []int) {
	return file_include_AudioRateLimit_proto_rawDescGZIP(), []int{0}
}

func (x *AudioRateLimit) GetDriverName() string {
	if x != nil && x.DriverName != nil {
		return *x.DriverName
	}
	return ""
}

func (x *AudioRateLimit) GetOutputDeviceName() string {
	if x != nil && x.OutputDeviceName != nil {
		return *x.OutputDeviceName
	}
	return ""
}

func (x *AudioRateLimit) GetOutputDeviceCategory() string {
	if x != nil && x.OutputDeviceCategory != nil {
		return *x.OutputDeviceCategory
	}
	return ""
}

func (x *AudioRateLimit) GetMaxSize() int64 {
	if x != nil && x.MaxSize != nil {
		return *x.MaxSize
	}
	return 0
}

func (x *AudioRateLimit) GetRefillPerMilliseconds() int64 {
	if x != nil && x.RefillPerMilliseconds != nil {
		return *x.RefillPerMilliseconds
	}
	return 0
}

func (x *AudioRateLimit) GetFramesRequested() int64 {
	if x != nil && x.FramesRequested != nil {
		return *x.FramesRequested
	}
	return 0
}

func (x *AudioRateLimit) GetFramesAcquired() int64 {
	if x != nil && x.FramesAcquired != nil {
		return *x.FramesAcquired
	}
	return 0
}

func (x *AudioRateLimit) GetPlaybackId() []byte {
	if x != nil {
		return x.PlaybackId
	}
	return nil
}

var File_include_AudioRateLimit_proto protoreflect.FileDescriptor

const file_include_AudioRateLimit_proto_rawDesc = "" +
	"\n" +
	"\x1cinclude/AudioRateLimit.proto\x12\x1aspotify.event_sender.proto\"\xdd\x02\n" +
	"\x0eAudioRateLimit\x12\x1f\n" +
	"\vdriver_name\x18\x01 \x01(\tR\n" +
	"driverName\x12,\n" +
	"\x12output_device_name\x18\x02 \x01(\tR\x10outputDeviceName\x124\n" +
	"\x16output_device_category\x18\x03 \x01(\tR\x14outputDeviceCategory\x12\x19\n" +
	"\bmax_size\x18\x04 \x01(\x03R\amaxSize\x126\n" +
	"\x17refill_per_milliseconds\x18\x05 \x01(\x03R\x15refillPerMilliseconds\x12)\n" +
	"\x10frames_requested\x18\x06 \x01(\x03R\x0fframesRequested\x12'\n" +
	"\x0fframes_acquired\x18\a \x01(\x03R\x0eframesAcquired\x12\x1f\n" +
	"\vplayback_id\x18\b \x01(\fR\n" +
	"playbackIdBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_AudioRateLimit_proto_rawDescOnce sync.Once
	file_include_AudioRateLimit_proto_rawDescData []byte
)

func file_include_AudioRateLimit_proto_rawDescGZIP() []byte {
	file_include_AudioRateLimit_proto_rawDescOnce.Do(func() {
		file_include_AudioRateLimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_AudioRateLimit_proto_rawDesc), len(file_include_AudioRateLimit_proto_rawDesc)))
	})
	return file_include_AudioRateLimit_proto_rawDescData
}

var file_include_AudioRateLimit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_AudioRateLimit_proto_goTypes = []any{
	(*AudioRateLimit)(nil), // 0: spotify.event_sender.proto.AudioRateLimit
}
var file_include_AudioRateLimit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_AudioRateLimit_proto_init() }
func file_include_AudioRateLimit_proto_init() {
	if File_include_AudioRateLimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_AudioRateLimit_proto_rawDesc), len(file_include_AudioRateLimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_AudioRateLimit_proto_goTypes,
		DependencyIndexes: file_include_AudioRateLimit_proto_depIdxs,
		MessageInfos:      file_include_AudioRateLimit_proto_msgTypes,
	}.Build()
	File_include_AudioRateLimit_proto = out.File
	file_include_AudioRateLimit_proto_goTypes = nil
	file_include_AudioRateLimit_proto_depIdxs = nil
}
