// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/ConnectDeviceDiscovered.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectDeviceDiscovered struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	DeviceId                     *string                `protobuf:"bytes,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DiscoverMethod               *string                `protobuf:"bytes,2,opt,name=discover_method,json=discoverMethod" json:"discover_method,omitempty"`
	DiscoveredDeviceId           *string                `protobuf:"bytes,3,opt,name=discovered_device_id,json=discoveredDeviceId" json:"discovered_device_id,omitempty"`
	DiscoveredDeviceType         *string                `protobuf:"bytes,4,opt,name=discovered_device_type,json=discoveredDeviceType" json:"discovered_device_type,omitempty"`
	DiscoveredLibraryVersion     *string                `protobuf:"bytes,5,opt,name=discovered_library_version,json=discoveredLibraryVersion" json:"discovered_library_version,omitempty"`
	DiscoveredBrandDisplayName   *string                `protobuf:"bytes,6,opt,name=discovered_brand_display_name,json=discoveredBrandDisplayName" json:"discovered_brand_display_name,omitempty"`
	DiscoveredModelDisplayName   *string                `protobuf:"bytes,7,opt,name=discovered_model_display_name,json=discoveredModelDisplayName" json:"discovered_model_display_name,omitempty"`
	DiscoveredClientId           *string                `protobuf:"bytes,8,opt,name=discovered_client_id,json=discoveredClientId" json:"discovered_client_id,omitempty"`
	DiscoveredProductId          *string                `protobuf:"bytes,9,opt,name=discovered_product_id,json=discoveredProductId" json:"discovered_product_id,omitempty"`
	DiscoveredDeviceAvailablilty *string                `protobuf:"bytes,10,opt,name=discovered_device_availablilty,json=discoveredDeviceAvailablilty" json:"discovered_device_availablilty,omitempty"`
	DiscoveredDevicePublicKey    *string                `protobuf:"bytes,11,opt,name=discovered_device_public_key,json=discoveredDevicePublicKey" json:"discovered_device_public_key,omitempty"`
	CapabilitiesResolved         *bool                  `protobuf:"varint,12,opt,name=capabilities_resolved,json=capabilitiesResolved" json:"capabilities_resolved,omitempty"`
	LocalTime                    *string                `protobuf:"bytes,13,opt,name=local_time,json=localTime" json:"local_time,omitempty"`
	DiscoveredTokenType          *string                `protobuf:"bytes,14,opt,name=discovered_token_type,json=discoveredTokenType" json:"discovered_token_type,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ConnectDeviceDiscovered) Reset() {
	*x = ConnectDeviceDiscovered{}
	mi := &file_include_ConnectDeviceDiscovered_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDeviceDiscovered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDeviceDiscovered) ProtoMessage() {}

func (x *ConnectDeviceDiscovered) ProtoReflect() protoreflect.Message {
	mi := &file_include_ConnectDeviceDiscovered_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDeviceDiscovered.ProtoReflect.Descriptor instead.
func (*ConnectDeviceDiscovered) Descriptor() ([]byte, []int) {
	return file_include_ConnectDeviceDiscovered_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectDeviceDiscovered) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoverMethod() string {
	if x != nil && x.DiscoverMethod != nil {
		return *x.DiscoverMethod
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredDeviceId() string {
	if x != nil && x.DiscoveredDeviceId != nil {
		return *x.DiscoveredDeviceId
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredDeviceType() string {
	if x != nil && x.DiscoveredDeviceType != nil {
		return *x.DiscoveredDeviceType
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredLibraryVersion() string {
	if x != nil && x.DiscoveredLibraryVersion != nil {
		return *x.DiscoveredLibraryVersion
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredBrandDisplayName() string {
	if x != nil && x.DiscoveredBrandDisplayName != nil {
		return *x.DiscoveredBrandDisplayName
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredModelDisplayName() string {
	if x != nil && x.DiscoveredModelDisplayName != nil {
		return *x.DiscoveredModelDisplayName
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredClientId() string {
	if x != nil && x.DiscoveredClientId != nil {
		return *x.DiscoveredClientId
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredProductId() string {
	if x != nil && x.DiscoveredProductId != nil {
		return *x.DiscoveredProductId
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredDeviceAvailablilty() string {
	if x != nil && x.DiscoveredDeviceAvailablilty != nil {
		return *x.DiscoveredDeviceAvailablilty
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredDevicePublicKey() string {
	if x != nil && x.DiscoveredDevicePublicKey != nil {
		return *x.DiscoveredDevicePublicKey
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetCapabilitiesResolved() bool {
	if x != nil && x.CapabilitiesResolved != nil {
		return *x.CapabilitiesResolved
	}
	return false
}

func (x *ConnectDeviceDiscovered) GetLocalTime() string {
	if x != nil && x.LocalTime != nil {
		return *x.LocalTime
	}
	return ""
}

func (x *ConnectDeviceDiscovered) GetDiscoveredTokenType() string {
	if x != nil && x.DiscoveredTokenType != nil {
		return *x.DiscoveredTokenType
	}
	return ""
}

var File_include_ConnectDeviceDiscovered_proto protoreflect.FileDescriptor

const file_include_ConnectDeviceDiscovered_proto_rawDesc = "" +
	"\n" +
	"%include/ConnectDeviceDiscovered.proto\x12\x1aspotify.event_sender.proto\"\x80\x06\n" +
	"\x17ConnectDeviceDiscovered\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12'\n" +
	"\x0fdiscover_method\x18\x02 \x01(\tR\x0ediscoverMethod\x120\n" +
	"\x14discovered_device_id\x18\x03 \x01(\tR\x12discoveredDeviceId\x124\n" +
	"\x16discovered_device_type\x18\x04 \x01(\tR\x14discoveredDeviceType\x12<\n" +
	"\x1adiscovered_library_version\x18\x05 \x01(\tR\x18discoveredLibraryVersion\x12A\n" +
	"\x1ddiscovered_brand_display_name\x18\x06 \x01(\tR\x1adiscoveredBrandDisplayName\x12A\n" +
	"\x1ddiscovered_model_display_name\x18\a \x01(\tR\x1adiscoveredModelDisplayName\x120\n" +
	"\x14discovered_client_id\x18\b \x01(\tR\x12discoveredClientId\x122\n" +
	"\x15discovered_product_id\x18\t \x01(\tR\x13discoveredProductId\x12D\n" +
	"\x1ediscovered_device_availablilty\x18\n" +
	" \x01(\tR\x1cdiscoveredDeviceAvailablilty\x12?\n" +
	"\x1cdiscovered_device_public_key\x18\v \x01(\tR\x19discoveredDevicePublicKey\x123\n" +
	"\x15capabilities_resolved\x18\f \x01(\bR\x14capabilitiesResolved\x12\x1d\n" +
	"\n" +
	"local_time\x18\r \x01(\tR\tlocalTime\x122\n" +
	"\x15discovered_token_type\x18\x0e \x01(\tR\x13discoveredTokenTypeBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_ConnectDeviceDiscovered_proto_rawDescOnce sync.Once
	file_include_ConnectDeviceDiscovered_proto_rawDescData []byte
)

func file_include_ConnectDeviceDiscovered_proto_rawDescGZIP() []byte {
	file_include_ConnectDeviceDiscovered_proto_rawDescOnce.Do(func() {
		file_include_ConnectDeviceDiscovered_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_ConnectDeviceDiscovered_proto_rawDesc), len(file_include_ConnectDeviceDiscovered_proto_rawDesc)))
	})
	return file_include_ConnectDeviceDiscovered_proto_rawDescData
}

var file_include_ConnectDeviceDiscovered_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_ConnectDeviceDiscovered_proto_goTypes = []any{
	(*ConnectDeviceDiscovered)(nil), // 0: spotify.event_sender.proto.ConnectDeviceDiscovered
}
var file_include_ConnectDeviceDiscovered_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_ConnectDeviceDiscovered_proto_init() }
func file_include_ConnectDeviceDiscovered_proto_init() {
	if File_include_ConnectDeviceDiscovered_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_ConnectDeviceDiscovered_proto_rawDesc), len(file_include_ConnectDeviceDiscovered_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_ConnectDeviceDiscovered_proto_goTypes,
		DependencyIndexes: file_include_ConnectDeviceDiscovered_proto_depIdxs,
		MessageInfos:      file_include_ConnectDeviceDiscovered_proto_msgTypes,
	}.Build()
	File_include_ConnectDeviceDiscovered_proto = out.File
	file_include_ConnectDeviceDiscovered_proto_goTypes = nil
	file_include_ConnectDeviceDiscovered_proto_depIdxs = nil
}
