// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/EventSenderCanaryNonAuth.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventSenderCanaryNonAuth struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BatchUuid             *string                `protobuf:"bytes,1,opt,name=batch_uuid,json=batchUuid" json:"batch_uuid,omitempty"`
	EventId               *int64                 `protobuf:"varint,2,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	BatchSize             *int64                 `protobuf:"varint,3,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	SendingSystem         *string                `protobuf:"bytes,4,opt,name=sending_system,json=sendingSystem" json:"sending_system,omitempty"`
	SentAsPendingEvent    *bool                  `protobuf:"varint,5,opt,name=sent_as_pending_event,json=sentAsPendingEvent" json:"sent_as_pending_event,omitempty"`
	BatchStartTimeMs      *int64                 `protobuf:"varint,6,opt,name=batch_start_time_ms,json=batchStartTimeMs" json:"batch_start_time_ms,omitempty"`
	EventTimeMs           *int64                 `protobuf:"varint,7,opt,name=event_time_ms,json=eventTimeMs" json:"event_time_ms,omitempty"`
	Configuration         *string                `protobuf:"bytes,8,opt,name=configuration" json:"configuration,omitempty"`
	ExperimentVariant     *string                `protobuf:"bytes,9,opt,name=experiment_variant,json=experimentVariant" json:"experiment_variant,omitempty"`
	MutationCount         *int64                 `protobuf:"varint,10,opt,name=mutation_count,json=mutationCount" json:"mutation_count,omitempty"`
	ExpectedMutationCount *int64                 `protobuf:"varint,11,opt,name=expected_mutation_count,json=expectedMutationCount" json:"expected_mutation_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventSenderCanaryNonAuth) Reset() {
	*x = EventSenderCanaryNonAuth{}
	mi := &file_include_EventSenderCanaryNonAuth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSenderCanaryNonAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSenderCanaryNonAuth) ProtoMessage() {}

func (x *EventSenderCanaryNonAuth) ProtoReflect() protoreflect.Message {
	mi := &file_include_EventSenderCanaryNonAuth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSenderCanaryNonAuth.ProtoReflect.Descriptor instead.
func (*EventSenderCanaryNonAuth) Descriptor() ([]byte, []int) {
	return file_include_EventSenderCanaryNonAuth_proto_rawDescGZIP(), []int{0}
}

func (x *EventSenderCanaryNonAuth) GetBatchUuid() string {
	if x != nil && x.BatchUuid != nil {
		return *x.BatchUuid
	}
	return ""
}

func (x *EventSenderCanaryNonAuth) GetEventId() int64 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *EventSenderCanaryNonAuth) GetBatchSize() int64 {
	if x != nil && x.BatchSize != nil {
		return *x.BatchSize
	}
	return 0
}

func (x *EventSenderCanaryNonAuth) GetSendingSystem() string {
	if x != nil && x.SendingSystem != nil {
		return *x.SendingSystem
	}
	return ""
}

func (x *EventSenderCanaryNonAuth) GetSentAsPendingEvent() bool {
	if x != nil && x.SentAsPendingEvent != nil {
		return *x.SentAsPendingEvent
	}
	return false
}

func (x *EventSenderCanaryNonAuth) GetBatchStartTimeMs() int64 {
	if x != nil && x.BatchStartTimeMs != nil {
		return *x.BatchStartTimeMs
	}
	return 0
}

func (x *EventSenderCanaryNonAuth) GetEventTimeMs() int64 {
	if x != nil && x.EventTimeMs != nil {
		return *x.EventTimeMs
	}
	return 0
}

func (x *EventSenderCanaryNonAuth) GetConfiguration() string {
	if x != nil && x.Configuration != nil {
		return *x.Configuration
	}
	return ""
}

func (x *EventSenderCanaryNonAuth) GetExperimentVariant() string {
	if x != nil && x.ExperimentVariant != nil {
		return *x.ExperimentVariant
	}
	return ""
}

func (x *EventSenderCanaryNonAuth) GetMutationCount() int64 {
	if x != nil && x.MutationCount != nil {
		return *x.MutationCount
	}
	return 0
}

func (x *EventSenderCanaryNonAuth) GetExpectedMutationCount() int64 {
	if x != nil && x.ExpectedMutationCount != nil {
		return *x.ExpectedMutationCount
	}
	return 0
}

var File_include_EventSenderCanaryNonAuth_proto protoreflect.FileDescriptor

const file_include_EventSenderCanaryNonAuth_proto_rawDesc = "" +
	"\n" +
	"&include/EventSenderCanaryNonAuth.proto\x12\x1aspotify.event_sender.proto\"\xd4\x03\n" +
	"\x18EventSenderCanaryNonAuth\x12\x1d\n" +
	"\n" +
	"batch_uuid\x18\x01 \x01(\tR\tbatchUuid\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x03R\tbatchSize\x12%\n" +
	"\x0esending_system\x18\x04 \x01(\tR\rsendingSystem\x121\n" +
	"\x15sent_as_pending_event\x18\x05 \x01(\bR\x12sentAsPendingEvent\x12-\n" +
	"\x13batch_start_time_ms\x18\x06 \x01(\x03R\x10batchStartTimeMs\x12\"\n" +
	"\revent_time_ms\x18\a \x01(\x03R\veventTimeMs\x12$\n" +
	"\rconfiguration\x18\b \x01(\tR\rconfiguration\x12-\n" +
	"\x12experiment_variant\x18\t \x01(\tR\x11experimentVariant\x12%\n" +
	"\x0emutation_count\x18\n" +
	" \x01(\x03R\rmutationCount\x126\n" +
	"\x17expected_mutation_count\x18\v \x01(\x03R\x15expectedMutationCountBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_EventSenderCanaryNonAuth_proto_rawDescOnce sync.Once
	file_include_EventSenderCanaryNonAuth_proto_rawDescData []byte
)

func file_include_EventSenderCanaryNonAuth_proto_rawDescGZIP() []byte {
	file_include_EventSenderCanaryNonAuth_proto_rawDescOnce.Do(func() {
		file_include_EventSenderCanaryNonAuth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_EventSenderCanaryNonAuth_proto_rawDesc), len(file_include_EventSenderCanaryNonAuth_proto_rawDesc)))
	})
	return file_include_EventSenderCanaryNonAuth_proto_rawDescData
}

var file_include_EventSenderCanaryNonAuth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_EventSenderCanaryNonAuth_proto_goTypes = []any{
	(*EventSenderCanaryNonAuth)(nil), // 0: spotify.event_sender.proto.EventSenderCanaryNonAuth
}
var file_include_EventSenderCanaryNonAuth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_EventSenderCanaryNonAuth_proto_init() }
func file_include_EventSenderCanaryNonAuth_proto_init() {
	if File_include_EventSenderCanaryNonAuth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_EventSenderCanaryNonAuth_proto_rawDesc), len(file_include_EventSenderCanaryNonAuth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_EventSenderCanaryNonAuth_proto_goTypes,
		DependencyIndexes: file_include_EventSenderCanaryNonAuth_proto_depIdxs,
		MessageInfos:      file_include_EventSenderCanaryNonAuth_proto_msgTypes,
	}.Build()
	File_include_EventSenderCanaryNonAuth_proto = out.File
	file_include_EventSenderCanaryNonAuth_proto_goTypes = nil
	file_include_EventSenderCanaryNonAuth_proto_depIdxs = nil
}
