// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/OfflinePlayableCacheReport.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfflinePlayableCacheReport struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NumTracks              *int64                 `protobuf:"varint,1,opt,name=num_tracks,json=numTracks" json:"num_tracks,omitempty"`
	NumMissingFiles        *int64                 `protobuf:"varint,2,opt,name=num_missing_files,json=numMissingFiles" json:"num_missing_files,omitempty"`
	NumMissingKeys         *int64                 `protobuf:"varint,3,opt,name=num_missing_keys,json=numMissingKeys" json:"num_missing_keys,omitempty"`
	NumMissingMetadata     *int64                 `protobuf:"varint,4,opt,name=num_missing_metadata,json=numMissingMetadata" json:"num_missing_metadata,omitempty"`
	NumExpired             *int64                 `protobuf:"varint,5,opt,name=num_expired,json=numExpired" json:"num_expired,omitempty"`
	NumMissingInAudioIndex *int64                 `protobuf:"varint,6,opt,name=num_missing_in_audio_index,json=numMissingInAudioIndex" json:"num_missing_in_audio_index,omitempty"`
	TotalTime              *int64                 `protobuf:"varint,7,opt,name=total_time,json=totalTime" json:"total_time,omitempty"`
	NumBatches             *int64                 `protobuf:"varint,8,opt,name=num_batches,json=numBatches" json:"num_batches,omitempty"`
	NumPreviouslyPlayed    *int64                 `protobuf:"varint,9,opt,name=num_previously_played,json=numPreviouslyPlayed" json:"num_previously_played,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OfflinePlayableCacheReport) Reset() {
	*x = OfflinePlayableCacheReport{}
	mi := &file_include_OfflinePlayableCacheReport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflinePlayableCacheReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflinePlayableCacheReport) ProtoMessage() {}

func (x *OfflinePlayableCacheReport) ProtoReflect() protoreflect.Message {
	mi := &file_include_OfflinePlayableCacheReport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflinePlayableCacheReport.ProtoReflect.Descriptor instead.
func (*OfflinePlayableCacheReport) Descriptor() ([]byte, []int) {
	return file_include_OfflinePlayableCacheReport_proto_rawDescGZIP(), []int{0}
}

func (x *OfflinePlayableCacheReport) GetNumTracks() int64 {
	if x != nil && x.NumTracks != nil {
		return *x.NumTracks
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumMissingFiles() int64 {
	if x != nil && x.NumMissingFiles != nil {
		return *x.NumMissingFiles
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumMissingKeys() int64 {
	if x != nil && x.NumMissingKeys != nil {
		return *x.NumMissingKeys
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumMissingMetadata() int64 {
	if x != nil && x.NumMissingMetadata != nil {
		return *x.NumMissingMetadata
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumExpired() int64 {
	if x != nil && x.NumExpired != nil {
		return *x.NumExpired
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumMissingInAudioIndex() int64 {
	if x != nil && x.NumMissingInAudioIndex != nil {
		return *x.NumMissingInAudioIndex
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetTotalTime() int64 {
	if x != nil && x.TotalTime != nil {
		return *x.TotalTime
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumBatches() int64 {
	if x != nil && x.NumBatches != nil {
		return *x.NumBatches
	}
	return 0
}

func (x *OfflinePlayableCacheReport) GetNumPreviouslyPlayed() int64 {
	if x != nil && x.NumPreviouslyPlayed != nil {
		return *x.NumPreviouslyPlayed
	}
	return 0
}

var File_include_OfflinePlayableCacheReport_proto protoreflect.FileDescriptor

const file_include_OfflinePlayableCacheReport_proto_rawDesc = "" +
	"\n" +
	"(include/OfflinePlayableCacheReport.proto\x12\x1aspotify.event_sender.proto\"\x94\x03\n" +
	"\x1aOfflinePlayableCacheReport\x12\x1d\n" +
	"\n" +
	"num_tracks\x18\x01 \x01(\x03R\tnumTracks\x12*\n" +
	"\x11num_missing_files\x18\x02 \x01(\x03R\x0fnumMissingFiles\x12(\n" +
	"\x10num_missing_keys\x18\x03 \x01(\x03R\x0enumMissingKeys\x120\n" +
	"\x14num_missing_metadata\x18\x04 \x01(\x03R\x12numMissingMetadata\x12\x1f\n" +
	"\vnum_expired\x18\x05 \x01(\x03R\n" +
	"numExpired\x12:\n" +
	"\x1anum_missing_in_audio_index\x18\x06 \x01(\x03R\x16numMissingInAudioIndex\x12\x1d\n" +
	"\n" +
	"total_time\x18\a \x01(\x03R\ttotalTime\x12\x1f\n" +
	"\vnum_batches\x18\b \x01(\x03R\n" +
	"numBatches\x122\n" +
	"\x15num_previously_played\x18\t \x01(\x03R\x13numPreviouslyPlayedBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_OfflinePlayableCacheReport_proto_rawDescOnce sync.Once
	file_include_OfflinePlayableCacheReport_proto_rawDescData []byte
)

func file_include_OfflinePlayableCacheReport_proto_rawDescGZIP() []byte {
	file_include_OfflinePlayableCacheReport_proto_rawDescOnce.Do(func() {
		file_include_OfflinePlayableCacheReport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_OfflinePlayableCacheReport_proto_rawDesc), len(file_include_OfflinePlayableCacheReport_proto_rawDesc)))
	})
	return file_include_OfflinePlayableCacheReport_proto_rawDescData
}

var file_include_OfflinePlayableCacheReport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_OfflinePlayableCacheReport_proto_goTypes = []any{
	(*OfflinePlayableCacheReport)(nil), // 0: spotify.event_sender.proto.OfflinePlayableCacheReport
}
var file_include_OfflinePlayableCacheReport_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_OfflinePlayableCacheReport_proto_init() }
func file_include_OfflinePlayableCacheReport_proto_init() {
	if File_include_OfflinePlayableCacheReport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_OfflinePlayableCacheReport_proto_rawDesc), len(file_include_OfflinePlayableCacheReport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_OfflinePlayableCacheReport_proto_goTypes,
		DependencyIndexes: file_include_OfflinePlayableCacheReport_proto_depIdxs,
		MessageInfos:      file_include_OfflinePlayableCacheReport_proto_msgTypes,
	}.Build()
	File_include_OfflinePlayableCacheReport_proto = out.File
	file_include_OfflinePlayableCacheReport_proto_goTypes = nil
	file_include_OfflinePlayableCacheReport_proto_depIdxs = nil
}
