// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/PartnerApiEventNonAuth.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartnerApiEventNonAuth struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectionType *string                `protobuf:"bytes,1,opt,name=connection_type,json=connectionType" json:"connection_type,omitempty"`
	ClientId       *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	ClientName     *string                `protobuf:"bytes,3,opt,name=client_name,json=clientName" json:"client_name,omitempty"`
	Action         *string                `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Parameters     *string                `protobuf:"bytes,5,opt,name=parameters" json:"parameters,omitempty"`
	Error          *string                `protobuf:"bytes,6,opt,name=error" json:"error,omitempty"`
	TimeMs         *int64                 `protobuf:"varint,7,opt,name=time_ms,json=timeMs" json:"time_ms,omitempty"`
	AppVariant     *string                `protobuf:"bytes,8,opt,name=app_variant,json=appVariant" json:"app_variant,omitempty"`
	ClientVersion  *string                `protobuf:"bytes,9,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PartnerApiEventNonAuth) Reset() {
	*x = PartnerApiEventNonAuth{}
	mi := &file_include_PartnerApiEventNonAuth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartnerApiEventNonAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnerApiEventNonAuth) ProtoMessage() {}

func (x *PartnerApiEventNonAuth) ProtoReflect() protoreflect.Message {
	mi := &file_include_PartnerApiEventNonAuth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnerApiEventNonAuth.ProtoReflect.Descriptor instead.
func (*PartnerApiEventNonAuth) Descriptor() ([]byte, []int) {
	return file_include_PartnerApiEventNonAuth_proto_rawDescGZIP(), []int{0}
}

func (x *PartnerApiEventNonAuth) GetConnectionType() string {
	if x != nil && x.ConnectionType != nil {
		return *x.ConnectionType
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetClientName() string {
	if x != nil && x.ClientName != nil {
		return *x.ClientName
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetAction() string {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetTimeMs() int64 {
	if x != nil && x.TimeMs != nil {
		return *x.TimeMs
	}
	return 0
}

func (x *PartnerApiEventNonAuth) GetAppVariant() string {
	if x != nil && x.AppVariant != nil {
		return *x.AppVariant
	}
	return ""
}

func (x *PartnerApiEventNonAuth) GetClientVersion() string {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return ""
}

var File_include_PartnerApiEventNonAuth_proto protoreflect.FileDescriptor

const file_include_PartnerApiEventNonAuth_proto_rawDesc = "" +
	"\n" +
	"$include/PartnerApiEventNonAuth.proto\x12\x1aspotify.event_sender.proto\"\xae\x02\n" +
	"\x16PartnerApiEventNonAuth\x12'\n" +
	"\x0fconnection_type\x18\x01 \x01(\tR\x0econnectionType\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"parameters\x18\x05 \x01(\tR\n" +
	"parameters\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x17\n" +
	"\atime_ms\x18\a \x01(\x03R\x06timeMs\x12\x1f\n" +
	"\vapp_variant\x18\b \x01(\tR\n" +
	"appVariant\x12%\n" +
	"\x0eclient_version\x18\t \x01(\tR\rclientVersionBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_PartnerApiEventNonAuth_proto_rawDescOnce sync.Once
	file_include_PartnerApiEventNonAuth_proto_rawDescData []byte
)

func file_include_PartnerApiEventNonAuth_proto_rawDescGZIP() []byte {
	file_include_PartnerApiEventNonAuth_proto_rawDescOnce.Do(func() {
		file_include_PartnerApiEventNonAuth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_PartnerApiEventNonAuth_proto_rawDesc), len(file_include_PartnerApiEventNonAuth_proto_rawDesc)))
	})
	return file_include_PartnerApiEventNonAuth_proto_rawDescData
}

var file_include_PartnerApiEventNonAuth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_PartnerApiEventNonAuth_proto_goTypes = []any{
	(*PartnerApiEventNonAuth)(nil), // 0: spotify.event_sender.proto.PartnerApiEventNonAuth
}
var file_include_PartnerApiEventNonAuth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_PartnerApiEventNonAuth_proto_init() }
func file_include_PartnerApiEventNonAuth_proto_init() {
	if File_include_PartnerApiEventNonAuth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_PartnerApiEventNonAuth_proto_rawDesc), len(file_include_PartnerApiEventNonAuth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_PartnerApiEventNonAuth_proto_goTypes,
		DependencyIndexes: file_include_PartnerApiEventNonAuth_proto_depIdxs,
		MessageInfos:      file_include_PartnerApiEventNonAuth_proto_msgTypes,
	}.Build()
	File_include_PartnerApiEventNonAuth_proto = out.File
	file_include_PartnerApiEventNonAuth_proto_goTypes = nil
	file_include_PartnerApiEventNonAuth_proto_depIdxs = nil
}
