// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/PubSubCountPerIdent.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSubCountPerIdent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentFilter           *string                `protobuf:"bytes,1,opt,name=ident_filter,json=identFilter" json:"ident_filter,omitempty"`
	NoOfMessagesReceived  *int32                 `protobuf:"varint,2,opt,name=no_of_messages_received,json=noOfMessagesReceived" json:"no_of_messages_received,omitempty"`
	NoOfFailedConversions *int32                 `protobuf:"varint,3,opt,name=no_of_failed_conversions,json=noOfFailedConversions" json:"no_of_failed_conversions,omitempty"`
	Implementation        *string                `protobuf:"bytes,4,opt,name=implementation" json:"implementation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PubSubCountPerIdent) Reset() {
	*x = PubSubCountPerIdent{}
	mi := &file_include_PubSubCountPerIdent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubCountPerIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubCountPerIdent) ProtoMessage() {}

func (x *PubSubCountPerIdent) ProtoReflect() protoreflect.Message {
	mi := &file_include_PubSubCountPerIdent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubCountPerIdent.ProtoReflect.Descriptor instead.
func (*PubSubCountPerIdent) Descriptor() ([]byte, []int) {
	return file_include_PubSubCountPerIdent_proto_rawDescGZIP(), []int{0}
}

func (x *PubSubCountPerIdent) GetIdentFilter() string {
	if x != nil && x.IdentFilter != nil {
		return *x.IdentFilter
	}
	return ""
}

func (x *PubSubCountPerIdent) GetNoOfMessagesReceived() int32 {
	if x != nil && x.NoOfMessagesReceived != nil {
		return *x.NoOfMessagesReceived
	}
	return 0
}

func (x *PubSubCountPerIdent) GetNoOfFailedConversions() int32 {
	if x != nil && x.NoOfFailedConversions != nil {
		return *x.NoOfFailedConversions
	}
	return 0
}

func (x *PubSubCountPerIdent) GetImplementation() string {
	if x != nil && x.Implementation != nil {
		return *x.Implementation
	}
	return ""
}

var File_include_PubSubCountPerIdent_proto protoreflect.FileDescriptor

const file_include_PubSubCountPerIdent_proto_rawDesc = "" +
	"\n" +
	"!include/PubSubCountPerIdent.proto\x12\x1aspotify.event_sender.proto\"\xd0\x01\n" +
	"\x13PubSubCountPerIdent\x12!\n" +
	"\fident_filter\x18\x01 \x01(\tR\videntFilter\x125\n" +
	"\x17no_of_messages_received\x18\x02 \x01(\x05R\x14noOfMessagesReceived\x127\n" +
	"\x18no_of_failed_conversions\x18\x03 \x01(\x05R\x15noOfFailedConversions\x12&\n" +
	"\x0eimplementation\x18\x04 \x01(\tR\x0eimplementationBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_PubSubCountPerIdent_proto_rawDescOnce sync.Once
	file_include_PubSubCountPerIdent_proto_rawDescData []byte
)

func file_include_PubSubCountPerIdent_proto_rawDescGZIP() []byte {
	file_include_PubSubCountPerIdent_proto_rawDescOnce.Do(func() {
		file_include_PubSubCountPerIdent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_PubSubCountPerIdent_proto_rawDesc), len(file_include_PubSubCountPerIdent_proto_rawDesc)))
	})
	return file_include_PubSubCountPerIdent_proto_rawDescData
}

var file_include_PubSubCountPerIdent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_PubSubCountPerIdent_proto_goTypes = []any{
	(*PubSubCountPerIdent)(nil), // 0: spotify.event_sender.proto.PubSubCountPerIdent
}
var file_include_PubSubCountPerIdent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_PubSubCountPerIdent_proto_init() }
func file_include_PubSubCountPerIdent_proto_init() {
	if File_include_PubSubCountPerIdent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_PubSubCountPerIdent_proto_rawDesc), len(file_include_PubSubCountPerIdent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_PubSubCountPerIdent_proto_goTypes,
		DependencyIndexes: file_include_PubSubCountPerIdent_proto_depIdxs,
		MessageInfos:      file_include_PubSubCountPerIdent_proto_msgTypes,
	}.Build()
	File_include_PubSubCountPerIdent_proto = out.File
	file_include_PubSubCountPerIdent_proto_goTypes = nil
	file_include_PubSubCountPerIdent_proto_depIdxs = nil
}
