// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: include/TrackErrorBypass.proto

package event_sender

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackErrorBypass struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode        *int64                 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage     *string                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	ErrorCategory    *string                `protobuf:"bytes,3,opt,name=error_category,json=errorCategory" json:"error_category,omitempty"`
	PlaybackId       []byte                 `protobuf:"bytes,4,opt,name=playback_id,json=playbackId" json:"playback_id,omitempty"`
	TrackId          *string                `protobuf:"bytes,5,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
	FileId           []byte                 `protobuf:"bytes,6,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
	PositionMs       *int64                 `protobuf:"varint,7,opt,name=position_ms,json=positionMs" json:"position_ms,omitempty"`
	ClientTimestamp  *int64                 `protobuf:"varint,8,opt,name=client_timestamp,json=clientTimestamp" json:"client_timestamp,omitempty"`
	Audiocodec       *string                `protobuf:"bytes,9,opt,name=audiocodec" json:"audiocodec,omitempty"`
	Bitrate          *int64                 `protobuf:"varint,10,opt,name=bitrate" json:"bitrate,omitempty"`
	ExternalTrack    *bool                  `protobuf:"varint,11,opt,name=external_track,json=externalTrack" json:"external_track,omitempty"`
	IsRetryEvent     *bool                  `protobuf:"varint,12,opt,name=is_retry_event,json=isRetryEvent" json:"is_retry_event,omitempty"`
	RetryCount       *int64                 `protobuf:"varint,13,opt,name=retry_count,json=retryCount" json:"retry_count,omitempty"`
	RetryReason      *string                `protobuf:"bytes,14,opt,name=retry_reason,json=retryReason" json:"retry_reason,omitempty"`
	MaxRetries       *int64                 `protobuf:"varint,15,opt,name=max_retries,json=maxRetries" json:"max_retries,omitempty"`
	RetriesExhausted *bool                  `protobuf:"varint,16,opt,name=retries_exhausted,json=retriesExhausted" json:"retries_exhausted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackErrorBypass) Reset() {
	*x = TrackErrorBypass{}
	mi := &file_include_TrackErrorBypass_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackErrorBypass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackErrorBypass) ProtoMessage() {}

func (x *TrackErrorBypass) ProtoReflect() protoreflect.Message {
	mi := &file_include_TrackErrorBypass_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackErrorBypass.ProtoReflect.Descriptor instead.
func (*TrackErrorBypass) Descriptor() ([]byte, []int) {
	return file_include_TrackErrorBypass_proto_rawDescGZIP(), []int{0}
}

func (x *TrackErrorBypass) GetErrorCode() int64 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *TrackErrorBypass) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *TrackErrorBypass) GetErrorCategory() string {
	if x != nil && x.ErrorCategory != nil {
		return *x.ErrorCategory
	}
	return ""
}

func (x *TrackErrorBypass) GetPlaybackId() []byte {
	if x != nil {
		return x.PlaybackId
	}
	return nil
}

func (x *TrackErrorBypass) GetTrackId() string {
	if x != nil && x.TrackId != nil {
		return *x.TrackId
	}
	return ""
}

func (x *TrackErrorBypass) GetFileId() []byte {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *TrackErrorBypass) GetPositionMs() int64 {
	if x != nil && x.PositionMs != nil {
		return *x.PositionMs
	}
	return 0
}

func (x *TrackErrorBypass) GetClientTimestamp() int64 {
	if x != nil && x.ClientTimestamp != nil {
		return *x.ClientTimestamp
	}
	return 0
}

func (x *TrackErrorBypass) GetAudiocodec() string {
	if x != nil && x.Audiocodec != nil {
		return *x.Audiocodec
	}
	return ""
}

func (x *TrackErrorBypass) GetBitrate() int64 {
	if x != nil && x.Bitrate != nil {
		return *x.Bitrate
	}
	return 0
}

func (x *TrackErrorBypass) GetExternalTrack() bool {
	if x != nil && x.ExternalTrack != nil {
		return *x.ExternalTrack
	}
	return false
}

func (x *TrackErrorBypass) GetIsRetryEvent() bool {
	if x != nil && x.IsRetryEvent != nil {
		return *x.IsRetryEvent
	}
	return false
}

func (x *TrackErrorBypass) GetRetryCount() int64 {
	if x != nil && x.RetryCount != nil {
		return *x.RetryCount
	}
	return 0
}

func (x *TrackErrorBypass) GetRetryReason() string {
	if x != nil && x.RetryReason != nil {
		return *x.RetryReason
	}
	return ""
}

func (x *TrackErrorBypass) GetMaxRetries() int64 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

func (x *TrackErrorBypass) GetRetriesExhausted() bool {
	if x != nil && x.RetriesExhausted != nil {
		return *x.RetriesExhausted
	}
	return false
}

var File_include_TrackErrorBypass_proto protoreflect.FileDescriptor

const file_include_TrackErrorBypass_proto_rawDesc = "" +
	"\n" +
	"\x1einclude/TrackErrorBypass.proto\x12\x1aspotify.event_sender.proto\"\xb7\x04\n" +
	"\x10TrackErrorBypass\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x03R\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eerror_category\x18\x03 \x01(\tR\rerrorCategory\x12\x1f\n" +
	"\vplayback_id\x18\x04 \x01(\fR\n" +
	"playbackId\x12\x19\n" +
	"\btrack_id\x18\x05 \x01(\tR\atrackId\x12\x17\n" +
	"\afile_id\x18\x06 \x01(\fR\x06fileId\x12\x1f\n" +
	"\vposition_ms\x18\a \x01(\x03R\n" +
	"positionMs\x12)\n" +
	"\x10client_timestamp\x18\b \x01(\x03R\x0fclientTimestamp\x12\x1e\n" +
	"\n" +
	"audiocodec\x18\t \x01(\tR\n" +
	"audiocodec\x12\x18\n" +
	"\abitrate\x18\n" +
	" \x01(\x03R\abitrate\x12%\n" +
	"\x0eexternal_track\x18\v \x01(\bR\rexternalTrack\x12$\n" +
	"\x0eis_retry_event\x18\f \x01(\bR\fisRetryEvent\x12\x1f\n" +
	"\vretry_count\x18\r \x01(\x03R\n" +
	"retryCount\x12!\n" +
	"\fretry_reason\x18\x0e \x01(\tR\vretryReason\x12\x1f\n" +
	"\vmax_retries\x18\x0f \x01(\x03R\n" +
	"maxRetries\x12+\n" +
	"\x11retries_exhausted\x18\x10 \x01(\bR\x10retriesExhaustedBEZCgithub.com/pyrorhythm/libspot/api/spotify/event_sender;event_sender"

var (
	file_include_TrackErrorBypass_proto_rawDescOnce sync.Once
	file_include_TrackErrorBypass_proto_rawDescData []byte
)

func file_include_TrackErrorBypass_proto_rawDescGZIP() []byte {
	file_include_TrackErrorBypass_proto_rawDescOnce.Do(func() {
		file_include_TrackErrorBypass_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_include_TrackErrorBypass_proto_rawDesc), len(file_include_TrackErrorBypass_proto_rawDesc)))
	})
	return file_include_TrackErrorBypass_proto_rawDescData
}

var file_include_TrackErrorBypass_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_include_TrackErrorBypass_proto_goTypes = []any{
	(*TrackErrorBypass)(nil), // 0: spotify.event_sender.proto.TrackErrorBypass
}
var file_include_TrackErrorBypass_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_include_TrackErrorBypass_proto_init() }
func file_include_TrackErrorBypass_proto_init() {
	if File_include_TrackErrorBypass_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_include_TrackErrorBypass_proto_rawDesc), len(file_include_TrackErrorBypass_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_include_TrackErrorBypass_proto_goTypes,
		DependencyIndexes: file_include_TrackErrorBypass_proto_depIdxs,
		MessageInfos:      file_include_TrackErrorBypass_proto_msgTypes,
	}.Build()
	File_include_TrackErrorBypass_proto = out.File
	file_include_TrackErrorBypass_proto_goTypes = nil
	file_include_TrackErrorBypass_proto_depIdxs = nil
}
