// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: state_restore/circuit_breaker_rules.proto

package state_restore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CircuitBreakerRules struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DiscardedTrackUids []string               `protobuf:"bytes,1,rep,name=discarded_track_uids,json=discardedTrackUids" json:"discarded_track_uids,omitempty"`
	NumErroredTracks   *int32                 `protobuf:"varint,2,req,name=num_errored_tracks,json=numErroredTracks" json:"num_errored_tracks,omitempty"`
	ContextTrackPlayed *bool                  `protobuf:"varint,3,req,name=context_track_played,json=contextTrackPlayed" json:"context_track_played,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CircuitBreakerRules) Reset() {
	*x = CircuitBreakerRules{}
	mi := &file_state_restore_circuit_breaker_rules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerRules) ProtoMessage() {}

func (x *CircuitBreakerRules) ProtoReflect() protoreflect.Message {
	mi := &file_state_restore_circuit_breaker_rules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerRules.ProtoReflect.Descriptor instead.
func (*CircuitBreakerRules) Descriptor() ([]byte, []int) {
	return file_state_restore_circuit_breaker_rules_proto_rawDescGZIP(), []int{0}
}

func (x *CircuitBreakerRules) GetDiscardedTrackUids() []string {
	if x != nil {
		return x.DiscardedTrackUids
	}
	return nil
}

func (x *CircuitBreakerRules) GetNumErroredTracks() int32 {
	if x != nil && x.NumErroredTracks != nil {
		return *x.NumErroredTracks
	}
	return 0
}

func (x *CircuitBreakerRules) GetContextTrackPlayed() bool {
	if x != nil && x.ContextTrackPlayed != nil {
		return *x.ContextTrackPlayed
	}
	return false
}

var File_state_restore_circuit_breaker_rules_proto protoreflect.FileDescriptor

const file_state_restore_circuit_breaker_rules_proto_rawDesc = "" +
	"\n" +
	")state_restore/circuit_breaker_rules.proto\x12\"spotify.player.proto.state_restore\"\xa7\x01\n" +
	"\x13CircuitBreakerRules\x120\n" +
	"\x14discarded_track_uids\x18\x01 \x03(\tR\x12discardedTrackUids\x12,\n" +
	"\x12num_errored_tracks\x18\x02 \x02(\x05R\x10numErroredTracks\x120\n" +
	"\x14context_track_played\x18\x03 \x02(\bR\x12contextTrackPlayedBNZLgithub.com/pyrorhythm/libspot/api/spotify/player/state_restore;state_restore"

var (
	file_state_restore_circuit_breaker_rules_proto_rawDescOnce sync.Once
	file_state_restore_circuit_breaker_rules_proto_rawDescData []byte
)

func file_state_restore_circuit_breaker_rules_proto_rawDescGZIP() []byte {
	file_state_restore_circuit_breaker_rules_proto_rawDescOnce.Do(func() {
		file_state_restore_circuit_breaker_rules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_restore_circuit_breaker_rules_proto_rawDesc), len(file_state_restore_circuit_breaker_rules_proto_rawDesc)))
	})
	return file_state_restore_circuit_breaker_rules_proto_rawDescData
}

var file_state_restore_circuit_breaker_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_restore_circuit_breaker_rules_proto_goTypes = []any{
	(*CircuitBreakerRules)(nil), // 0: spotify.player.proto.state_restore.CircuitBreakerRules
}
var file_state_restore_circuit_breaker_rules_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_state_restore_circuit_breaker_rules_proto_init() }
func file_state_restore_circuit_breaker_rules_proto_init() {
	if File_state_restore_circuit_breaker_rules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_restore_circuit_breaker_rules_proto_rawDesc), len(file_state_restore_circuit_breaker_rules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_restore_circuit_breaker_rules_proto_goTypes,
		DependencyIndexes: file_state_restore_circuit_breaker_rules_proto_depIdxs,
		MessageInfos:      file_state_restore_circuit_breaker_rules_proto_msgTypes,
	}.Build()
	File_state_restore_circuit_breaker_rules_proto = out.File
	file_state_restore_circuit_breaker_rules_proto_goTypes = nil
	file_state_restore_circuit_breaker_rules_proto_depIdxs = nil
}
