// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: state_restore/player_session_fake.proto

package state_restore

import (
	player "github.com/pyrorhythm/libspot/api/spotify/player"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerSessionFake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerState   *ContextPlayerState    `protobuf:"bytes,1,req,name=player_state,json=playerState" json:"player_state,omitempty"`
	PlayerContext *player.Context        `protobuf:"bytes,2,req,name=player_context,json=playerContext" json:"player_context,omitempty"`
	IsFinished    *bool                  `protobuf:"varint,3,req,name=is_finished,json=isFinished" json:"is_finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSessionFake) Reset() {
	*x = PlayerSessionFake{}
	mi := &file_state_restore_player_session_fake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSessionFake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSessionFake) ProtoMessage() {}

func (x *PlayerSessionFake) ProtoReflect() protoreflect.Message {
	mi := &file_state_restore_player_session_fake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSessionFake.ProtoReflect.Descriptor instead.
func (*PlayerSessionFake) Descriptor() ([]byte, []int) {
	return file_state_restore_player_session_fake_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerSessionFake) GetPlayerState() *ContextPlayerState {
	if x != nil {
		return x.PlayerState
	}
	return nil
}

func (x *PlayerSessionFake) GetPlayerContext() *player.Context {
	if x != nil {
		return x.PlayerContext
	}
	return nil
}

func (x *PlayerSessionFake) GetIsFinished() bool {
	if x != nil && x.IsFinished != nil {
		return *x.IsFinished
	}
	return false
}

var File_state_restore_player_session_fake_proto protoreflect.FileDescriptor

const file_state_restore_player_session_fake_proto_rawDesc = "" +
	"\n" +
	"'state_restore/player_session_fake.proto\x12\"spotify.player.proto.state_restore\x1a\rcontext.proto\x1a(state_restore/context_player_state.proto\"\xd5\x01\n" +
	"\x11PlayerSessionFake\x12Y\n" +
	"\fplayer_state\x18\x01 \x02(\v26.spotify.player.proto.state_restore.ContextPlayerStateR\vplayerState\x12D\n" +
	"\x0eplayer_context\x18\x02 \x02(\v2\x1d.spotify.player.proto.ContextR\rplayerContext\x12\x1f\n" +
	"\vis_finished\x18\x03 \x02(\bR\n" +
	"isFinishedBNZLgithub.com/pyrorhythm/libspot/api/spotify/player/state_restore;state_restore"

var (
	file_state_restore_player_session_fake_proto_rawDescOnce sync.Once
	file_state_restore_player_session_fake_proto_rawDescData []byte
)

func file_state_restore_player_session_fake_proto_rawDescGZIP() []byte {
	file_state_restore_player_session_fake_proto_rawDescOnce.Do(func() {
		file_state_restore_player_session_fake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_restore_player_session_fake_proto_rawDesc), len(file_state_restore_player_session_fake_proto_rawDesc)))
	})
	return file_state_restore_player_session_fake_proto_rawDescData
}

var file_state_restore_player_session_fake_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_state_restore_player_session_fake_proto_goTypes = []any{
	(*PlayerSessionFake)(nil),  // 0: spotify.player.proto.state_restore.PlayerSessionFake
	(*ContextPlayerState)(nil), // 1: spotify.player.proto.state_restore.ContextPlayerState
	(*player.Context)(nil),     // 2: spotify.player.proto.Context
}
var file_state_restore_player_session_fake_proto_depIdxs = []int32{
	1, // 0: spotify.player.proto.state_restore.PlayerSessionFake.player_state:type_name -> spotify.player.proto.state_restore.ContextPlayerState
	2, // 1: spotify.player.proto.state_restore.PlayerSessionFake.player_context:type_name -> spotify.player.proto.Context
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_state_restore_player_session_fake_proto_init() }
func file_state_restore_player_session_fake_proto_init() {
	if File_state_restore_player_session_fake_proto != nil {
		return
	}
	file_state_restore_context_player_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_restore_player_session_fake_proto_rawDesc), len(file_state_restore_player_session_fake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_restore_player_session_fake_proto_goTypes,
		DependencyIndexes: file_state_restore_player_session_fake_proto_depIdxs,
		MessageInfos:      file_state_restore_player_session_fake_proto_msgTypes,
	}.Build()
	File_state_restore_player_session_fake_proto = out.File
	file_state_restore_player_session_fake_proto_goTypes = nil
	file_state_restore_player_session_fake_proto_depIdxs = nil
}
