// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: spotify/list/v1/model/requested_fields.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributesRequestedFields struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestedField []AttributeKind        `protobuf:"varint,1,rep,packed,name=requested_field,json=requestedField,proto3,enum=spotify.list.v1.model.AttributeKind" json:"requested_field,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttributesRequestedFields) Reset() {
	*x = AttributesRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributesRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributesRequestedFields) ProtoMessage() {}

func (x *AttributesRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributesRequestedFields.ProtoReflect.Descriptor instead.
func (*AttributesRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{0}
}

func (x *AttributesRequestedFields) GetRequestedField() []AttributeKind {
	if x != nil {
		return x.RequestedField
	}
	return nil
}

type ItemRequestedFields struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            *bool                      `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Attributes    *AttributesRequestedFields `protobuf:"bytes,2,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequestedFields) Reset() {
	*x = ItemRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequestedFields) ProtoMessage() {}

func (x *ItemRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequestedFields.ProtoReflect.Descriptor instead.
func (*ItemRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{1}
}

func (x *ItemRequestedFields) GetId() bool {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return false
}

func (x *ItemRequestedFields) GetAttributes() *AttributesRequestedFields {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type MetaItemsRequestedFields struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Attributes    *AttributesRequestedFields `protobuf:"bytes,1,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaItemsRequestedFields) Reset() {
	*x = MetaItemsRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaItemsRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaItemsRequestedFields) ProtoMessage() {}

func (x *MetaItemsRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaItemsRequestedFields.ProtoReflect.Descriptor instead.
func (*MetaItemsRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{2}
}

func (x *MetaItemsRequestedFields) GetAttributes() *AttributesRequestedFields {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type LensRemovedItemsRequestedFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         *ItemRequestedFields   `protobuf:"bytes,1,opt,name=items,proto3,oneof" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LensRemovedItemsRequestedFields) Reset() {
	*x = LensRemovedItemsRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LensRemovedItemsRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LensRemovedItemsRequestedFields) ProtoMessage() {}

func (x *LensRemovedItemsRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LensRemovedItemsRequestedFields.ProtoReflect.Descriptor instead.
func (*LensRemovedItemsRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{3}
}

func (x *LensRemovedItemsRequestedFields) GetItems() *ItemRequestedFields {
	if x != nil {
		return x.Items
	}
	return nil
}

type LensEffectRequestedFields struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	LensRemovedItems *LensRemovedItemsRequestedFields `protobuf:"bytes,1,opt,name=lens_removed_items,json=lensRemovedItems,proto3,oneof" json:"lens_removed_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LensEffectRequestedFields) Reset() {
	*x = LensEffectRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LensEffectRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LensEffectRequestedFields) ProtoMessage() {}

func (x *LensEffectRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LensEffectRequestedFields.ProtoReflect.Descriptor instead.
func (*LensEffectRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{4}
}

func (x *LensEffectRequestedFields) GetLensRemovedItems() *LensRemovedItemsRequestedFields {
	if x != nil {
		return x.LensRemovedItems
	}
	return nil
}

type ListEntityRequestedFields struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Attributes    *AttributesRequestedFields `protobuf:"bytes,1,opt,name=attributes,proto3,oneof" json:"attributes,omitempty"`
	Items         *ItemRequestedFields       `protobuf:"bytes,2,opt,name=items,proto3,oneof" json:"items,omitempty"`
	MetaItems     *MetaItemsRequestedFields  `protobuf:"bytes,3,opt,name=meta_items,json=metaItems,proto3,oneof" json:"meta_items,omitempty"`
	LensEffect    *LensEffectRequestedFields `protobuf:"bytes,4,opt,name=lens_effect,json=lensEffect,proto3,oneof" json:"lens_effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntityRequestedFields) Reset() {
	*x = ListEntityRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntityRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntityRequestedFields) ProtoMessage() {}

func (x *ListEntityRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntityRequestedFields.ProtoReflect.Descriptor instead.
func (*ListEntityRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{5}
}

func (x *ListEntityRequestedFields) GetAttributes() *AttributesRequestedFields {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ListEntityRequestedFields) GetItems() *ItemRequestedFields {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListEntityRequestedFields) GetMetaItems() *MetaItemsRequestedFields {
	if x != nil {
		return x.MetaItems
	}
	return nil
}

func (x *ListEntityRequestedFields) GetLensEffect() *LensEffectRequestedFields {
	if x != nil {
		return x.LensEffect
	}
	return nil
}

type ListResponseRequestedFields struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entity        *ListEntityRequestedFields `protobuf:"bytes,1,opt,name=entity,proto3,oneof" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponseRequestedFields) Reset() {
	*x = ListResponseRequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponseRequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponseRequestedFields) ProtoMessage() {}

func (x *ListResponseRequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponseRequestedFields.ProtoReflect.Descriptor instead.
func (*ListResponseRequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponseRequestedFields) GetEntity() *ListEntityRequestedFields {
	if x != nil {
		return x.Entity
	}
	return nil
}

type RequestedFields struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	All           *bool                        `protobuf:"varint,1,opt,name=all,proto3,oneof" json:"all,omitempty"`
	ListResponse  *ListResponseRequestedFields `protobuf:"bytes,2,opt,name=list_response,json=listResponse,proto3,oneof" json:"list_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedFields) Reset() {
	*x = RequestedFields{}
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedFields) ProtoMessage() {}

func (x *RequestedFields) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_list_v1_model_requested_fields_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedFields.ProtoReflect.Descriptor instead.
func (*RequestedFields) Descriptor() ([]byte, []int) {
	return file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP(), []int{7}
}

func (x *RequestedFields) GetAll() bool {
	if x != nil && x.All != nil {
		return *x.All
	}
	return false
}

func (x *RequestedFields) GetListResponse() *ListResponseRequestedFields {
	if x != nil {
		return x.ListResponse
	}
	return nil
}

var File_spotify_list_v1_model_requested_fields_proto protoreflect.FileDescriptor

const file_spotify_list_v1_model_requested_fields_proto_rawDesc = "" +
	"\n" +
	",spotify/list/v1/model/requested_fields.proto\x12\x15spotify.list.v1.model\x1a+spotify/list/v1/model/attribute_kinds.proto\"j\n" +
	"\x19AttributesRequestedFields\x12M\n" +
	"\x0frequested_field\x18\x01 \x03(\x0e2$.spotify.list.v1.model.AttributeKindR\x0erequestedField\"\x97\x01\n" +
	"\x13ItemRequestedFields\x12\x13\n" +
	"\x02id\x18\x01 \x01(\bH\x00R\x02id\x88\x01\x01\x12U\n" +
	"\n" +
	"attributes\x18\x02 \x01(\v20.spotify.list.v1.model.AttributesRequestedFieldsH\x01R\n" +
	"attributes\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_attributes\"\x86\x01\n" +
	"\x18MetaItemsRequestedFields\x12U\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v20.spotify.list.v1.model.AttributesRequestedFieldsH\x00R\n" +
	"attributes\x88\x01\x01B\r\n" +
	"\v_attributesJ\x04\b\x02\x10\x03\"r\n" +
	"\x1fLensRemovedItemsRequestedFields\x12E\n" +
	"\x05items\x18\x01 \x01(\v2*.spotify.list.v1.model.ItemRequestedFieldsH\x00R\x05items\x88\x01\x01B\b\n" +
	"\x06_items\"\x9d\x01\n" +
	"\x19LensEffectRequestedFields\x12i\n" +
	"\x12lens_removed_items\x18\x01 \x01(\v26.spotify.list.v1.model.LensRemovedItemsRequestedFieldsH\x00R\x10lensRemovedItems\x88\x01\x01B\x15\n" +
	"\x13_lens_removed_items\"\x9e\x03\n" +
	"\x19ListEntityRequestedFields\x12U\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v20.spotify.list.v1.model.AttributesRequestedFieldsH\x00R\n" +
	"attributes\x88\x01\x01\x12E\n" +
	"\x05items\x18\x02 \x01(\v2*.spotify.list.v1.model.ItemRequestedFieldsH\x01R\x05items\x88\x01\x01\x12S\n" +
	"\n" +
	"meta_items\x18\x03 \x01(\v2/.spotify.list.v1.model.MetaItemsRequestedFieldsH\x02R\tmetaItems\x88\x01\x01\x12V\n" +
	"\vlens_effect\x18\x04 \x01(\v20.spotify.list.v1.model.LensEffectRequestedFieldsH\x03R\n" +
	"lensEffect\x88\x01\x01B\r\n" +
	"\v_attributesB\b\n" +
	"\x06_itemsB\r\n" +
	"\v_meta_itemsB\x0e\n" +
	"\f_lens_effect\"}\n" +
	"\x1bListResponseRequestedFields\x12M\n" +
	"\x06entity\x18\x01 \x01(\v20.spotify.list.v1.model.ListEntityRequestedFieldsH\x00R\x06entity\x88\x01\x01B\t\n" +
	"\a_entityJ\x04\b\x02\x10\x03\"\xa0\x01\n" +
	"\x0fRequestedFields\x12\x15\n" +
	"\x03all\x18\x01 \x01(\bH\x00R\x03all\x88\x01\x01\x12\\\n" +
	"\rlist_response\x18\x02 \x01(\v22.spotify.list.v1.model.ListResponseRequestedFieldsH\x01R\flistResponse\x88\x01\x01B\x06\n" +
	"\x04_allB\x10\n" +
	"\x0e_list_responseBr\n" +
	"\x19com.spotify.list.v1.modelB\x14RequestedFieldsProtoP\x01Z=github.com/pyrorhythm/libspot/api/spotify/list/v1/model;modelb\x06proto3"

var (
	file_spotify_list_v1_model_requested_fields_proto_rawDescOnce sync.Once
	file_spotify_list_v1_model_requested_fields_proto_rawDescData []byte
)

func file_spotify_list_v1_model_requested_fields_proto_rawDescGZIP() []byte {
	file_spotify_list_v1_model_requested_fields_proto_rawDescOnce.Do(func() {
		file_spotify_list_v1_model_requested_fields_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_list_v1_model_requested_fields_proto_rawDesc), len(file_spotify_list_v1_model_requested_fields_proto_rawDesc)))
	})
	return file_spotify_list_v1_model_requested_fields_proto_rawDescData
}

var file_spotify_list_v1_model_requested_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_spotify_list_v1_model_requested_fields_proto_goTypes = []any{
	(*AttributesRequestedFields)(nil),       // 0: spotify.list.v1.model.AttributesRequestedFields
	(*ItemRequestedFields)(nil),             // 1: spotify.list.v1.model.ItemRequestedFields
	(*MetaItemsRequestedFields)(nil),        // 2: spotify.list.v1.model.MetaItemsRequestedFields
	(*LensRemovedItemsRequestedFields)(nil), // 3: spotify.list.v1.model.LensRemovedItemsRequestedFields
	(*LensEffectRequestedFields)(nil),       // 4: spotify.list.v1.model.LensEffectRequestedFields
	(*ListEntityRequestedFields)(nil),       // 5: spotify.list.v1.model.ListEntityRequestedFields
	(*ListResponseRequestedFields)(nil),     // 6: spotify.list.v1.model.ListResponseRequestedFields
	(*RequestedFields)(nil),                 // 7: spotify.list.v1.model.RequestedFields
	(AttributeKind)(0),                      // 8: spotify.list.v1.model.AttributeKind
}
var file_spotify_list_v1_model_requested_fields_proto_depIdxs = []int32{
	8,  // 0: spotify.list.v1.model.AttributesRequestedFields.requested_field:type_name -> spotify.list.v1.model.AttributeKind
	0,  // 1: spotify.list.v1.model.ItemRequestedFields.attributes:type_name -> spotify.list.v1.model.AttributesRequestedFields
	0,  // 2: spotify.list.v1.model.MetaItemsRequestedFields.attributes:type_name -> spotify.list.v1.model.AttributesRequestedFields
	1,  // 3: spotify.list.v1.model.LensRemovedItemsRequestedFields.items:type_name -> spotify.list.v1.model.ItemRequestedFields
	3,  // 4: spotify.list.v1.model.LensEffectRequestedFields.lens_removed_items:type_name -> spotify.list.v1.model.LensRemovedItemsRequestedFields
	0,  // 5: spotify.list.v1.model.ListEntityRequestedFields.attributes:type_name -> spotify.list.v1.model.AttributesRequestedFields
	1,  // 6: spotify.list.v1.model.ListEntityRequestedFields.items:type_name -> spotify.list.v1.model.ItemRequestedFields
	2,  // 7: spotify.list.v1.model.ListEntityRequestedFields.meta_items:type_name -> spotify.list.v1.model.MetaItemsRequestedFields
	4,  // 8: spotify.list.v1.model.ListEntityRequestedFields.lens_effect:type_name -> spotify.list.v1.model.LensEffectRequestedFields
	5,  // 9: spotify.list.v1.model.ListResponseRequestedFields.entity:type_name -> spotify.list.v1.model.ListEntityRequestedFields
	6,  // 10: spotify.list.v1.model.RequestedFields.list_response:type_name -> spotify.list.v1.model.ListResponseRequestedFields
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_spotify_list_v1_model_requested_fields_proto_init() }
func file_spotify_list_v1_model_requested_fields_proto_init() {
	if File_spotify_list_v1_model_requested_fields_proto != nil {
		return
	}
	file_spotify_list_v1_model_attribute_kinds_proto_init()
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[1].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[2].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[3].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[4].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[5].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[6].OneofWrappers = []any{}
	file_spotify_list_v1_model_requested_fields_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_list_v1_model_requested_fields_proto_rawDesc), len(file_spotify_list_v1_model_requested_fields_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_list_v1_model_requested_fields_proto_goTypes,
		DependencyIndexes: file_spotify_list_v1_model_requested_fields_proto_depIdxs,
		MessageInfos:      file_spotify_list_v1_model_requested_fields_proto_msgTypes,
	}.Build()
	File_spotify_list_v1_model_requested_fields_proto = out.File
	file_spotify_list_v1_model_requested_fields_proto_goTypes = nil
	file_spotify_list_v1_model_requested_fields_proto_depIdxs = nil
}
