// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: es_context_player_state.proto

package esperanto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackQuality_BitrateLevel int32

const (
	PlaybackQuality_UNKNOWN   PlaybackQuality_BitrateLevel = 0
	PlaybackQuality_LOW       PlaybackQuality_BitrateLevel = 1
	PlaybackQuality_NORMAL    PlaybackQuality_BitrateLevel = 2
	PlaybackQuality_HIGH      PlaybackQuality_BitrateLevel = 3
	PlaybackQuality_VERY_HIGH PlaybackQuality_BitrateLevel = 4
	PlaybackQuality_HIFI      PlaybackQuality_BitrateLevel = 5
	PlaybackQuality_HIFI24    PlaybackQuality_BitrateLevel = 6
)

// Enum value maps for PlaybackQuality_BitrateLevel.
var (
	PlaybackQuality_BitrateLevel_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOW",
		2: "NORMAL",
		3: "HIGH",
		4: "VERY_HIGH",
		5: "HIFI",
		6: "HIFI24",
	}
	PlaybackQuality_BitrateLevel_value = map[string]int32{
		"UNKNOWN":   0,
		"LOW":       1,
		"NORMAL":    2,
		"HIGH":      3,
		"VERY_HIGH": 4,
		"HIFI":      5,
		"HIFI24":    6,
	}
)

func (x PlaybackQuality_BitrateLevel) Enum() *PlaybackQuality_BitrateLevel {
	p := new(PlaybackQuality_BitrateLevel)
	*p = x
	return p
}

func (x PlaybackQuality_BitrateLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackQuality_BitrateLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_es_context_player_state_proto_enumTypes[0].Descriptor()
}

func (PlaybackQuality_BitrateLevel) Type() protoreflect.EnumType {
	return &file_es_context_player_state_proto_enumTypes[0]
}

func (x PlaybackQuality_BitrateLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackQuality_BitrateLevel.Descriptor instead.
func (PlaybackQuality_BitrateLevel) EnumDescriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{1, 0}
}

type PlaybackQuality_BitrateStrategy int32

const (
	PlaybackQuality_UNKNOWN_STRATEGY PlaybackQuality_BitrateStrategy = 0
	PlaybackQuality_BEST_MATCHING    PlaybackQuality_BitrateStrategy = 1
	PlaybackQuality_BACKEND_ADVISED  PlaybackQuality_BitrateStrategy = 2
	PlaybackQuality_OFFLINED_FILE    PlaybackQuality_BitrateStrategy = 3
	PlaybackQuality_CACHED_FILE      PlaybackQuality_BitrateStrategy = 4
	PlaybackQuality_LOCAL_FILE       PlaybackQuality_BitrateStrategy = 5
)

// Enum value maps for PlaybackQuality_BitrateStrategy.
var (
	PlaybackQuality_BitrateStrategy_name = map[int32]string{
		0: "UNKNOWN_STRATEGY",
		1: "BEST_MATCHING",
		2: "BACKEND_ADVISED",
		3: "OFFLINED_FILE",
		4: "CACHED_FILE",
		5: "LOCAL_FILE",
	}
	PlaybackQuality_BitrateStrategy_value = map[string]int32{
		"UNKNOWN_STRATEGY": 0,
		"BEST_MATCHING":    1,
		"BACKEND_ADVISED":  2,
		"OFFLINED_FILE":    3,
		"CACHED_FILE":      4,
		"LOCAL_FILE":       5,
	}
)

func (x PlaybackQuality_BitrateStrategy) Enum() *PlaybackQuality_BitrateStrategy {
	p := new(PlaybackQuality_BitrateStrategy)
	*p = x
	return p
}

func (x PlaybackQuality_BitrateStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackQuality_BitrateStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_es_context_player_state_proto_enumTypes[1].Descriptor()
}

func (PlaybackQuality_BitrateStrategy) Type() protoreflect.EnumType {
	return &file_es_context_player_state_proto_enumTypes[1]
}

func (x PlaybackQuality_BitrateStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackQuality_BitrateStrategy.Descriptor instead.
func (PlaybackQuality_BitrateStrategy) EnumDescriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{1, 1}
}

type PlaybackQuality_HiFiStatus int32

const (
	PlaybackQuality_NONE PlaybackQuality_HiFiStatus = 0
	PlaybackQuality_OFF  PlaybackQuality_HiFiStatus = 1
	PlaybackQuality_ON   PlaybackQuality_HiFiStatus = 2
)

// Enum value maps for PlaybackQuality_HiFiStatus.
var (
	PlaybackQuality_HiFiStatus_name = map[int32]string{
		0: "NONE",
		1: "OFF",
		2: "ON",
	}
	PlaybackQuality_HiFiStatus_value = map[string]int32{
		"NONE": 0,
		"OFF":  1,
		"ON":   2,
	}
)

func (x PlaybackQuality_HiFiStatus) Enum() *PlaybackQuality_HiFiStatus {
	p := new(PlaybackQuality_HiFiStatus)
	*p = x
	return p
}

func (x PlaybackQuality_HiFiStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackQuality_HiFiStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_es_context_player_state_proto_enumTypes[2].Descriptor()
}

func (PlaybackQuality_HiFiStatus) Type() protoreflect.EnumType {
	return &file_es_context_player_state_proto_enumTypes[2]
}

func (x PlaybackQuality_HiFiStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackQuality_HiFiStatus.Descriptor instead.
func (PlaybackQuality_HiFiStatus) EnumDescriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{1, 2}
}

type ContextPlayerState_Format int32

const (
	ContextPlayerState_UNKNOWN ContextPlayerState_Format = 0
	ContextPlayerState_DEFAULT ContextPlayerState_Format = 1
	ContextPlayerState_PARROT  ContextPlayerState_Format = 2
)

// Enum value maps for ContextPlayerState_Format.
var (
	ContextPlayerState_Format_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEFAULT",
		2: "PARROT",
	}
	ContextPlayerState_Format_value = map[string]int32{
		"UNKNOWN": 0,
		"DEFAULT": 1,
		"PARROT":  2,
	}
)

func (x ContextPlayerState_Format) Enum() *ContextPlayerState_Format {
	p := new(ContextPlayerState_Format)
	*p = x
	return p
}

func (x ContextPlayerState_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContextPlayerState_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_es_context_player_state_proto_enumTypes[3].Descriptor()
}

func (ContextPlayerState_Format) Type() protoreflect.EnumType {
	return &file_es_context_player_state_proto_enumTypes[3]
}

func (x ContextPlayerState_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContextPlayerState_Format.Descriptor instead.
func (ContextPlayerState_Format) EnumDescriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{2, 0}
}

type ContextIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Track         uint64                 `protobuf:"varint,2,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextIndex) Reset() {
	*x = ContextIndex{}
	mi := &file_es_context_player_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextIndex) ProtoMessage() {}

func (x *ContextIndex) ProtoReflect() protoreflect.Message {
	mi := &file_es_context_player_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextIndex.ProtoReflect.Descriptor instead.
func (*ContextIndex) Descriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{0}
}

func (x *ContextIndex) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContextIndex) GetTrack() uint64 {
	if x != nil {
		return x.Track
	}
	return 0
}

type PlaybackQuality struct {
	state                  protoimpl.MessageState          `protogen:"open.v1"`
	BitrateLevel           PlaybackQuality_BitrateLevel    `protobuf:"varint,1,opt,name=bitrate_level,json=bitrateLevel,proto3,enum=spotify.player.esperanto.proto.PlaybackQuality_BitrateLevel" json:"bitrate_level,omitempty"`
	Strategy               PlaybackQuality_BitrateStrategy `protobuf:"varint,2,opt,name=strategy,proto3,enum=spotify.player.esperanto.proto.PlaybackQuality_BitrateStrategy" json:"strategy,omitempty"`
	TargetBitrateLevel     PlaybackQuality_BitrateLevel    `protobuf:"varint,3,opt,name=target_bitrate_level,json=targetBitrateLevel,proto3,enum=spotify.player.esperanto.proto.PlaybackQuality_BitrateLevel" json:"target_bitrate_level,omitempty"`
	TargetBitrateAvailable bool                            `protobuf:"varint,4,opt,name=target_bitrate_available,json=targetBitrateAvailable,proto3" json:"target_bitrate_available,omitempty"`
	HifiStatus             PlaybackQuality_HiFiStatus      `protobuf:"varint,5,opt,name=hifi_status,json=hifiStatus,proto3,enum=spotify.player.esperanto.proto.PlaybackQuality_HiFiStatus" json:"hifi_status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlaybackQuality) Reset() {
	*x = PlaybackQuality{}
	mi := &file_es_context_player_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackQuality) ProtoMessage() {}

func (x *PlaybackQuality) ProtoReflect() protoreflect.Message {
	mi := &file_es_context_player_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackQuality.ProtoReflect.Descriptor instead.
func (*PlaybackQuality) Descriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{1}
}

func (x *PlaybackQuality) GetBitrateLevel() PlaybackQuality_BitrateLevel {
	if x != nil {
		return x.BitrateLevel
	}
	return PlaybackQuality_UNKNOWN
}

func (x *PlaybackQuality) GetStrategy() PlaybackQuality_BitrateStrategy {
	if x != nil {
		return x.Strategy
	}
	return PlaybackQuality_UNKNOWN_STRATEGY
}

func (x *PlaybackQuality) GetTargetBitrateLevel() PlaybackQuality_BitrateLevel {
	if x != nil {
		return x.TargetBitrateLevel
	}
	return PlaybackQuality_UNKNOWN
}

func (x *PlaybackQuality) GetTargetBitrateAvailable() bool {
	if x != nil {
		return x.TargetBitrateAvailable
	}
	return false
}

func (x *PlaybackQuality) GetHifiStatus() PlaybackQuality_HiFiStatus {
	if x != nil {
		return x.HifiStatus
	}
	return PlaybackQuality_NONE
}

type ContextPlayerState struct {
	state                 protoimpl.MessageState                     `protogen:"open.v1"`
	Timestamp             uint64                                     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ContextUri            string                                     `protobuf:"bytes,2,opt,name=context_uri,json=contextUri,proto3" json:"context_uri,omitempty"`
	ContextUrl            string                                     `protobuf:"bytes,3,opt,name=context_url,json=contextUrl,proto3" json:"context_url,omitempty"`
	ContextRestrictions   *Restrictions                              `protobuf:"bytes,4,opt,name=context_restrictions,json=contextRestrictions,proto3" json:"context_restrictions,omitempty"`
	PlayOrigin            *PlayOrigin                                `protobuf:"bytes,5,opt,name=play_origin,json=playOrigin,proto3" json:"play_origin,omitempty"`
	Index                 *ContextIndex                              `protobuf:"bytes,6,opt,name=index,proto3" json:"index,omitempty"`
	Track                 *ProvidedTrack                             `protobuf:"bytes,7,opt,name=track,proto3" json:"track,omitempty"`
	PlaybackId            []byte                                     `protobuf:"bytes,8,opt,name=playback_id,json=playbackId,proto3" json:"playback_id,omitempty"`
	PlaybackQuality       *PlaybackQuality                           `protobuf:"bytes,9,opt,name=playback_quality,json=playbackQuality,proto3" json:"playback_quality,omitempty"`
	PlaybackSpeed         *OptionalDouble                            `protobuf:"bytes,10,opt,name=playback_speed,json=playbackSpeed,proto3" json:"playback_speed,omitempty"`
	PositionAsOfTimestamp *OptionalInt64                             `protobuf:"bytes,11,opt,name=position_as_of_timestamp,json=positionAsOfTimestamp,proto3" json:"position_as_of_timestamp,omitempty"`
	Duration              *OptionalInt64                             `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	IsPlaying             bool                                       `protobuf:"varint,13,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	IsPaused              bool                                       `protobuf:"varint,14,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	IsBuffering           bool                                       `protobuf:"varint,15,opt,name=is_buffering,json=isBuffering,proto3" json:"is_buffering,omitempty"`
	IsSystemInitiated     bool                                       `protobuf:"varint,16,opt,name=is_system_initiated,json=isSystemInitiated,proto3" json:"is_system_initiated,omitempty"`
	Options               *ContextPlayerOptions                      `protobuf:"bytes,17,opt,name=options,proto3" json:"options,omitempty"`
	Restrictions          *Restrictions                              `protobuf:"bytes,18,opt,name=restrictions,proto3" json:"restrictions,omitempty"`
	Suppressions          []string                                   `protobuf:"bytes,19,rep,name=suppressions,proto3" json:"suppressions,omitempty"`
	PrevTracks            []*ProvidedTrack                           `protobuf:"bytes,20,rep,name=prev_tracks,json=prevTracks,proto3" json:"prev_tracks,omitempty"`
	NextTracks            []*ProvidedTrack                           `protobuf:"bytes,21,rep,name=next_tracks,json=nextTracks,proto3" json:"next_tracks,omitempty"`
	ContextMetadata       []*ContextPlayerState_ContextMetadataEntry `protobuf:"bytes,22,rep,name=context_metadata,json=contextMetadata,proto3" json:"context_metadata,omitempty"`
	PageMetadata          []*ContextPlayerState_PageMetadataEntry    `protobuf:"bytes,23,rep,name=page_metadata,json=pageMetadata,proto3" json:"page_metadata,omitempty"`
	SessionId             string                                     `protobuf:"bytes,24,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	QueueRevision         uint64                                     `protobuf:"varint,25,opt,name=queue_revision,json=queueRevision,proto3" json:"queue_revision,omitempty"`
	AudioStream           PreparePlayOptions_AudioStream             `protobuf:"varint,26,opt,name=audio_stream,json=audioStream,proto3,enum=spotify.player.esperanto.proto.PreparePlayOptions_AudioStream" json:"audio_stream,omitempty"`
	Signals               []string                                   `protobuf:"bytes,27,rep,name=signals,proto3" json:"signals,omitempty"`
	SessionCommandId      string                                     `protobuf:"bytes,28,opt,name=session_command_id,json=sessionCommandId,proto3" json:"session_command_id,omitempty"`
	Format                *ContextPlayerState_Format                 `protobuf:"varint,29,opt,name=format,proto3,enum=spotify.player.esperanto.proto.ContextPlayerState_Format,oneof" json:"format,omitempty"`
	AdBreakContext        *AdBreakContext                            `protobuf:"bytes,30,opt,name=ad_break_context,json=adBreakContext,proto3,oneof" json:"ad_break_context,omitempty"`
	SleepTimer            *SleepTimer                                `protobuf:"bytes,31,opt,name=sleep_timer,json=sleepTimer,proto3,oneof" json:"sleep_timer,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContextPlayerState) Reset() {
	*x = ContextPlayerState{}
	mi := &file_es_context_player_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPlayerState) ProtoMessage() {}

func (x *ContextPlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_es_context_player_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPlayerState.ProtoReflect.Descriptor instead.
func (*ContextPlayerState) Descriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{2}
}

func (x *ContextPlayerState) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ContextPlayerState) GetContextUri() string {
	if x != nil {
		return x.ContextUri
	}
	return ""
}

func (x *ContextPlayerState) GetContextUrl() string {
	if x != nil {
		return x.ContextUrl
	}
	return ""
}

func (x *ContextPlayerState) GetContextRestrictions() *Restrictions {
	if x != nil {
		return x.ContextRestrictions
	}
	return nil
}

func (x *ContextPlayerState) GetPlayOrigin() *PlayOrigin {
	if x != nil {
		return x.PlayOrigin
	}
	return nil
}

func (x *ContextPlayerState) GetIndex() *ContextIndex {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *ContextPlayerState) GetTrack() *ProvidedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *ContextPlayerState) GetPlaybackId() []byte {
	if x != nil {
		return x.PlaybackId
	}
	return nil
}

func (x *ContextPlayerState) GetPlaybackQuality() *PlaybackQuality {
	if x != nil {
		return x.PlaybackQuality
	}
	return nil
}

func (x *ContextPlayerState) GetPlaybackSpeed() *OptionalDouble {
	if x != nil {
		return x.PlaybackSpeed
	}
	return nil
}

func (x *ContextPlayerState) GetPositionAsOfTimestamp() *OptionalInt64 {
	if x != nil {
		return x.PositionAsOfTimestamp
	}
	return nil
}

func (x *ContextPlayerState) GetDuration() *OptionalInt64 {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ContextPlayerState) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *ContextPlayerState) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

func (x *ContextPlayerState) GetIsBuffering() bool {
	if x != nil {
		return x.IsBuffering
	}
	return false
}

func (x *ContextPlayerState) GetIsSystemInitiated() bool {
	if x != nil {
		return x.IsSystemInitiated
	}
	return false
}

func (x *ContextPlayerState) GetOptions() *ContextPlayerOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ContextPlayerState) GetRestrictions() *Restrictions {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

func (x *ContextPlayerState) GetSuppressions() []string {
	if x != nil {
		return x.Suppressions
	}
	return nil
}

func (x *ContextPlayerState) GetPrevTracks() []*ProvidedTrack {
	if x != nil {
		return x.PrevTracks
	}
	return nil
}

func (x *ContextPlayerState) GetNextTracks() []*ProvidedTrack {
	if x != nil {
		return x.NextTracks
	}
	return nil
}

func (x *ContextPlayerState) GetContextMetadata() []*ContextPlayerState_ContextMetadataEntry {
	if x != nil {
		return x.ContextMetadata
	}
	return nil
}

func (x *ContextPlayerState) GetPageMetadata() []*ContextPlayerState_PageMetadataEntry {
	if x != nil {
		return x.PageMetadata
	}
	return nil
}

func (x *ContextPlayerState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContextPlayerState) GetQueueRevision() uint64 {
	if x != nil {
		return x.QueueRevision
	}
	return 0
}

func (x *ContextPlayerState) GetAudioStream() PreparePlayOptions_AudioStream {
	if x != nil {
		return x.AudioStream
	}
	return PreparePlayOptions_DEFAULT
}

func (x *ContextPlayerState) GetSignals() []string {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *ContextPlayerState) GetSessionCommandId() string {
	if x != nil {
		return x.SessionCommandId
	}
	return ""
}

func (x *ContextPlayerState) GetFormat() ContextPlayerState_Format {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ContextPlayerState_UNKNOWN
}

func (x *ContextPlayerState) GetAdBreakContext() *AdBreakContext {
	if x != nil {
		return x.AdBreakContext
	}
	return nil
}

func (x *ContextPlayerState) GetSleepTimer() *SleepTimer {
	if x != nil {
		return x.SleepTimer
	}
	return nil
}

type ContextPlayerState_ContextMetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPlayerState_ContextMetadataEntry) Reset() {
	*x = ContextPlayerState_ContextMetadataEntry{}
	mi := &file_es_context_player_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPlayerState_ContextMetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPlayerState_ContextMetadataEntry) ProtoMessage() {}

func (x *ContextPlayerState_ContextMetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_es_context_player_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPlayerState_ContextMetadataEntry.ProtoReflect.Descriptor instead.
func (*ContextPlayerState_ContextMetadataEntry) Descriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ContextPlayerState_ContextMetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextPlayerState_ContextMetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ContextPlayerState_PageMetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPlayerState_PageMetadataEntry) Reset() {
	*x = ContextPlayerState_PageMetadataEntry{}
	mi := &file_es_context_player_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPlayerState_PageMetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPlayerState_PageMetadataEntry) ProtoMessage() {}

func (x *ContextPlayerState_PageMetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_es_context_player_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPlayerState_PageMetadataEntry.ProtoReflect.Descriptor instead.
func (*ContextPlayerState_PageMetadataEntry) Descriptor() ([]byte, []int) {
	return file_es_context_player_state_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ContextPlayerState_PageMetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextPlayerState_PageMetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_es_context_player_state_proto protoreflect.FileDescriptor

const file_es_context_player_state_proto_rawDesc = "" +
	"\n" +
	"\x1des_context_player_state.proto\x12\x1espotify.player.esperanto.proto\x1a\x15es_restrictions.proto\x1a\x14es_play_origin.proto\x1a\x11es_optional.proto\x1a\x17es_provided_track.proto\x1a\x1fes_context_player_options.proto\x1a\x1des_prepare_play_options.proto\x1a\x19es_ad_break_context.proto\x1a\x14es_sleep_timer.proto\"8\n" +
	"\fContextIndex\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x04R\x04page\x12\x14\n" +
	"\x05track\x18\x02 \x01(\x04R\x05track\"\xe8\x05\n" +
	"\x0fPlaybackQuality\x12a\n" +
	"\rbitrate_level\x18\x01 \x01(\x0e2<.spotify.player.esperanto.proto.PlaybackQuality.BitrateLevelR\fbitrateLevel\x12[\n" +
	"\bstrategy\x18\x02 \x01(\x0e2?.spotify.player.esperanto.proto.PlaybackQuality.BitrateStrategyR\bstrategy\x12n\n" +
	"\x14target_bitrate_level\x18\x03 \x01(\x0e2<.spotify.player.esperanto.proto.PlaybackQuality.BitrateLevelR\x12targetBitrateLevel\x128\n" +
	"\x18target_bitrate_available\x18\x04 \x01(\bR\x16targetBitrateAvailable\x12[\n" +
	"\vhifi_status\x18\x05 \x01(\x0e2:.spotify.player.esperanto.proto.PlaybackQuality.HiFiStatusR\n" +
	"hifiStatus\"_\n" +
	"\fBitrateLevel\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\r\n" +
	"\tVERY_HIGH\x10\x04\x12\b\n" +
	"\x04HIFI\x10\x05\x12\n" +
	"\n" +
	"\x06HIFI24\x10\x06\"\x83\x01\n" +
	"\x0fBitrateStrategy\x12\x14\n" +
	"\x10UNKNOWN_STRATEGY\x10\x00\x12\x11\n" +
	"\rBEST_MATCHING\x10\x01\x12\x13\n" +
	"\x0fBACKEND_ADVISED\x10\x02\x12\x11\n" +
	"\rOFFLINED_FILE\x10\x03\x12\x0f\n" +
	"\vCACHED_FILE\x10\x04\x12\x0e\n" +
	"\n" +
	"LOCAL_FILE\x10\x05\"'\n" +
	"\n" +
	"HiFiStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03OFF\x10\x01\x12\x06\n" +
	"\x02ON\x10\x02\"\xdd\x11\n" +
	"\x12ContextPlayerState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1f\n" +
	"\vcontext_uri\x18\x02 \x01(\tR\n" +
	"contextUri\x12\x1f\n" +
	"\vcontext_url\x18\x03 \x01(\tR\n" +
	"contextUrl\x12_\n" +
	"\x14context_restrictions\x18\x04 \x01(\v2,.spotify.player.esperanto.proto.RestrictionsR\x13contextRestrictions\x12K\n" +
	"\vplay_origin\x18\x05 \x01(\v2*.spotify.player.esperanto.proto.PlayOriginR\n" +
	"playOrigin\x12B\n" +
	"\x05index\x18\x06 \x01(\v2,.spotify.player.esperanto.proto.ContextIndexR\x05index\x12C\n" +
	"\x05track\x18\a \x01(\v2-.spotify.player.esperanto.proto.ProvidedTrackR\x05track\x12\x1f\n" +
	"\vplayback_id\x18\b \x01(\fR\n" +
	"playbackId\x12Z\n" +
	"\x10playback_quality\x18\t \x01(\v2/.spotify.player.esperanto.proto.PlaybackQualityR\x0fplaybackQuality\x12U\n" +
	"\x0eplayback_speed\x18\n" +
	" \x01(\v2..spotify.player.esperanto.proto.OptionalDoubleR\rplaybackSpeed\x12f\n" +
	"\x18position_as_of_timestamp\x18\v \x01(\v2-.spotify.player.esperanto.proto.OptionalInt64R\x15positionAsOfTimestamp\x12I\n" +
	"\bduration\x18\f \x01(\v2-.spotify.player.esperanto.proto.OptionalInt64R\bduration\x12\x1d\n" +
	"\n" +
	"is_playing\x18\r \x01(\bR\tisPlaying\x12\x1b\n" +
	"\tis_paused\x18\x0e \x01(\bR\bisPaused\x12!\n" +
	"\fis_buffering\x18\x0f \x01(\bR\visBuffering\x12.\n" +
	"\x13is_system_initiated\x18\x10 \x01(\bR\x11isSystemInitiated\x12N\n" +
	"\aoptions\x18\x11 \x01(\v24.spotify.player.esperanto.proto.ContextPlayerOptionsR\aoptions\x12P\n" +
	"\frestrictions\x18\x12 \x01(\v2,.spotify.player.esperanto.proto.RestrictionsR\frestrictions\x12\"\n" +
	"\fsuppressions\x18\x13 \x03(\tR\fsuppressions\x12N\n" +
	"\vprev_tracks\x18\x14 \x03(\v2-.spotify.player.esperanto.proto.ProvidedTrackR\n" +
	"prevTracks\x12N\n" +
	"\vnext_tracks\x18\x15 \x03(\v2-.spotify.player.esperanto.proto.ProvidedTrackR\n" +
	"nextTracks\x12r\n" +
	"\x10context_metadata\x18\x16 \x03(\v2G.spotify.player.esperanto.proto.ContextPlayerState.ContextMetadataEntryR\x0fcontextMetadata\x12i\n" +
	"\rpage_metadata\x18\x17 \x03(\v2D.spotify.player.esperanto.proto.ContextPlayerState.PageMetadataEntryR\fpageMetadata\x12\x1d\n" +
	"\n" +
	"session_id\x18\x18 \x01(\tR\tsessionId\x12%\n" +
	"\x0equeue_revision\x18\x19 \x01(\x04R\rqueueRevision\x12a\n" +
	"\faudio_stream\x18\x1a \x01(\x0e2>.spotify.player.esperanto.proto.PreparePlayOptions.AudioStreamR\vaudioStream\x12\x18\n" +
	"\asignals\x18\x1b \x03(\tR\asignals\x12,\n" +
	"\x12session_command_id\x18\x1c \x01(\tR\x10sessionCommandId\x12V\n" +
	"\x06format\x18\x1d \x01(\x0e29.spotify.player.esperanto.proto.ContextPlayerState.FormatH\x00R\x06format\x88\x01\x01\x12]\n" +
	"\x10ad_break_context\x18\x1e \x01(\v2..spotify.player.esperanto.proto.AdBreakContextH\x01R\x0eadBreakContext\x88\x01\x01\x12P\n" +
	"\vsleep_timer\x18\x1f \x01(\v2*.spotify.player.esperanto.proto.SleepTimerH\x02R\n" +
	"sleepTimer\x88\x01\x01\x1a>\n" +
	"\x14ContextMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a;\n" +
	"\x11PageMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\x06Format\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDEFAULT\x10\x01\x12\n" +
	"\n" +
	"\x06PARROT\x10\x02B\t\n" +
	"\a_formatB\x13\n" +
	"\x11_ad_break_contextB\x0e\n" +
	"\f_sleep_timerBp\n" +
	"\"com.spotify.player.esperanto.protoZDgithub.com/pyrorhythm/libspot/api/spotify/player/esperanto;esperanto\xa2\x02\x03ESPb\x06proto3"

var (
	file_es_context_player_state_proto_rawDescOnce sync.Once
	file_es_context_player_state_proto_rawDescData []byte
)

func file_es_context_player_state_proto_rawDescGZIP() []byte {
	file_es_context_player_state_proto_rawDescOnce.Do(func() {
		file_es_context_player_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es_context_player_state_proto_rawDesc), len(file_es_context_player_state_proto_rawDesc)))
	})
	return file_es_context_player_state_proto_rawDescData
}

var file_es_context_player_state_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_es_context_player_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_es_context_player_state_proto_goTypes = []any{
	(PlaybackQuality_BitrateLevel)(0),               // 0: spotify.player.esperanto.proto.PlaybackQuality.BitrateLevel
	(PlaybackQuality_BitrateStrategy)(0),            // 1: spotify.player.esperanto.proto.PlaybackQuality.BitrateStrategy
	(PlaybackQuality_HiFiStatus)(0),                 // 2: spotify.player.esperanto.proto.PlaybackQuality.HiFiStatus
	(ContextPlayerState_Format)(0),                  // 3: spotify.player.esperanto.proto.ContextPlayerState.Format
	(*ContextIndex)(nil),                            // 4: spotify.player.esperanto.proto.ContextIndex
	(*PlaybackQuality)(nil),                         // 5: spotify.player.esperanto.proto.PlaybackQuality
	(*ContextPlayerState)(nil),                      // 6: spotify.player.esperanto.proto.ContextPlayerState
	(*ContextPlayerState_ContextMetadataEntry)(nil), // 7: spotify.player.esperanto.proto.ContextPlayerState.ContextMetadataEntry
	(*ContextPlayerState_PageMetadataEntry)(nil),    // 8: spotify.player.esperanto.proto.ContextPlayerState.PageMetadataEntry
	(*Restrictions)(nil),                            // 9: spotify.player.esperanto.proto.Restrictions
	(*PlayOrigin)(nil),                              // 10: spotify.player.esperanto.proto.PlayOrigin
	(*ProvidedTrack)(nil),                           // 11: spotify.player.esperanto.proto.ProvidedTrack
	(*OptionalDouble)(nil),                          // 12: spotify.player.esperanto.proto.OptionalDouble
	(*OptionalInt64)(nil),                           // 13: spotify.player.esperanto.proto.OptionalInt64
	(*ContextPlayerOptions)(nil),                    // 14: spotify.player.esperanto.proto.ContextPlayerOptions
	(PreparePlayOptions_AudioStream)(0),             // 15: spotify.player.esperanto.proto.PreparePlayOptions.AudioStream
	(*AdBreakContext)(nil),                          // 16: spotify.player.esperanto.proto.AdBreakContext
	(*SleepTimer)(nil),                              // 17: spotify.player.esperanto.proto.SleepTimer
}
var file_es_context_player_state_proto_depIdxs = []int32{
	0,  // 0: spotify.player.esperanto.proto.PlaybackQuality.bitrate_level:type_name -> spotify.player.esperanto.proto.PlaybackQuality.BitrateLevel
	1,  // 1: spotify.player.esperanto.proto.PlaybackQuality.strategy:type_name -> spotify.player.esperanto.proto.PlaybackQuality.BitrateStrategy
	0,  // 2: spotify.player.esperanto.proto.PlaybackQuality.target_bitrate_level:type_name -> spotify.player.esperanto.proto.PlaybackQuality.BitrateLevel
	2,  // 3: spotify.player.esperanto.proto.PlaybackQuality.hifi_status:type_name -> spotify.player.esperanto.proto.PlaybackQuality.HiFiStatus
	9,  // 4: spotify.player.esperanto.proto.ContextPlayerState.context_restrictions:type_name -> spotify.player.esperanto.proto.Restrictions
	10, // 5: spotify.player.esperanto.proto.ContextPlayerState.play_origin:type_name -> spotify.player.esperanto.proto.PlayOrigin
	4,  // 6: spotify.player.esperanto.proto.ContextPlayerState.index:type_name -> spotify.player.esperanto.proto.ContextIndex
	11, // 7: spotify.player.esperanto.proto.ContextPlayerState.track:type_name -> spotify.player.esperanto.proto.ProvidedTrack
	5,  // 8: spotify.player.esperanto.proto.ContextPlayerState.playback_quality:type_name -> spotify.player.esperanto.proto.PlaybackQuality
	12, // 9: spotify.player.esperanto.proto.ContextPlayerState.playback_speed:type_name -> spotify.player.esperanto.proto.OptionalDouble
	13, // 10: spotify.player.esperanto.proto.ContextPlayerState.position_as_of_timestamp:type_name -> spotify.player.esperanto.proto.OptionalInt64
	13, // 11: spotify.player.esperanto.proto.ContextPlayerState.duration:type_name -> spotify.player.esperanto.proto.OptionalInt64
	14, // 12: spotify.player.esperanto.proto.ContextPlayerState.options:type_name -> spotify.player.esperanto.proto.ContextPlayerOptions
	9,  // 13: spotify.player.esperanto.proto.ContextPlayerState.restrictions:type_name -> spotify.player.esperanto.proto.Restrictions
	11, // 14: spotify.player.esperanto.proto.ContextPlayerState.prev_tracks:type_name -> spotify.player.esperanto.proto.ProvidedTrack
	11, // 15: spotify.player.esperanto.proto.ContextPlayerState.next_tracks:type_name -> spotify.player.esperanto.proto.ProvidedTrack
	7,  // 16: spotify.player.esperanto.proto.ContextPlayerState.context_metadata:type_name -> spotify.player.esperanto.proto.ContextPlayerState.ContextMetadataEntry
	8,  // 17: spotify.player.esperanto.proto.ContextPlayerState.page_metadata:type_name -> spotify.player.esperanto.proto.ContextPlayerState.PageMetadataEntry
	15, // 18: spotify.player.esperanto.proto.ContextPlayerState.audio_stream:type_name -> spotify.player.esperanto.proto.PreparePlayOptions.AudioStream
	3,  // 19: spotify.player.esperanto.proto.ContextPlayerState.format:type_name -> spotify.player.esperanto.proto.ContextPlayerState.Format
	16, // 20: spotify.player.esperanto.proto.ContextPlayerState.ad_break_context:type_name -> spotify.player.esperanto.proto.AdBreakContext
	17, // 21: spotify.player.esperanto.proto.ContextPlayerState.sleep_timer:type_name -> spotify.player.esperanto.proto.SleepTimer
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_es_context_player_state_proto_init() }
func file_es_context_player_state_proto_init() {
	if File_es_context_player_state_proto != nil {
		return
	}
	file_es_restrictions_proto_init()
	file_es_play_origin_proto_init()
	file_es_optional_proto_init()
	file_es_provided_track_proto_init()
	file_es_context_player_options_proto_init()
	file_es_prepare_play_options_proto_init()
	file_es_ad_break_context_proto_init()
	file_es_sleep_timer_proto_init()
	file_es_context_player_state_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es_context_player_state_proto_rawDesc), len(file_es_context_player_state_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es_context_player_state_proto_goTypes,
		DependencyIndexes: file_es_context_player_state_proto_depIdxs,
		EnumInfos:         file_es_context_player_state_proto_enumTypes,
		MessageInfos:      file_es_context_player_state_proto_msgTypes,
	}.Build()
	File_es_context_player_state_proto = out.File
	file_es_context_player_state_proto_goTypes = nil
	file_es_context_player_state_proto_depIdxs = nil
}
