// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: es_skip_prev.proto

package esperanto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkipPrevRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *CommandOptions        `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	AllowSeeking  bool                   `protobuf:"varint,2,opt,name=allow_seeking,json=allowSeeking,proto3" json:"allow_seeking,omitempty"`
	LoggingParams *LoggingParams         `protobuf:"bytes,3,opt,name=logging_params,json=loggingParams,proto3" json:"logging_params,omitempty"`
	Track         *ContextTrack          `protobuf:"bytes,4,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipPrevRequest) Reset() {
	*x = SkipPrevRequest{}
	mi := &file_es_skip_prev_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipPrevRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipPrevRequest) ProtoMessage() {}

func (x *SkipPrevRequest) ProtoReflect() protoreflect.Message {
	mi := &file_es_skip_prev_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipPrevRequest.ProtoReflect.Descriptor instead.
func (*SkipPrevRequest) Descriptor() ([]byte, []int) {
	return file_es_skip_prev_proto_rawDescGZIP(), []int{0}
}

func (x *SkipPrevRequest) GetOptions() *CommandOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SkipPrevRequest) GetAllowSeeking() bool {
	if x != nil {
		return x.AllowSeeking
	}
	return false
}

func (x *SkipPrevRequest) GetLoggingParams() *LoggingParams {
	if x != nil {
		return x.LoggingParams
	}
	return nil
}

func (x *SkipPrevRequest) GetTrack() *ContextTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

var File_es_skip_prev_proto protoreflect.FileDescriptor

const file_es_skip_prev_proto_rawDesc = "" +
	"\n" +
	"\x12es_skip_prev.proto\x12\x1espotify.player.esperanto.proto\x1a\x18es_command_options.proto\x1a\x17es_logging_params.proto\x1a\x16es_context_track.proto\"\x9a\x02\n" +
	"\x0fSkipPrevRequest\x12H\n" +
	"\aoptions\x18\x01 \x01(\v2..spotify.player.esperanto.proto.CommandOptionsR\aoptions\x12#\n" +
	"\rallow_seeking\x18\x02 \x01(\bR\fallowSeeking\x12T\n" +
	"\x0elogging_params\x18\x03 \x01(\v2-.spotify.player.esperanto.proto.LoggingParamsR\rloggingParams\x12B\n" +
	"\x05track\x18\x04 \x01(\v2,.spotify.player.esperanto.proto.ContextTrackR\x05trackBp\n" +
	"\"com.spotify.player.esperanto.protoZDgithub.com/pyrorhythm/libspot/api/spotify/player/esperanto;esperanto\xa2\x02\x03ESPb\x06proto3"

var (
	file_es_skip_prev_proto_rawDescOnce sync.Once
	file_es_skip_prev_proto_rawDescData []byte
)

func file_es_skip_prev_proto_rawDescGZIP() []byte {
	file_es_skip_prev_proto_rawDescOnce.Do(func() {
		file_es_skip_prev_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_es_skip_prev_proto_rawDesc), len(file_es_skip_prev_proto_rawDesc)))
	})
	return file_es_skip_prev_proto_rawDescData
}

var file_es_skip_prev_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_es_skip_prev_proto_goTypes = []any{
	(*SkipPrevRequest)(nil), // 0: spotify.player.esperanto.proto.SkipPrevRequest
	(*CommandOptions)(nil),  // 1: spotify.player.esperanto.proto.CommandOptions
	(*LoggingParams)(nil),   // 2: spotify.player.esperanto.proto.LoggingParams
	(*ContextTrack)(nil),    // 3: spotify.player.esperanto.proto.ContextTrack
}
var file_es_skip_prev_proto_depIdxs = []int32{
	1, // 0: spotify.player.esperanto.proto.SkipPrevRequest.options:type_name -> spotify.player.esperanto.proto.CommandOptions
	2, // 1: spotify.player.esperanto.proto.SkipPrevRequest.logging_params:type_name -> spotify.player.esperanto.proto.LoggingParams
	3, // 2: spotify.player.esperanto.proto.SkipPrevRequest.track:type_name -> spotify.player.esperanto.proto.ContextTrack
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_es_skip_prev_proto_init() }
func file_es_skip_prev_proto_init() {
	if File_es_skip_prev_proto != nil {
		return
	}
	file_es_command_options_proto_init()
	file_es_logging_params_proto_init()
	file_es_context_track_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_es_skip_prev_proto_rawDesc), len(file_es_skip_prev_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_es_skip_prev_proto_goTypes,
		DependencyIndexes: file_es_skip_prev_proto_depIdxs,
		MessageInfos:      file_es_skip_prev_proto_msgTypes,
	}.Build()
	File_es_skip_prev_proto = out.File
	file_es_skip_prev_proto_goTypes = nil
	file_es_skip_prev_proto_depIdxs = nil
}
