// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: playlist_folder_state.proto

package cosmos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FolderMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                  *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NumFolders            *uint32                `protobuf:"varint,3,opt,name=num_folders,json=numFolders" json:"num_folders,omitempty"`
	NumPlaylists          *uint32                `protobuf:"varint,4,opt,name=num_playlists,json=numPlaylists" json:"num_playlists,omitempty"`
	NumRecursiveFolders   *uint32                `protobuf:"varint,5,opt,name=num_recursive_folders,json=numRecursiveFolders" json:"num_recursive_folders,omitempty"`
	NumRecursivePlaylists *uint32                `protobuf:"varint,6,opt,name=num_recursive_playlists,json=numRecursivePlaylists" json:"num_recursive_playlists,omitempty"`
	Link                  *string                `protobuf:"bytes,7,opt,name=link" json:"link,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FolderMetadata) Reset() {
	*x = FolderMetadata{}
	mi := &file_playlist_folder_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderMetadata) ProtoMessage() {}

func (x *FolderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_playlist_folder_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderMetadata.ProtoReflect.Descriptor instead.
func (*FolderMetadata) Descriptor() ([]byte, []int) {
	return file_playlist_folder_state_proto_rawDescGZIP(), []int{0}
}

func (x *FolderMetadata) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *FolderMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FolderMetadata) GetNumFolders() uint32 {
	if x != nil && x.NumFolders != nil {
		return *x.NumFolders
	}
	return 0
}

func (x *FolderMetadata) GetNumPlaylists() uint32 {
	if x != nil && x.NumPlaylists != nil {
		return *x.NumPlaylists
	}
	return 0
}

func (x *FolderMetadata) GetNumRecursiveFolders() uint32 {
	if x != nil && x.NumRecursiveFolders != nil {
		return *x.NumRecursiveFolders
	}
	return 0
}

func (x *FolderMetadata) GetNumRecursivePlaylists() uint32 {
	if x != nil && x.NumRecursivePlaylists != nil {
		return *x.NumRecursivePlaylists
	}
	return 0
}

func (x *FolderMetadata) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

var File_playlist_folder_state_proto protoreflect.FileDescriptor

const file_playlist_folder_state_proto_rawDesc = "" +
	"\n" +
	"\x1bplaylist_folder_state.proto\x12\x1dspotify.playlist.cosmos.proto\"\xfa\x01\n" +
	"\x0eFolderMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vnum_folders\x18\x03 \x01(\rR\n" +
	"numFolders\x12#\n" +
	"\rnum_playlists\x18\x04 \x01(\rR\fnumPlaylists\x122\n" +
	"\x15num_recursive_folders\x18\x05 \x01(\rR\x13numRecursiveFolders\x126\n" +
	"\x17num_recursive_playlists\x18\x06 \x01(\rR\x15numRecursivePlaylists\x12\x12\n" +
	"\x04link\x18\a \x01(\tR\x04linkB`\n" +
	"\x1acom.spotify.playlist.protoP\x01Z@github.com/pyrorhythm/libspot/api/spotify/playlist/cosmos;cosmos"

var (
	file_playlist_folder_state_proto_rawDescOnce sync.Once
	file_playlist_folder_state_proto_rawDescData []byte
)

func file_playlist_folder_state_proto_rawDescGZIP() []byte {
	file_playlist_folder_state_proto_rawDescOnce.Do(func() {
		file_playlist_folder_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playlist_folder_state_proto_rawDesc), len(file_playlist_folder_state_proto_rawDesc)))
	})
	return file_playlist_folder_state_proto_rawDescData
}

var file_playlist_folder_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_playlist_folder_state_proto_goTypes = []any{
	(*FolderMetadata)(nil), // 0: spotify.playlist.cosmos.proto.FolderMetadata
}
var file_playlist_folder_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_playlist_folder_state_proto_init() }
func file_playlist_folder_state_proto_init() {
	if File_playlist_folder_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playlist_folder_state_proto_rawDesc), len(file_playlist_folder_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playlist_folder_state_proto_goTypes,
		DependencyIndexes: file_playlist_folder_state_proto_depIdxs,
		MessageInfos:      file_playlist_folder_state_proto_msgTypes,
	}.Build()
	File_playlist_folder_state_proto = out.File
	file_playlist_folder_state_proto_goTypes = nil
	file_playlist_folder_state_proto_depIdxs = nil
}
