// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cuepoints.proto

package automix

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Origin int32

const (
	Origin_HUMAN Origin = 0
	Origin_ML    Origin = 1
)

// Enum value maps for Origin.
var (
	Origin_name = map[int32]string{
		0: "HUMAN",
		1: "ML",
	}
	Origin_value = map[string]int32{
		"HUMAN": 0,
		"ML":    1,
	}
)

func (x Origin) Enum() *Origin {
	p := new(Origin)
	*p = x
	return p
}

func (x Origin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Origin) Descriptor() protoreflect.EnumDescriptor {
	return file_cuepoints_proto_enumTypes[0].Descriptor()
}

func (Origin) Type() protoreflect.EnumType {
	return &file_cuepoints_proto_enumTypes[0]
}

func (x Origin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Origin.Descriptor instead.
func (Origin) EnumDescriptor() ([]byte, []int) {
	return file_cuepoints_proto_rawDescGZIP(), []int{0}
}

type Cuepoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionMs    int64                  `protobuf:"varint,1,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	TempoBpm      float32                `protobuf:"fixed32,2,opt,name=tempo_bpm,json=tempoBpm,proto3" json:"tempo_bpm,omitempty"`
	Origin        Origin                 `protobuf:"varint,3,opt,name=origin,proto3,enum=spotify.automix.proto.Origin" json:"origin,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cuepoint) Reset() {
	*x = Cuepoint{}
	mi := &file_cuepoints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cuepoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuepoint) ProtoMessage() {}

func (x *Cuepoint) ProtoReflect() protoreflect.Message {
	mi := &file_cuepoints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cuepoint.ProtoReflect.Descriptor instead.
func (*Cuepoint) Descriptor() ([]byte, []int) {
	return file_cuepoints_proto_rawDescGZIP(), []int{0}
}

func (x *Cuepoint) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *Cuepoint) GetTempoBpm() float32 {
	if x != nil {
		return x.TempoBpm
	}
	return 0
}

func (x *Cuepoint) GetOrigin() Origin {
	if x != nil {
		return x.Origin
	}
	return Origin_HUMAN
}

func (x *Cuepoint) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Cuepoints struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BestFadeInCuepoint  *Cuepoint              `protobuf:"bytes,1,opt,name=best_fade_in_cuepoint,json=bestFadeInCuepoint,proto3" json:"best_fade_in_cuepoint,omitempty"`
	BestFadeOutCuepoint *Cuepoint              `protobuf:"bytes,2,opt,name=best_fade_out_cuepoint,json=bestFadeOutCuepoint,proto3" json:"best_fade_out_cuepoint,omitempty"`
	FadeInCuepoints     []*Cuepoint            `protobuf:"bytes,3,rep,name=fade_in_cuepoints,json=fadeInCuepoints,proto3" json:"fade_in_cuepoints,omitempty"`
	FadeOutCuepoints    []*Cuepoint            `protobuf:"bytes,4,rep,name=fade_out_cuepoints,json=fadeOutCuepoints,proto3" json:"fade_out_cuepoints,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Cuepoints) Reset() {
	*x = Cuepoints{}
	mi := &file_cuepoints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cuepoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuepoints) ProtoMessage() {}

func (x *Cuepoints) ProtoReflect() protoreflect.Message {
	mi := &file_cuepoints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cuepoints.ProtoReflect.Descriptor instead.
func (*Cuepoints) Descriptor() ([]byte, []int) {
	return file_cuepoints_proto_rawDescGZIP(), []int{1}
}

func (x *Cuepoints) GetBestFadeInCuepoint() *Cuepoint {
	if x != nil {
		return x.BestFadeInCuepoint
	}
	return nil
}

func (x *Cuepoints) GetBestFadeOutCuepoint() *Cuepoint {
	if x != nil {
		return x.BestFadeOutCuepoint
	}
	return nil
}

func (x *Cuepoints) GetFadeInCuepoints() []*Cuepoint {
	if x != nil {
		return x.FadeInCuepoints
	}
	return nil
}

func (x *Cuepoints) GetFadeOutCuepoints() []*Cuepoint {
	if x != nil {
		return x.FadeOutCuepoints
	}
	return nil
}

var File_cuepoints_proto protoreflect.FileDescriptor

const file_cuepoints_proto_rawDesc = "" +
	"\n" +
	"\x0fcuepoints.proto\x12\x15spotify.automix.proto\"\x9f\x01\n" +
	"\bCuepoint\x12\x1f\n" +
	"\vposition_ms\x18\x01 \x01(\x03R\n" +
	"positionMs\x12\x1b\n" +
	"\ttempo_bpm\x18\x02 \x01(\x02R\btempoBpm\x125\n" +
	"\x06origin\x18\x03 \x01(\x0e2\x1d.spotify.automix.proto.OriginR\x06origin\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"\xd1\x02\n" +
	"\tCuepoints\x12R\n" +
	"\x15best_fade_in_cuepoint\x18\x01 \x01(\v2\x1f.spotify.automix.proto.CuepointR\x12bestFadeInCuepoint\x12T\n" +
	"\x16best_fade_out_cuepoint\x18\x02 \x01(\v2\x1f.spotify.automix.proto.CuepointR\x13bestFadeOutCuepoint\x12K\n" +
	"\x11fade_in_cuepoints\x18\x03 \x03(\v2\x1f.spotify.automix.proto.CuepointR\x0ffadeInCuepoints\x12M\n" +
	"\x12fade_out_cuepoints\x18\x04 \x03(\v2\x1f.spotify.automix.proto.CuepointR\x10fadeOutCuepoints*\x1b\n" +
	"\x06Origin\x12\t\n" +
	"\x05HUMAN\x10\x00\x12\x06\n" +
	"\x02ML\x10\x01BV\n" +
	"\x19com.spotify.automix.protoZ9github.com/pyrorhythm/libspot/api/spotify/automix;automixb\x06proto3"

var (
	file_cuepoints_proto_rawDescOnce sync.Once
	file_cuepoints_proto_rawDescData []byte
)

func file_cuepoints_proto_rawDescGZIP() []byte {
	file_cuepoints_proto_rawDescOnce.Do(func() {
		file_cuepoints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cuepoints_proto_rawDesc), len(file_cuepoints_proto_rawDesc)))
	})
	return file_cuepoints_proto_rawDescData
}

var file_cuepoints_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cuepoints_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cuepoints_proto_goTypes = []any{
	(Origin)(0),       // 0: spotify.automix.proto.Origin
	(*Cuepoint)(nil),  // 1: spotify.automix.proto.Cuepoint
	(*Cuepoints)(nil), // 2: spotify.automix.proto.Cuepoints
}
var file_cuepoints_proto_depIdxs = []int32{
	0, // 0: spotify.automix.proto.Cuepoint.origin:type_name -> spotify.automix.proto.Origin
	1, // 1: spotify.automix.proto.Cuepoints.best_fade_in_cuepoint:type_name -> spotify.automix.proto.Cuepoint
	1, // 2: spotify.automix.proto.Cuepoints.best_fade_out_cuepoint:type_name -> spotify.automix.proto.Cuepoint
	1, // 3: spotify.automix.proto.Cuepoints.fade_in_cuepoints:type_name -> spotify.automix.proto.Cuepoint
	1, // 4: spotify.automix.proto.Cuepoints.fade_out_cuepoints:type_name -> spotify.automix.proto.Cuepoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cuepoints_proto_init() }
func file_cuepoints_proto_init() {
	if File_cuepoints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cuepoints_proto_rawDesc), len(file_cuepoints_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cuepoints_proto_goTypes,
		DependencyIndexes: file_cuepoints_proto_depIdxs,
		EnumInfos:         file_cuepoints_proto_enumTypes,
		MessageInfos:      file_cuepoints_proto_msgTypes,
	}.Build()
	File_cuepoints_proto = out.File
	file_cuepoints_proto_goTypes = nil
	file_cuepoints_proto_depIdxs = nil
}
