// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mix_vocal_activity.proto

package mixvocalactivity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VocalActivity struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	SourceSampleRateHz         float32                `protobuf:"fixed32,1,opt,name=source_sample_rate_hz,json=sourceSampleRateHz,proto3" json:"source_sample_rate_hz,omitempty"`
	SmoothingWindowSize        int32                  `protobuf:"varint,2,opt,name=smoothing_window_size,json=smoothingWindowSize,proto3" json:"smoothing_window_size,omitempty"`
	FirstWindowSampleStart     int32                  `protobuf:"varint,3,opt,name=first_window_sample_start,json=firstWindowSampleStart,proto3" json:"first_window_sample_start,omitempty"`
	SamplesBetweenWindows      int32                  `protobuf:"varint,4,opt,name=samples_between_windows,json=samplesBetweenWindows,proto3" json:"samples_between_windows,omitempty"`
	VocalActivityProbabilities []int32                `protobuf:"varint,5,rep,packed,name=vocal_activity_probabilities,json=vocalActivityProbabilities,proto3" json:"vocal_activity_probabilities,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VocalActivity) Reset() {
	*x = VocalActivity{}
	mi := &file_mix_vocal_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VocalActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VocalActivity) ProtoMessage() {}

func (x *VocalActivity) ProtoReflect() protoreflect.Message {
	mi := &file_mix_vocal_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VocalActivity.ProtoReflect.Descriptor instead.
func (*VocalActivity) Descriptor() ([]byte, []int) {
	return file_mix_vocal_activity_proto_rawDescGZIP(), []int{0}
}

func (x *VocalActivity) GetSourceSampleRateHz() float32 {
	if x != nil {
		return x.SourceSampleRateHz
	}
	return 0
}

func (x *VocalActivity) GetSmoothingWindowSize() int32 {
	if x != nil {
		return x.SmoothingWindowSize
	}
	return 0
}

func (x *VocalActivity) GetFirstWindowSampleStart() int32 {
	if x != nil {
		return x.FirstWindowSampleStart
	}
	return 0
}

func (x *VocalActivity) GetSamplesBetweenWindows() int32 {
	if x != nil {
		return x.SamplesBetweenWindows
	}
	return 0
}

func (x *VocalActivity) GetVocalActivityProbabilities() []int32 {
	if x != nil {
		return x.VocalActivityProbabilities
	}
	return nil
}

var File_mix_vocal_activity_proto protoreflect.FileDescriptor

const file_mix_vocal_activity_proto_rawDesc = "" +
	"\n" +
	"\x18mix_vocal_activity.proto\x122spotify.playlistmixing.extensions.mixvocalactivity\"\xab\x02\n" +
	"\rVocalActivity\x121\n" +
	"\x15source_sample_rate_hz\x18\x01 \x01(\x02R\x12sourceSampleRateHz\x122\n" +
	"\x15smoothing_window_size\x18\x02 \x01(\x05R\x13smoothingWindowSize\x129\n" +
	"\x19first_window_sample_start\x18\x03 \x01(\x05R\x16firstWindowSampleStart\x126\n" +
	"\x17samples_between_windows\x18\x04 \x01(\x05R\x15samplesBetweenWindows\x12@\n" +
	"\x1cvocal_activity_probabilities\x18\x05 \x03(\x05R\x1avocalActivityProbabilitiesB\xbc\x01\n" +
	"<com.spotify.playlistmixing.extensions.mixvocalactivity.protoB\x15MixVocalActivityProtoZegithub.com/pyrorhythm/libspot/api/spotify/playlistmixing/extensions/mixvocalactivity;mixvocalactivityb\x06proto3"

var (
	file_mix_vocal_activity_proto_rawDescOnce sync.Once
	file_mix_vocal_activity_proto_rawDescData []byte
)

func file_mix_vocal_activity_proto_rawDescGZIP() []byte {
	file_mix_vocal_activity_proto_rawDescOnce.Do(func() {
		file_mix_vocal_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mix_vocal_activity_proto_rawDesc), len(file_mix_vocal_activity_proto_rawDesc)))
	})
	return file_mix_vocal_activity_proto_rawDescData
}

var file_mix_vocal_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mix_vocal_activity_proto_goTypes = []any{
	(*VocalActivity)(nil), // 0: spotify.playlistmixing.extensions.mixvocalactivity.VocalActivity
}
var file_mix_vocal_activity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mix_vocal_activity_proto_init() }
func file_mix_vocal_activity_proto_init() {
	if File_mix_vocal_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mix_vocal_activity_proto_rawDesc), len(file_mix_vocal_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mix_vocal_activity_proto_goTypes,
		DependencyIndexes: file_mix_vocal_activity_proto_depIdxs,
		MessageInfos:      file_mix_vocal_activity_proto_msgTypes,
	}.Build()
	File_mix_vocal_activity_proto = out.File
	file_mix_vocal_activity_proto_goTypes = nil
	file_mix_vocal_activity_proto_depIdxs = nil
}
