// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audiobooks_common_capping.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudiobooksCommonCapping struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShouldBlockResume *bool                  `protobuf:"varint,3,opt,name=should_block_resume,json=shouldBlockResume" json:"should_block_resume,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AudiobooksCommonCapping) Reset() {
	*x = AudiobooksCommonCapping{}
	mi := &file_audiobooks_common_capping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiobooksCommonCapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiobooksCommonCapping) ProtoMessage() {}

func (x *AudiobooksCommonCapping) ProtoReflect() protoreflect.Message {
	mi := &file_audiobooks_common_capping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiobooksCommonCapping.ProtoReflect.Descriptor instead.
func (*AudiobooksCommonCapping) Descriptor() ([]byte, []int) {
	return file_audiobooks_common_capping_proto_rawDescGZIP(), []int{0}
}

func (x *AudiobooksCommonCapping) GetShouldBlockResume() bool {
	if x != nil && x.ShouldBlockResume != nil {
		return *x.ShouldBlockResume
	}
	return false
}

var File_audiobooks_common_capping_proto protoreflect.FileDescriptor

const file_audiobooks_common_capping_proto_rawDesc = "" +
	"\n" +
	"\x1faudiobooks_common_capping.proto\x12\x14spotify.player.proto\"I\n" +
	"\x17AudiobooksCommonCapping\x12.\n" +
	"\x13should_block_resume\x18\x03 \x01(\bR\x11shouldBlockResumeB9Z7github.com/pyrorhythm/libspot/api/spotify/player;player"

var (
	file_audiobooks_common_capping_proto_rawDescOnce sync.Once
	file_audiobooks_common_capping_proto_rawDescData []byte
)

func file_audiobooks_common_capping_proto_rawDescGZIP() []byte {
	file_audiobooks_common_capping_proto_rawDescOnce.Do(func() {
		file_audiobooks_common_capping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audiobooks_common_capping_proto_rawDesc), len(file_audiobooks_common_capping_proto_rawDesc)))
	})
	return file_audiobooks_common_capping_proto_rawDescData
}

var file_audiobooks_common_capping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_audiobooks_common_capping_proto_goTypes = []any{
	(*AudiobooksCommonCapping)(nil), // 0: spotify.player.proto.AudiobooksCommonCapping
}
var file_audiobooks_common_capping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audiobooks_common_capping_proto_init() }
func file_audiobooks_common_capping_proto_init() {
	if File_audiobooks_common_capping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audiobooks_common_capping_proto_rawDesc), len(file_audiobooks_common_capping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audiobooks_common_capping_proto_goTypes,
		DependencyIndexes: file_audiobooks_common_capping_proto_depIdxs,
		MessageInfos:      file_audiobooks_common_capping_proto_msgTypes,
	}.Build()
	File_audiobooks_common_capping_proto = out.File
	file_audiobooks_common_capping_proto_goTypes = nil
	file_audiobooks_common_capping_proto_depIdxs = nil
}
