// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: context_page.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextPage struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	PageUrl       *string                      `protobuf:"bytes,1,opt,name=page_url,json=pageUrl" json:"page_url,omitempty"`
	NextPageUrl   *string                      `protobuf:"bytes,2,opt,name=next_page_url,json=nextPageUrl" json:"next_page_url,omitempty"`
	Metadata      []*ContextPage_MetadataEntry `protobuf:"bytes,3,rep,name=metadata" json:"metadata,omitempty"`
	Tracks        []*ContextTrack              `protobuf:"bytes,4,rep,name=tracks" json:"tracks,omitempty"`
	Loading       *bool                        `protobuf:"varint,5,opt,name=loading" json:"loading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPage) Reset() {
	*x = ContextPage{}
	mi := &file_context_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPage) ProtoMessage() {}

func (x *ContextPage) ProtoReflect() protoreflect.Message {
	mi := &file_context_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPage.ProtoReflect.Descriptor instead.
func (*ContextPage) Descriptor() ([]byte, []int) {
	return file_context_page_proto_rawDescGZIP(), []int{0}
}

func (x *ContextPage) GetPageUrl() string {
	if x != nil && x.PageUrl != nil {
		return *x.PageUrl
	}
	return ""
}

func (x *ContextPage) GetNextPageUrl() string {
	if x != nil && x.NextPageUrl != nil {
		return *x.NextPageUrl
	}
	return ""
}

func (x *ContextPage) GetMetadata() []*ContextPage_MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ContextPage) GetTracks() []*ContextTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *ContextPage) GetLoading() bool {
	if x != nil && x.Loading != nil {
		return *x.Loading
	}
	return false
}

type ContextPage_MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextPage_MetadataEntry) Reset() {
	*x = ContextPage_MetadataEntry{}
	mi := &file_context_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPage_MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPage_MetadataEntry) ProtoMessage() {}

func (x *ContextPage_MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_context_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPage_MetadataEntry.ProtoReflect.Descriptor instead.
func (*ContextPage_MetadataEntry) Descriptor() ([]byte, []int) {
	return file_context_page_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ContextPage_MetadataEntry) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ContextPage_MetadataEntry) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_context_page_proto protoreflect.FileDescriptor

const file_context_page_proto_rawDesc = "" +
	"\n" +
	"\x12context_page.proto\x12\x14spotify.player.proto\x1a\x13context_track.proto\"\xa8\x02\n" +
	"\vContextPage\x12\x19\n" +
	"\bpage_url\x18\x01 \x01(\tR\apageUrl\x12\"\n" +
	"\rnext_page_url\x18\x02 \x01(\tR\vnextPageUrl\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.spotify.player.proto.ContextPage.MetadataEntryR\bmetadata\x12:\n" +
	"\x06tracks\x18\x04 \x03(\v2\".spotify.player.proto.ContextTrackR\x06tracks\x12\x18\n" +
	"\aloading\x18\x05 \x01(\bR\aloading\x1a7\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB9Z7github.com/pyrorhythm/libspot/api/spotify/player;player"

var (
	file_context_page_proto_rawDescOnce sync.Once
	file_context_page_proto_rawDescData []byte
)

func file_context_page_proto_rawDescGZIP() []byte {
	file_context_page_proto_rawDescOnce.Do(func() {
		file_context_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_page_proto_rawDesc), len(file_context_page_proto_rawDesc)))
	})
	return file_context_page_proto_rawDescData
}

var file_context_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_page_proto_goTypes = []any{
	(*ContextPage)(nil),               // 0: spotify.player.proto.ContextPage
	(*ContextPage_MetadataEntry)(nil), // 1: spotify.player.proto.ContextPage.MetadataEntry
	(*ContextTrack)(nil),              // 2: spotify.player.proto.ContextTrack
}
var file_context_page_proto_depIdxs = []int32{
	1, // 0: spotify.player.proto.ContextPage.metadata:type_name -> spotify.player.proto.ContextPage.MetadataEntry
	2, // 1: spotify.player.proto.ContextPage.tracks:type_name -> spotify.player.proto.ContextTrack
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_context_page_proto_init() }
func file_context_page_proto_init() {
	if File_context_page_proto != nil {
		return
	}
	file_context_track_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_page_proto_rawDesc), len(file_context_page_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_context_page_proto_goTypes,
		DependencyIndexes: file_context_page_proto_depIdxs,
		MessageInfos:      file_context_page_proto_msgTypes,
	}.Build()
	File_context_page_proto = out.File
	file_context_page_proto_goTypes = nil
	file_context_page_proto_depIdxs = nil
}
