// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: seek_to_position.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeekToPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint64                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Revision      *uint32                `protobuf:"varint,2,opt,name=revision" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeekToPosition) Reset() {
	*x = SeekToPosition{}
	mi := &file_seek_to_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeekToPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekToPosition) ProtoMessage() {}

func (x *SeekToPosition) ProtoReflect() protoreflect.Message {
	mi := &file_seek_to_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekToPosition.ProtoReflect.Descriptor instead.
func (*SeekToPosition) Descriptor() ([]byte, []int) {
	return file_seek_to_position_proto_rawDescGZIP(), []int{0}
}

func (x *SeekToPosition) GetValue() uint64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SeekToPosition) GetRevision() uint32 {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return 0
}

var File_seek_to_position_proto protoreflect.FileDescriptor

const file_seek_to_position_proto_rawDesc = "" +
	"\n" +
	"\x16seek_to_position.proto\x12\x14spotify.player.proto\"B\n" +
	"\x0eSeekToPosition\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\rR\brevisionB9Z7github.com/pyrorhythm/libspot/api/spotify/player;player"

var (
	file_seek_to_position_proto_rawDescOnce sync.Once
	file_seek_to_position_proto_rawDescData []byte
)

func file_seek_to_position_proto_rawDescGZIP() []byte {
	file_seek_to_position_proto_rawDescOnce.Do(func() {
		file_seek_to_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seek_to_position_proto_rawDesc), len(file_seek_to_position_proto_rawDesc)))
	})
	return file_seek_to_position_proto_rawDescData
}

var file_seek_to_position_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seek_to_position_proto_goTypes = []any{
	(*SeekToPosition)(nil), // 0: spotify.player.proto.SeekToPosition
}
var file_seek_to_position_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seek_to_position_proto_init() }
func file_seek_to_position_proto_init() {
	if File_seek_to_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seek_to_position_proto_rawDesc), len(file_seek_to_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seek_to_position_proto_goTypes,
		DependencyIndexes: file_seek_to_position_proto_depIdxs,
		MessageInfos:      file_seek_to_position_proto_msgTypes,
	}.Build()
	File_seek_to_position_proto = out.File
	file_seek_to_position_proto_goTypes = nil
	file_seek_to_position_proto_depIdxs = nil
}
