// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protobuf_delta.proto

package spotifybuf_deltas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta_Type int32

const (
	Delta_DELETE Delta_Type = 0
	Delta_INSERT Delta_Type = 1
)

// Enum value maps for Delta_Type.
var (
	Delta_Type_name = map[int32]string{
		0: "DELETE",
		1: "INSERT",
	}
	Delta_Type_value = map[string]int32{
		"DELETE": 0,
		"INSERT": 1,
	}
)

func (x Delta_Type) Enum() *Delta_Type {
	p := new(Delta_Type)
	*p = x
	return p
}

func (x Delta_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Delta_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_delta_proto_enumTypes[0].Descriptor()
}

func (Delta_Type) Type() protoreflect.EnumType {
	return &file_protobuf_delta_proto_enumTypes[0]
}

func (x Delta_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Delta_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Delta_Type(num)
	return nil
}

// Deprecated: Use Delta_Type.Descriptor instead.
func (Delta_Type) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_delta_proto_rawDescGZIP(), []int{0, 0}
}

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Delta_Type            `protobuf:"varint,1,req,name=type,enum=spotify.protobuf_deltas.proto.Delta_Type" json:"type,omitempty"`
	Index         *uint32                `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	Length        *uint32                `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_protobuf_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_protobuf_delta_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetType() Delta_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Delta_DELETE
}

func (x *Delta) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Delta) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

var File_protobuf_delta_proto protoreflect.FileDescriptor

const file_protobuf_delta_proto_rawDesc = "" +
	"\n" +
	"\x14protobuf_delta.proto\x12\x1dspotify.protobuf_deltas.proto\"\x94\x01\n" +
	"\x05Delta\x12=\n" +
	"\x04type\x18\x01 \x02(\x0e2).spotify.protobuf_deltas.proto.Delta.TypeR\x04type\x12\x14\n" +
	"\x05index\x18\x02 \x02(\rR\x05index\x12\x16\n" +
	"\x06length\x18\x03 \x02(\rR\x06length\"\x1e\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06DELETE\x10\x00\x12\n" +
	"\n" +
	"\x06INSERT\x10\x01Bh\n" +
	"\x1dcom.spotify.cosmos.util.protoP\x01ZEgithub.com/pyrorhythm/libspot/api/spotifybuf_deltas;spotifybuf_deltas"

var (
	file_protobuf_delta_proto_rawDescOnce sync.Once
	file_protobuf_delta_proto_rawDescData []byte
)

func file_protobuf_delta_proto_rawDescGZIP() []byte {
	file_protobuf_delta_proto_rawDescOnce.Do(func() {
		file_protobuf_delta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_delta_proto_rawDesc), len(file_protobuf_delta_proto_rawDesc)))
	})
	return file_protobuf_delta_proto_rawDescData
}

var file_protobuf_delta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_delta_proto_goTypes = []any{
	(Delta_Type)(0), // 0: spotify.protobuf_deltas.proto.Delta.Type
	(*Delta)(nil),   // 1: spotify.protobuf_deltas.proto.Delta
}
var file_protobuf_delta_proto_depIdxs = []int32{
	0, // 0: spotify.protobuf_deltas.proto.Delta.type:type_name -> spotify.protobuf_deltas.proto.Delta.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_delta_proto_init() }
func file_protobuf_delta_proto_init() {
	if File_protobuf_delta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_delta_proto_rawDesc), len(file_protobuf_delta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_delta_proto_goTypes,
		DependencyIndexes: file_protobuf_delta_proto_depIdxs,
		EnumInfos:         file_protobuf_delta_proto_enumTypes,
		MessageInfos:      file_protobuf_delta_proto_msgTypes,
	}.Build()
	File_protobuf_delta_proto = out.File
	file_protobuf_delta_proto_goTypes = nil
	file_protobuf_delta_proto_depIdxs = nil
}
