// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: spotify/playback_platform/context/v1/context_environment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextEnvironment struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	SequenceOptions *SequenceOptions                      `protobuf:"bytes,1,opt,name=sequence_options,json=sequenceOptions,proto3" json:"sequence_options,omitempty"`
	SkipTo          *ContextEnvironment_LegacySkipToTrack `protobuf:"bytes,2,opt,name=skip_to,json=skipTo,proto3" json:"skip_to,omitempty"`
	Iteration       int32                                 `protobuf:"varint,5,opt,name=iteration,proto3" json:"iteration,omitempty"`
	Patch           *SequencePatch                        `protobuf:"bytes,4,opt,name=patch,proto3,oneof" json:"patch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContextEnvironment) Reset() {
	*x = ContextEnvironment{}
	mi := &file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEnvironment) ProtoMessage() {}

func (x *ContextEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextEnvironment.ProtoReflect.Descriptor instead.
func (*ContextEnvironment) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_context_environment_proto_rawDescGZIP(), []int{0}
}

func (x *ContextEnvironment) GetSequenceOptions() *SequenceOptions {
	if x != nil {
		return x.SequenceOptions
	}
	return nil
}

func (x *ContextEnvironment) GetSkipTo() *ContextEnvironment_LegacySkipToTrack {
	if x != nil {
		return x.SkipTo
	}
	return nil
}

func (x *ContextEnvironment) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

func (x *ContextEnvironment) GetPatch() *SequencePatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type ContextEnvironment_LegacySkipToTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *string                `protobuf:"bytes,1,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	ContextId     *string                `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3,oneof" json:"context_id,omitempty"`
	ItemIndex     *string                `protobuf:"bytes,3,opt,name=item_index,json=itemIndex,proto3,oneof" json:"item_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextEnvironment_LegacySkipToTrack) Reset() {
	*x = ContextEnvironment_LegacySkipToTrack{}
	mi := &file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextEnvironment_LegacySkipToTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextEnvironment_LegacySkipToTrack) ProtoMessage() {}

func (x *ContextEnvironment_LegacySkipToTrack) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextEnvironment_LegacySkipToTrack.ProtoReflect.Descriptor instead.
func (*ContextEnvironment_LegacySkipToTrack) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_context_environment_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ContextEnvironment_LegacySkipToTrack) GetUid() string {
	if x != nil && x.Uid != nil {
		return *x.Uid
	}
	return ""
}

func (x *ContextEnvironment_LegacySkipToTrack) GetContextId() string {
	if x != nil && x.ContextId != nil {
		return *x.ContextId
	}
	return ""
}

func (x *ContextEnvironment_LegacySkipToTrack) GetItemIndex() string {
	if x != nil && x.ItemIndex != nil {
		return *x.ItemIndex
	}
	return ""
}

var File_spotify_playback_platform_context_v1_context_environment_proto protoreflect.FileDescriptor

const file_spotify_playback_platform_context_v1_context_environment_proto_rawDesc = "" +
	"\n" +
	">spotify/playback_platform/context/v1/context_environment.proto\x12$spotify.playback_platform.context.v1\x1a;spotify/playback_platform/context/v1/sequence_options.proto\x1a9spotify/playback_platform/context/v1/sequence_patch.proto\"\x90\x04\n" +
	"\x12ContextEnvironment\x12`\n" +
	"\x10sequence_options\x18\x01 \x01(\v25.spotify.playback_platform.context.v1.SequenceOptionsR\x0fsequenceOptions\x12c\n" +
	"\askip_to\x18\x02 \x01(\v2J.spotify.playback_platform.context.v1.ContextEnvironment.LegacySkipToTrackR\x06skipTo\x12\x1c\n" +
	"\titeration\x18\x05 \x01(\x05R\titeration\x12N\n" +
	"\x05patch\x18\x04 \x01(\v23.spotify.playback_platform.context.v1.SequencePatchH\x00R\x05patch\x88\x01\x01\x1a\xba\x01\n" +
	"\x11LegacySkipToTrack\x12\x15\n" +
	"\x03uid\x18\x01 \x01(\tH\x00R\x03uid\x88\x01\x01\x12\"\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tH\x01R\tcontextId\x88\x01\x01\x12\"\n" +
	"\n" +
	"item_index\x18\x03 \x01(\tH\x02R\titemIndex\x88\x01\x01B\x06\n" +
	"\x04_uidB\r\n" +
	"\v_context_idB\r\n" +
	"\v_item_indexJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\n" +
	"page_indexR\bpage_urlB\b\n" +
	"\x06_patchBs\n" +
	"$spotify.playback_platform.context.v1P\x01ZIgithub.com/pyrorhythm/libspot/api/spotify/playback_platform/context/v1;v1b\x06proto3"

var (
	file_spotify_playback_platform_context_v1_context_environment_proto_rawDescOnce sync.Once
	file_spotify_playback_platform_context_v1_context_environment_proto_rawDescData []byte
)

func file_spotify_playback_platform_context_v1_context_environment_proto_rawDescGZIP() []byte {
	file_spotify_playback_platform_context_v1_context_environment_proto_rawDescOnce.Do(func() {
		file_spotify_playback_platform_context_v1_context_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_context_environment_proto_rawDesc), len(file_spotify_playback_platform_context_v1_context_environment_proto_rawDesc)))
	})
	return file_spotify_playback_platform_context_v1_context_environment_proto_rawDescData
}

var file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spotify_playback_platform_context_v1_context_environment_proto_goTypes = []any{
	(*ContextEnvironment)(nil),                   // 0: spotify.playback_platform.context.v1.ContextEnvironment
	(*ContextEnvironment_LegacySkipToTrack)(nil), // 1: spotify.playback_platform.context.v1.ContextEnvironment.LegacySkipToTrack
	(*SequenceOptions)(nil),                      // 2: spotify.playback_platform.context.v1.SequenceOptions
	(*SequencePatch)(nil),                        // 3: spotify.playback_platform.context.v1.SequencePatch
}
var file_spotify_playback_platform_context_v1_context_environment_proto_depIdxs = []int32{
	2, // 0: spotify.playback_platform.context.v1.ContextEnvironment.sequence_options:type_name -> spotify.playback_platform.context.v1.SequenceOptions
	1, // 1: spotify.playback_platform.context.v1.ContextEnvironment.skip_to:type_name -> spotify.playback_platform.context.v1.ContextEnvironment.LegacySkipToTrack
	3, // 2: spotify.playback_platform.context.v1.ContextEnvironment.patch:type_name -> spotify.playback_platform.context.v1.SequencePatch
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_spotify_playback_platform_context_v1_context_environment_proto_init() }
func file_spotify_playback_platform_context_v1_context_environment_proto_init() {
	if File_spotify_playback_platform_context_v1_context_environment_proto != nil {
		return
	}
	file_spotify_playback_platform_context_v1_sequence_options_proto_init()
	file_spotify_playback_platform_context_v1_sequence_patch_proto_init()
	file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[0].OneofWrappers = []any{}
	file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_context_environment_proto_rawDesc), len(file_spotify_playback_platform_context_v1_context_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_playback_platform_context_v1_context_environment_proto_goTypes,
		DependencyIndexes: file_spotify_playback_platform_context_v1_context_environment_proto_depIdxs,
		MessageInfos:      file_spotify_playback_platform_context_v1_context_environment_proto_msgTypes,
	}.Build()
	File_spotify_playback_platform_context_v1_context_environment_proto = out.File
	file_spotify_playback_platform_context_v1_context_environment_proto_goTypes = nil
	file_spotify_playback_platform_context_v1_context_environment_proto_depIdxs = nil
}
