// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: spotify/playback_platform/context/v1/requests.proto

package v1

import (
	v1 "github.com/pyrorhythm/libspot/api/spotify/playback_platform/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Queries       []*ContextRequest_Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Client        *v1.Client              `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0}
}

func (x *ContextRequest) GetQueries() []*ContextRequest_Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ContextRequest) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type SequencePageRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Queries       []*SequencePageRequest_Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	Client        *v1.Client                   `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencePageRequest) Reset() {
	*x = SequencePageRequest{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageRequest) ProtoMessage() {}

func (x *SequencePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageRequest.ProtoReflect.Descriptor instead.
func (*SequencePageRequest) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{1}
}

func (x *SequencePageRequest) GetQueries() []*SequencePageRequest_Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *SequencePageRequest) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ContextResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Results       []*ContextResponse_ResultsEntry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{2}
}

func (x *ContextResponse) GetResults() []*ContextResponse_ResultsEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type SequencePageResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Results       []*SequencePageResponse_ResultsEntry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencePageResponse) Reset() {
	*x = SequencePageResponse{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageResponse) ProtoMessage() {}

func (x *SequencePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageResponse.ProtoReflect.Descriptor instead.
func (*SequencePageResponse) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{3}
}

func (x *SequencePageResponse) GetResults() []*SequencePageResponse_ResultsEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type RemoteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	ContextQuery  *ContextRequest_Query  `protobuf:"bytes,4,opt,name=context_query,json=contextQuery,proto3" json:"context_query,omitempty"`
	Client        *v1.Client             `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	Ledger        *Ledger                `protobuf:"bytes,6,opt,name=ledger,proto3" json:"ledger,omitempty"`
	ActionId      *string                `protobuf:"bytes,2,opt,name=action_id,json=actionId,proto3,oneof" json:"action_id,omitempty"`
	Parameters    []byte                 `protobuf:"bytes,3,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActionRequest) Reset() {
	*x = RemoteActionRequest{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActionRequest) ProtoMessage() {}

func (x *RemoteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActionRequest.ProtoReflect.Descriptor instead.
func (*RemoteActionRequest) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{4}
}

func (x *RemoteActionRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *RemoteActionRequest) GetContextQuery() *ContextRequest_Query {
	if x != nil {
		return x.ContextQuery
	}
	return nil
}

func (x *RemoteActionRequest) GetClient() *v1.Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *RemoteActionRequest) GetLedger() *Ledger {
	if x != nil {
		return x.Ledger
	}
	return nil
}

func (x *RemoteActionRequest) GetActionId() string {
	if x != nil && x.ActionId != nil {
		return *x.ActionId
	}
	return ""
}

func (x *RemoteActionRequest) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type RemoteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*RemoteAction        `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Error         *v1.RequestError       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteActionResponse) Reset() {
	*x = RemoteActionResponse{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteActionResponse) ProtoMessage() {}

func (x *RemoteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteActionResponse.ProtoReflect.Descriptor instead.
func (*RemoteActionResponse) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteActionResponse) GetActions() []*RemoteAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RemoteActionResponse) GetError() *v1.RequestError {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoteAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*RemoteAction_Replace_
	//	*RemoteAction_Report
	//	*RemoteAction_Reload
	//	*RemoteAction_Unload
	//	*RemoteAction_Signal
	//	*RemoteAction_Player
	Action        isRemoteAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAction) Reset() {
	*x = RemoteAction{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAction) ProtoMessage() {}

func (x *RemoteAction) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAction.ProtoReflect.Descriptor instead.
func (*RemoteAction) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{6}
}

func (x *RemoteAction) GetAction() isRemoteAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RemoteAction) GetReplace() *RemoteAction_Replace {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Replace_); ok {
			return x.Replace
		}
	}
	return nil
}

func (x *RemoteAction) GetReport() *Action_Report {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *RemoteAction) GetReload() *Action_Reload {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *RemoteAction) GetUnload() *Action_Unload {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Unload); ok {
			return x.Unload
		}
	}
	return nil
}

func (x *RemoteAction) GetSignal() *Action_Signal {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *RemoteAction) GetPlayer() *Action_Player {
	if x != nil {
		if x, ok := x.Action.(*RemoteAction_Player); ok {
			return x.Player
		}
	}
	return nil
}

type isRemoteAction_Action interface {
	isRemoteAction_Action()
}

type RemoteAction_Replace_ struct {
	Replace *RemoteAction_Replace `protobuf:"bytes,1,opt,name=replace,proto3,oneof"`
}

type RemoteAction_Report struct {
	Report *Action_Report `protobuf:"bytes,2,opt,name=report,proto3,oneof"`
}

type RemoteAction_Reload struct {
	Reload *Action_Reload `protobuf:"bytes,3,opt,name=reload,proto3,oneof"`
}

type RemoteAction_Unload struct {
	Unload *Action_Unload `protobuf:"bytes,4,opt,name=unload,proto3,oneof"`
}

type RemoteAction_Signal struct {
	Signal *Action_Signal `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

type RemoteAction_Player struct {
	Player *Action_Player `protobuf:"bytes,6,opt,name=player,proto3,oneof"`
}

func (*RemoteAction_Replace_) isRemoteAction_Action() {}

func (*RemoteAction_Report) isRemoteAction_Action() {}

func (*RemoteAction_Reload) isRemoteAction_Action() {}

func (*RemoteAction_Unload) isRemoteAction_Action() {}

func (*RemoteAction_Signal) isRemoteAction_Action() {}

func (*RemoteAction_Player) isRemoteAction_Action() {}

type ContextRequest_Cache struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Children      []*ContextRequest_Cache_ChildrenEntry `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	EntityTag     []byte                                `protobuf:"bytes,1,opt,name=entity_tag,json=entityTag,proto3,oneof" json:"entity_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest_Cache) Reset() {
	*x = ContextRequest_Cache{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest_Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest_Cache) ProtoMessage() {}

func (x *ContextRequest_Cache) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest_Cache.ProtoReflect.Descriptor instead.
func (*ContextRequest_Cache) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ContextRequest_Cache) GetChildren() []*ContextRequest_Cache_ChildrenEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ContextRequest_Cache) GetEntityTag() []byte {
	if x != nil {
		return x.EntityTag
	}
	return nil
}

type ContextRequest_State struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	State         *ContextState                         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Children      []*ContextRequest_State_ChildrenEntry `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest_State) Reset() {
	*x = ContextRequest_State{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest_State) ProtoMessage() {}

func (x *ContextRequest_State) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest_State.ProtoReflect.Descriptor instead.
func (*ContextRequest_State) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ContextRequest_State) GetState() *ContextState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ContextRequest_State) GetChildren() []*ContextRequest_State_ChildrenEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

type ContextRequest_Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextId     string                 `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Cache         *ContextRequest_Cache  `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	State         *ContextRequest_State  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Env           *ContextEnvironment    `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest_Query) Reset() {
	*x = ContextRequest_Query{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest_Query) ProtoMessage() {}

func (x *ContextRequest_Query) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest_Query.ProtoReflect.Descriptor instead.
func (*ContextRequest_Query) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ContextRequest_Query) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *ContextRequest_Query) GetCache() *ContextRequest_Cache {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *ContextRequest_Query) GetState() *ContextRequest_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ContextRequest_Query) GetEnv() *ContextEnvironment {
	if x != nil {
		return x.Env
	}
	return nil
}

type ContextRequest_Cache_ChildrenEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ContextRequest_Cache  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest_Cache_ChildrenEntry) Reset() {
	*x = ContextRequest_Cache_ChildrenEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest_Cache_ChildrenEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest_Cache_ChildrenEntry) ProtoMessage() {}

func (x *ContextRequest_Cache_ChildrenEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest_Cache_ChildrenEntry.ProtoReflect.Descriptor instead.
func (*ContextRequest_Cache_ChildrenEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ContextRequest_Cache_ChildrenEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextRequest_Cache_ChildrenEntry) GetValue() *ContextRequest_Cache {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContextRequest_State_ChildrenEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ContextRequest_State  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest_State_ChildrenEntry) Reset() {
	*x = ContextRequest_State_ChildrenEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest_State_ChildrenEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest_State_ChildrenEntry) ProtoMessage() {}

func (x *ContextRequest_State_ChildrenEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest_State_ChildrenEntry.ProtoReflect.Descriptor instead.
func (*ContextRequest_State_ChildrenEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ContextRequest_State_ChildrenEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextRequest_State_ChildrenEntry) GetValue() *ContextRequest_State {
	if x != nil {
		return x.Value
	}
	return nil
}

type SequencePageRequest_Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        []byte                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ContextQuery  *ContextRequest_Query  `protobuf:"bytes,2,opt,name=context_query,json=contextQuery,proto3" json:"context_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencePageRequest_Query) Reset() {
	*x = SequencePageRequest_Query{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageRequest_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageRequest_Query) ProtoMessage() {}

func (x *SequencePageRequest_Query) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageRequest_Query.ProtoReflect.Descriptor instead.
func (*SequencePageRequest_Query) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SequencePageRequest_Query) GetPageId() []byte {
	if x != nil {
		return x.PageId
	}
	return nil
}

func (x *SequencePageRequest_Query) GetContextQuery() *ContextRequest_Query {
	if x != nil {
		return x.ContextQuery
	}
	return nil
}

type ContextResponse_Result struct {
	state             protoimpl.MessageState                           `protogen:"open.v1"`
	Error             *v1.RequestError                                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Context           *Context                                         `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	CacheControl      *v1.CacheControl                                 `protobuf:"bytes,3,opt,name=cache_control,json=cacheControl,proto3" json:"cache_control,omitempty"`
	State             *ContextState                                    `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Env               *ContextEnvironment                              `protobuf:"bytes,5,opt,name=env,proto3" json:"env,omitempty"`
	PreloadedChildren []*ContextResponse_Result_PreloadedChildrenEntry `protobuf:"bytes,6,rep,name=preloaded_children,json=preloadedChildren,proto3" json:"preloaded_children,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContextResponse_Result) Reset() {
	*x = ContextResponse_Result{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse_Result) ProtoMessage() {}

func (x *ContextResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse_Result.ProtoReflect.Descriptor instead.
func (*ContextResponse_Result) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ContextResponse_Result) GetError() *v1.RequestError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ContextResponse_Result) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ContextResponse_Result) GetCacheControl() *v1.CacheControl {
	if x != nil {
		return x.CacheControl
	}
	return nil
}

func (x *ContextResponse_Result) GetState() *ContextState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ContextResponse_Result) GetEnv() *ContextEnvironment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContextResponse_Result) GetPreloadedChildren() []*ContextResponse_Result_PreloadedChildrenEntry {
	if x != nil {
		return x.PreloadedChildren
	}
	return nil
}

type ContextResponse_ResultsEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           uint32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ContextResponse_Result `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse_ResultsEntry) Reset() {
	*x = ContextResponse_ResultsEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse_ResultsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse_ResultsEntry) ProtoMessage() {}

func (x *ContextResponse_ResultsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse_ResultsEntry.ProtoReflect.Descriptor instead.
func (*ContextResponse_ResultsEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ContextResponse_ResultsEntry) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ContextResponse_ResultsEntry) GetValue() *ContextResponse_Result {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContextResponse_Result_PreloadedChildrenEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ContextResponse_Result `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse_Result_PreloadedChildrenEntry) Reset() {
	*x = ContextResponse_Result_PreloadedChildrenEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse_Result_PreloadedChildrenEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse_Result_PreloadedChildrenEntry) ProtoMessage() {}

func (x *ContextResponse_Result_PreloadedChildrenEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse_Result_PreloadedChildrenEntry.ProtoReflect.Descriptor instead.
func (*ContextResponse_Result_PreloadedChildrenEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ContextResponse_Result_PreloadedChildrenEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ContextResponse_Result_PreloadedChildrenEntry) GetValue() *ContextResponse_Result {
	if x != nil {
		return x.Value
	}
	return nil
}

type SequencePageResponse_Result struct {
	state             protoimpl.MessageState                                `protogen:"open.v1"`
	Error             *v1.RequestError                                      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Children          []*SequenceChild                                      `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	PreloadedChildren []*SequencePageResponse_Result_PreloadedChildrenEntry `protobuf:"bytes,5,rep,name=preloaded_children,json=preloadedChildren,proto3" json:"preloaded_children,omitempty"`
	PrevPageId        []byte                                                `protobuf:"bytes,3,opt,name=prev_page_id,json=prevPageId,proto3,oneof" json:"prev_page_id,omitempty"`
	NextPageId        []byte                                                `protobuf:"bytes,4,opt,name=next_page_id,json=nextPageId,proto3,oneof" json:"next_page_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SequencePageResponse_Result) Reset() {
	*x = SequencePageResponse_Result{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageResponse_Result) ProtoMessage() {}

func (x *SequencePageResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageResponse_Result.ProtoReflect.Descriptor instead.
func (*SequencePageResponse_Result) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SequencePageResponse_Result) GetError() *v1.RequestError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SequencePageResponse_Result) GetChildren() []*SequenceChild {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *SequencePageResponse_Result) GetPreloadedChildren() []*SequencePageResponse_Result_PreloadedChildrenEntry {
	if x != nil {
		return x.PreloadedChildren
	}
	return nil
}

func (x *SequencePageResponse_Result) GetPrevPageId() []byte {
	if x != nil {
		return x.PrevPageId
	}
	return nil
}

func (x *SequencePageResponse_Result) GetNextPageId() []byte {
	if x != nil {
		return x.NextPageId
	}
	return nil
}

type SequencePageResponse_ResultsEntry struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Key           uint32                       `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *SequencePageResponse_Result `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencePageResponse_ResultsEntry) Reset() {
	*x = SequencePageResponse_ResultsEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageResponse_ResultsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageResponse_ResultsEntry) ProtoMessage() {}

func (x *SequencePageResponse_ResultsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageResponse_ResultsEntry.ProtoReflect.Descriptor instead.
func (*SequencePageResponse_ResultsEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{3, 1}
}

func (x *SequencePageResponse_ResultsEntry) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *SequencePageResponse_ResultsEntry) GetValue() *SequencePageResponse_Result {
	if x != nil {
		return x.Value
	}
	return nil
}

type SequencePageResponse_Result_PreloadedChildrenEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           string                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *ContextResponse_Result `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencePageResponse_Result_PreloadedChildrenEntry) Reset() {
	*x = SequencePageResponse_Result_PreloadedChildrenEntry{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencePageResponse_Result_PreloadedChildrenEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencePageResponse_Result_PreloadedChildrenEntry) ProtoMessage() {}

func (x *SequencePageResponse_Result_PreloadedChildrenEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencePageResponse_Result_PreloadedChildrenEntry.ProtoReflect.Descriptor instead.
func (*SequencePageResponse_Result_PreloadedChildrenEntry) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *SequencePageResponse_Result_PreloadedChildrenEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SequencePageResponse_Result_PreloadedChildrenEntry) GetValue() *ContextResponse_Result {
	if x != nil {
		return x.Value
	}
	return nil
}

type RemoteAction_Replace struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        *ContextResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteAction_Replace) Reset() {
	*x = RemoteAction_Replace{}
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAction_Replace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAction_Replace) ProtoMessage() {}

func (x *RemoteAction_Replace) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_requests_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAction_Replace.ProtoReflect.Descriptor instead.
func (*RemoteAction_Replace) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RemoteAction_Replace) GetResult() *ContextResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_spotify_playback_platform_context_v1_requests_proto protoreflect.FileDescriptor

const file_spotify_playback_platform_context_v1_requests_proto_rawDesc = "" +
	"\n" +
	"3spotify/playback_platform/context/v1/requests.proto\x12$spotify.playback_platform.context.v1\x1a7spotify/playback_platform/common/v1/cache_control.proto\x1a0spotify/playback_platform/common/v1/client.proto\x1a7spotify/playback_platform/common/v1/request_error.proto\x1a:spotify/playback_platform/context/v1/behavior/action.proto\x1a2spotify/playback_platform/context/v1/context.proto\x1a>spotify/playback_platform/context/v1/context_environment.proto\x1a8spotify/playback_platform/context/v1/context_state.proto\x1a1spotify/playback_platform/context/v1/ledger.proto\x1a9spotify/playback_platform/context/v1/sequence_child.proto\"\x8b\b\n" +
	"\x0eContextRequest\x12T\n" +
	"\aqueries\x18\x01 \x03(\v2:.spotify.playback_platform.context.v1.ContextRequest.QueryR\aqueries\x12C\n" +
	"\x06client\x18\x02 \x01(\v2+.spotify.playback_platform.common.v1.ClientR\x06client\x1a\x95\x02\n" +
	"\x05Cache\x12d\n" +
	"\bchildren\x18\x02 \x03(\v2H.spotify.playback_platform.context.v1.ContextRequest.Cache.ChildrenEntryR\bchildren\x12\"\n" +
	"\n" +
	"entity_tag\x18\x01 \x01(\fH\x00R\tentityTag\x88\x01\x01\x1as\n" +
	"\rChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\x05value\x18\x02 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.CacheR\x05valueB\r\n" +
	"\v_entity_tag\x1a\xac\x02\n" +
	"\x05State\x12H\n" +
	"\x05state\x18\x01 \x01(\v22.spotify.playback_platform.context.v1.ContextStateR\x05state\x12d\n" +
	"\bchildren\x18\x02 \x03(\v2H.spotify.playback_platform.context.v1.ContextRequest.State.ChildrenEntryR\bchildren\x1as\n" +
	"\rChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\x05value\x18\x02 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.StateR\x05value\x1a\x96\x02\n" +
	"\x05Query\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12P\n" +
	"\x05cache\x18\x02 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.CacheR\x05cache\x12P\n" +
	"\x05state\x18\x03 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.StateR\x05state\x12J\n" +
	"\x03env\x18\x04 \x01(\v28.spotify.playback_platform.context.v1.ContextEnvironmentR\x03env\"\xb9\x02\n" +
	"\x13SequencePageRequest\x12Y\n" +
	"\aqueries\x18\x01 \x03(\v2?.spotify.playback_platform.context.v1.SequencePageRequest.QueryR\aqueries\x12C\n" +
	"\x06client\x18\x02 \x01(\v2+.spotify.playback_platform.common.v1.ClientR\x06client\x1a\x81\x01\n" +
	"\x05Query\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\fR\x06pageId\x12_\n" +
	"\rcontext_query\x18\x02 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.QueryR\fcontextQuery\"\xf5\x06\n" +
	"\x0fContextResponse\x12\\\n" +
	"\aresults\x18\x01 \x03(\v2B.spotify.playback_platform.context.v1.ContextResponse.ResultsEntryR\aresults\x1a\x8d\x05\n" +
	"\x06Result\x12G\n" +
	"\x05error\x18\x01 \x01(\v21.spotify.playback_platform.common.v1.RequestErrorR\x05error\x12G\n" +
	"\acontext\x18\x02 \x01(\v2-.spotify.playback_platform.context.v1.ContextR\acontext\x12V\n" +
	"\rcache_control\x18\x03 \x01(\v21.spotify.playback_platform.common.v1.CacheControlR\fcacheControl\x12H\n" +
	"\x05state\x18\x04 \x01(\v22.spotify.playback_platform.context.v1.ContextStateR\x05state\x12J\n" +
	"\x03env\x18\x05 \x01(\v28.spotify.playback_platform.context.v1.ContextEnvironmentR\x03env\x12\x82\x01\n" +
	"\x12preloaded_children\x18\x06 \x03(\v2S.spotify.playback_platform.context.v1.ContextResponse.Result.PreloadedChildrenEntryR\x11preloadedChildren\x1a~\n" +
	"\x16PreloadedChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12R\n" +
	"\x05value\x18\x02 \x01(\v2<.spotify.playback_platform.context.v1.ContextResponse.ResultR\x05value\x1at\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12R\n" +
	"\x05value\x18\x02 \x01(\v2<.spotify.playback_platform.context.v1.ContextResponse.ResultR\x05value\"\x93\x06\n" +
	"\x14SequencePageResponse\x12a\n" +
	"\aresults\x18\x01 \x03(\v2G.spotify.playback_platform.context.v1.SequencePageResponse.ResultsEntryR\aresults\x1a\x9c\x04\n" +
	"\x06Result\x12G\n" +
	"\x05error\x18\x01 \x01(\v21.spotify.playback_platform.common.v1.RequestErrorR\x05error\x12O\n" +
	"\bchildren\x18\x02 \x03(\v23.spotify.playback_platform.context.v1.SequenceChildR\bchildren\x12\x87\x01\n" +
	"\x12preloaded_children\x18\x05 \x03(\v2X.spotify.playback_platform.context.v1.SequencePageResponse.Result.PreloadedChildrenEntryR\x11preloadedChildren\x12%\n" +
	"\fprev_page_id\x18\x03 \x01(\fH\x00R\n" +
	"prevPageId\x88\x01\x01\x12%\n" +
	"\fnext_page_id\x18\x04 \x01(\fH\x01R\n" +
	"nextPageId\x88\x01\x01\x1a~\n" +
	"\x16PreloadedChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12R\n" +
	"\x05value\x18\x02 \x01(\v2<.spotify.playback_platform.context.v1.ContextResponse.ResultR\x05valueB\x0f\n" +
	"\r_prev_page_idB\x0f\n" +
	"\r_next_page_id\x1ay\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12W\n" +
	"\x05value\x18\x02 \x01(\v2A.spotify.playback_platform.context.v1.SequencePageResponse.ResultR\x05value\"\x84\x03\n" +
	"\x13RemoteActionRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12_\n" +
	"\rcontext_query\x18\x04 \x01(\v2:.spotify.playback_platform.context.v1.ContextRequest.QueryR\fcontextQuery\x12C\n" +
	"\x06client\x18\x05 \x01(\v2+.spotify.playback_platform.common.v1.ClientR\x06client\x12D\n" +
	"\x06ledger\x18\x06 \x01(\v2,.spotify.playback_platform.context.v1.LedgerR\x06ledger\x12 \n" +
	"\taction_id\x18\x02 \x01(\tH\x00R\bactionId\x88\x01\x01\x12#\n" +
	"\n" +
	"parameters\x18\x03 \x01(\fH\x01R\n" +
	"parameters\x88\x01\x01B\f\n" +
	"\n" +
	"_action_idB\r\n" +
	"\v_parameters\"\xad\x01\n" +
	"\x14RemoteActionResponse\x12L\n" +
	"\aactions\x18\x01 \x03(\v22.spotify.playback_platform.context.v1.RemoteActionR\aactions\x12G\n" +
	"\x05error\x18\x02 \x01(\v21.spotify.playback_platform.common.v1.RequestErrorR\x05error\"\x89\x05\n" +
	"\fRemoteAction\x12V\n" +
	"\areplace\x18\x01 \x01(\v2:.spotify.playback_platform.context.v1.RemoteAction.ReplaceH\x00R\areplace\x12V\n" +
	"\x06report\x18\x02 \x01(\v2<.spotify.playback_platform.context.v1.behavior.Action.ReportH\x00R\x06report\x12V\n" +
	"\x06reload\x18\x03 \x01(\v2<.spotify.playback_platform.context.v1.behavior.Action.ReloadH\x00R\x06reload\x12V\n" +
	"\x06unload\x18\x04 \x01(\v2<.spotify.playback_platform.context.v1.behavior.Action.UnloadH\x00R\x06unload\x12V\n" +
	"\x06signal\x18\x05 \x01(\v2<.spotify.playback_platform.context.v1.behavior.Action.SignalH\x00R\x06signal\x12V\n" +
	"\x06player\x18\x06 \x01(\v2<.spotify.playback_platform.context.v1.behavior.Action.PlayerH\x00R\x06player\x1a_\n" +
	"\aReplace\x12T\n" +
	"\x06result\x18\x01 \x01(\v2<.spotify.playback_platform.context.v1.ContextResponse.ResultR\x06resultB\b\n" +
	"\x06actionBs\n" +
	"$spotify.playback_platform.context.v1P\x01ZIgithub.com/pyrorhythm/libspot/api/spotify/playback_platform/context/v1;v1b\x06proto3"

var (
	file_spotify_playback_platform_context_v1_requests_proto_rawDescOnce sync.Once
	file_spotify_playback_platform_context_v1_requests_proto_rawDescData []byte
)

func file_spotify_playback_platform_context_v1_requests_proto_rawDescGZIP() []byte {
	file_spotify_playback_platform_context_v1_requests_proto_rawDescOnce.Do(func() {
		file_spotify_playback_platform_context_v1_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_requests_proto_rawDesc), len(file_spotify_playback_platform_context_v1_requests_proto_rawDesc)))
	})
	return file_spotify_playback_platform_context_v1_requests_proto_rawDescData
}

var file_spotify_playback_platform_context_v1_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_spotify_playback_platform_context_v1_requests_proto_goTypes = []any{
	(*ContextRequest)(nil),                                     // 0: spotify.playback_platform.context.v1.ContextRequest
	(*SequencePageRequest)(nil),                                // 1: spotify.playback_platform.context.v1.SequencePageRequest
	(*ContextResponse)(nil),                                    // 2: spotify.playback_platform.context.v1.ContextResponse
	(*SequencePageResponse)(nil),                               // 3: spotify.playback_platform.context.v1.SequencePageResponse
	(*RemoteActionRequest)(nil),                                // 4: spotify.playback_platform.context.v1.RemoteActionRequest
	(*RemoteActionResponse)(nil),                               // 5: spotify.playback_platform.context.v1.RemoteActionResponse
	(*RemoteAction)(nil),                                       // 6: spotify.playback_platform.context.v1.RemoteAction
	(*ContextRequest_Cache)(nil),                               // 7: spotify.playback_platform.context.v1.ContextRequest.Cache
	(*ContextRequest_State)(nil),                               // 8: spotify.playback_platform.context.v1.ContextRequest.State
	(*ContextRequest_Query)(nil),                               // 9: spotify.playback_platform.context.v1.ContextRequest.Query
	(*ContextRequest_Cache_ChildrenEntry)(nil),                 // 10: spotify.playback_platform.context.v1.ContextRequest.Cache.ChildrenEntry
	(*ContextRequest_State_ChildrenEntry)(nil),                 // 11: spotify.playback_platform.context.v1.ContextRequest.State.ChildrenEntry
	(*SequencePageRequest_Query)(nil),                          // 12: spotify.playback_platform.context.v1.SequencePageRequest.Query
	(*ContextResponse_Result)(nil),                             // 13: spotify.playback_platform.context.v1.ContextResponse.Result
	(*ContextResponse_ResultsEntry)(nil),                       // 14: spotify.playback_platform.context.v1.ContextResponse.ResultsEntry
	(*ContextResponse_Result_PreloadedChildrenEntry)(nil),      // 15: spotify.playback_platform.context.v1.ContextResponse.Result.PreloadedChildrenEntry
	(*SequencePageResponse_Result)(nil),                        // 16: spotify.playback_platform.context.v1.SequencePageResponse.Result
	(*SequencePageResponse_ResultsEntry)(nil),                  // 17: spotify.playback_platform.context.v1.SequencePageResponse.ResultsEntry
	(*SequencePageResponse_Result_PreloadedChildrenEntry)(nil), // 18: spotify.playback_platform.context.v1.SequencePageResponse.Result.PreloadedChildrenEntry
	(*RemoteAction_Replace)(nil),                               // 19: spotify.playback_platform.context.v1.RemoteAction.Replace
	(*v1.Client)(nil),                                          // 20: spotify.playback_platform.common.v1.Client
	(*Ledger)(nil),                                             // 21: spotify.playback_platform.context.v1.Ledger
	(*v1.RequestError)(nil),                                    // 22: spotify.playback_platform.common.v1.RequestError
	(*Action_Report)(nil),                                      // 23: spotify.playback_platform.context.v1.behavior.Action.Report
	(*Action_Reload)(nil),                                      // 24: spotify.playback_platform.context.v1.behavior.Action.Reload
	(*Action_Unload)(nil),                                      // 25: spotify.playback_platform.context.v1.behavior.Action.Unload
	(*Action_Signal)(nil),                                      // 26: spotify.playback_platform.context.v1.behavior.Action.Signal
	(*Action_Player)(nil),                                      // 27: spotify.playback_platform.context.v1.behavior.Action.Player
	(*ContextState)(nil),                                       // 28: spotify.playback_platform.context.v1.ContextState
	(*ContextEnvironment)(nil),                                 // 29: spotify.playback_platform.context.v1.ContextEnvironment
	(*Context)(nil),                                            // 30: spotify.playback_platform.context.v1.Context
	(*v1.CacheControl)(nil),                                    // 31: spotify.playback_platform.common.v1.CacheControl
	(*SequenceChild)(nil),                                      // 32: spotify.playback_platform.context.v1.SequenceChild
}
var file_spotify_playback_platform_context_v1_requests_proto_depIdxs = []int32{
	9,  // 0: spotify.playback_platform.context.v1.ContextRequest.queries:type_name -> spotify.playback_platform.context.v1.ContextRequest.Query
	20, // 1: spotify.playback_platform.context.v1.ContextRequest.client:type_name -> spotify.playback_platform.common.v1.Client
	12, // 2: spotify.playback_platform.context.v1.SequencePageRequest.queries:type_name -> spotify.playback_platform.context.v1.SequencePageRequest.Query
	20, // 3: spotify.playback_platform.context.v1.SequencePageRequest.client:type_name -> spotify.playback_platform.common.v1.Client
	14, // 4: spotify.playback_platform.context.v1.ContextResponse.results:type_name -> spotify.playback_platform.context.v1.ContextResponse.ResultsEntry
	17, // 5: spotify.playback_platform.context.v1.SequencePageResponse.results:type_name -> spotify.playback_platform.context.v1.SequencePageResponse.ResultsEntry
	9,  // 6: spotify.playback_platform.context.v1.RemoteActionRequest.context_query:type_name -> spotify.playback_platform.context.v1.ContextRequest.Query
	20, // 7: spotify.playback_platform.context.v1.RemoteActionRequest.client:type_name -> spotify.playback_platform.common.v1.Client
	21, // 8: spotify.playback_platform.context.v1.RemoteActionRequest.ledger:type_name -> spotify.playback_platform.context.v1.Ledger
	6,  // 9: spotify.playback_platform.context.v1.RemoteActionResponse.actions:type_name -> spotify.playback_platform.context.v1.RemoteAction
	22, // 10: spotify.playback_platform.context.v1.RemoteActionResponse.error:type_name -> spotify.playback_platform.common.v1.RequestError
	19, // 11: spotify.playback_platform.context.v1.RemoteAction.replace:type_name -> spotify.playback_platform.context.v1.RemoteAction.Replace
	23, // 12: spotify.playback_platform.context.v1.RemoteAction.report:type_name -> spotify.playback_platform.context.v1.behavior.Action.Report
	24, // 13: spotify.playback_platform.context.v1.RemoteAction.reload:type_name -> spotify.playback_platform.context.v1.behavior.Action.Reload
	25, // 14: spotify.playback_platform.context.v1.RemoteAction.unload:type_name -> spotify.playback_platform.context.v1.behavior.Action.Unload
	26, // 15: spotify.playback_platform.context.v1.RemoteAction.signal:type_name -> spotify.playback_platform.context.v1.behavior.Action.Signal
	27, // 16: spotify.playback_platform.context.v1.RemoteAction.player:type_name -> spotify.playback_platform.context.v1.behavior.Action.Player
	10, // 17: spotify.playback_platform.context.v1.ContextRequest.Cache.children:type_name -> spotify.playback_platform.context.v1.ContextRequest.Cache.ChildrenEntry
	28, // 18: spotify.playback_platform.context.v1.ContextRequest.State.state:type_name -> spotify.playback_platform.context.v1.ContextState
	11, // 19: spotify.playback_platform.context.v1.ContextRequest.State.children:type_name -> spotify.playback_platform.context.v1.ContextRequest.State.ChildrenEntry
	7,  // 20: spotify.playback_platform.context.v1.ContextRequest.Query.cache:type_name -> spotify.playback_platform.context.v1.ContextRequest.Cache
	8,  // 21: spotify.playback_platform.context.v1.ContextRequest.Query.state:type_name -> spotify.playback_platform.context.v1.ContextRequest.State
	29, // 22: spotify.playback_platform.context.v1.ContextRequest.Query.env:type_name -> spotify.playback_platform.context.v1.ContextEnvironment
	7,  // 23: spotify.playback_platform.context.v1.ContextRequest.Cache.ChildrenEntry.value:type_name -> spotify.playback_platform.context.v1.ContextRequest.Cache
	8,  // 24: spotify.playback_platform.context.v1.ContextRequest.State.ChildrenEntry.value:type_name -> spotify.playback_platform.context.v1.ContextRequest.State
	9,  // 25: spotify.playback_platform.context.v1.SequencePageRequest.Query.context_query:type_name -> spotify.playback_platform.context.v1.ContextRequest.Query
	22, // 26: spotify.playback_platform.context.v1.ContextResponse.Result.error:type_name -> spotify.playback_platform.common.v1.RequestError
	30, // 27: spotify.playback_platform.context.v1.ContextResponse.Result.context:type_name -> spotify.playback_platform.context.v1.Context
	31, // 28: spotify.playback_platform.context.v1.ContextResponse.Result.cache_control:type_name -> spotify.playback_platform.common.v1.CacheControl
	28, // 29: spotify.playback_platform.context.v1.ContextResponse.Result.state:type_name -> spotify.playback_platform.context.v1.ContextState
	29, // 30: spotify.playback_platform.context.v1.ContextResponse.Result.env:type_name -> spotify.playback_platform.context.v1.ContextEnvironment
	15, // 31: spotify.playback_platform.context.v1.ContextResponse.Result.preloaded_children:type_name -> spotify.playback_platform.context.v1.ContextResponse.Result.PreloadedChildrenEntry
	13, // 32: spotify.playback_platform.context.v1.ContextResponse.ResultsEntry.value:type_name -> spotify.playback_platform.context.v1.ContextResponse.Result
	13, // 33: spotify.playback_platform.context.v1.ContextResponse.Result.PreloadedChildrenEntry.value:type_name -> spotify.playback_platform.context.v1.ContextResponse.Result
	22, // 34: spotify.playback_platform.context.v1.SequencePageResponse.Result.error:type_name -> spotify.playback_platform.common.v1.RequestError
	32, // 35: spotify.playback_platform.context.v1.SequencePageResponse.Result.children:type_name -> spotify.playback_platform.context.v1.SequenceChild
	18, // 36: spotify.playback_platform.context.v1.SequencePageResponse.Result.preloaded_children:type_name -> spotify.playback_platform.context.v1.SequencePageResponse.Result.PreloadedChildrenEntry
	16, // 37: spotify.playback_platform.context.v1.SequencePageResponse.ResultsEntry.value:type_name -> spotify.playback_platform.context.v1.SequencePageResponse.Result
	13, // 38: spotify.playback_platform.context.v1.SequencePageResponse.Result.PreloadedChildrenEntry.value:type_name -> spotify.playback_platform.context.v1.ContextResponse.Result
	13, // 39: spotify.playback_platform.context.v1.RemoteAction.Replace.result:type_name -> spotify.playback_platform.context.v1.ContextResponse.Result
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_spotify_playback_platform_context_v1_requests_proto_init() }
func file_spotify_playback_platform_context_v1_requests_proto_init() {
	if File_spotify_playback_platform_context_v1_requests_proto != nil {
		return
	}
	file_spotify_playback_platform_context_v1_behavior_action_proto_init()
	file_spotify_playback_platform_context_v1_context_proto_init()
	file_spotify_playback_platform_context_v1_context_environment_proto_init()
	file_spotify_playback_platform_context_v1_context_state_proto_init()
	file_spotify_playback_platform_context_v1_ledger_proto_init()
	file_spotify_playback_platform_context_v1_sequence_child_proto_init()
	file_spotify_playback_platform_context_v1_requests_proto_msgTypes[4].OneofWrappers = []any{}
	file_spotify_playback_platform_context_v1_requests_proto_msgTypes[6].OneofWrappers = []any{
		(*RemoteAction_Replace_)(nil),
		(*RemoteAction_Report)(nil),
		(*RemoteAction_Reload)(nil),
		(*RemoteAction_Unload)(nil),
		(*RemoteAction_Signal)(nil),
		(*RemoteAction_Player)(nil),
	}
	file_spotify_playback_platform_context_v1_requests_proto_msgTypes[7].OneofWrappers = []any{}
	file_spotify_playback_platform_context_v1_requests_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_requests_proto_rawDesc), len(file_spotify_playback_platform_context_v1_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_playback_platform_context_v1_requests_proto_goTypes,
		DependencyIndexes: file_spotify_playback_platform_context_v1_requests_proto_depIdxs,
		MessageInfos:      file_spotify_playback_platform_context_v1_requests_proto_msgTypes,
	}.Build()
	File_spotify_playback_platform_context_v1_requests_proto = out.File
	file_spotify_playback_platform_context_v1_requests_proto_goTypes = nil
	file_spotify_playback_platform_context_v1_requests_proto_depIdxs = nil
}
