// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: spotify/playback_platform/context/v1/sequence_options.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SequenceOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShufflingSequence *bool                  `protobuf:"varint,1,opt,name=shuffling_sequence,json=shufflingSequence,proto3,oneof" json:"shuffling_sequence,omitempty"`
	EnhancingSequence *bool                  `protobuf:"varint,2,opt,name=enhancing_sequence,json=enhancingSequence,proto3,oneof" json:"enhancing_sequence,omitempty"`
	RepeatingSequence *bool                  `protobuf:"varint,3,opt,name=repeating_sequence,json=repeatingSequence,proto3,oneof" json:"repeating_sequence,omitempty"`
	RepeatingTimeline *bool                  `protobuf:"varint,4,opt,name=repeating_timeline,json=repeatingTimeline,proto3,oneof" json:"repeating_timeline,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SequenceOptions) Reset() {
	*x = SequenceOptions{}
	mi := &file_spotify_playback_platform_context_v1_sequence_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceOptions) ProtoMessage() {}

func (x *SequenceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_spotify_playback_platform_context_v1_sequence_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceOptions.ProtoReflect.Descriptor instead.
func (*SequenceOptions) Descriptor() ([]byte, []int) {
	return file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescGZIP(), []int{0}
}

func (x *SequenceOptions) GetShufflingSequence() bool {
	if x != nil && x.ShufflingSequence != nil {
		return *x.ShufflingSequence
	}
	return false
}

func (x *SequenceOptions) GetEnhancingSequence() bool {
	if x != nil && x.EnhancingSequence != nil {
		return *x.EnhancingSequence
	}
	return false
}

func (x *SequenceOptions) GetRepeatingSequence() bool {
	if x != nil && x.RepeatingSequence != nil {
		return *x.RepeatingSequence
	}
	return false
}

func (x *SequenceOptions) GetRepeatingTimeline() bool {
	if x != nil && x.RepeatingTimeline != nil {
		return *x.RepeatingTimeline
	}
	return false
}

var File_spotify_playback_platform_context_v1_sequence_options_proto protoreflect.FileDescriptor

const file_spotify_playback_platform_context_v1_sequence_options_proto_rawDesc = "" +
	"\n" +
	";spotify/playback_platform/context/v1/sequence_options.proto\x12$spotify.playback_platform.context.v1\"\xbd\x02\n" +
	"\x0fSequenceOptions\x122\n" +
	"\x12shuffling_sequence\x18\x01 \x01(\bH\x00R\x11shufflingSequence\x88\x01\x01\x122\n" +
	"\x12enhancing_sequence\x18\x02 \x01(\bH\x01R\x11enhancingSequence\x88\x01\x01\x122\n" +
	"\x12repeating_sequence\x18\x03 \x01(\bH\x02R\x11repeatingSequence\x88\x01\x01\x122\n" +
	"\x12repeating_timeline\x18\x04 \x01(\bH\x03R\x11repeatingTimeline\x88\x01\x01B\x15\n" +
	"\x13_shuffling_sequenceB\x15\n" +
	"\x13_enhancing_sequenceB\x15\n" +
	"\x13_repeating_sequenceB\x15\n" +
	"\x13_repeating_timelineBs\n" +
	"$spotify.playback_platform.context.v1P\x01ZIgithub.com/pyrorhythm/libspot/api/spotify/playback_platform/context/v1;v1b\x06proto3"

var (
	file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescOnce sync.Once
	file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescData []byte
)

func file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescGZIP() []byte {
	file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescOnce.Do(func() {
		file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_sequence_options_proto_rawDesc), len(file_spotify_playback_platform_context_v1_sequence_options_proto_rawDesc)))
	})
	return file_spotify_playback_platform_context_v1_sequence_options_proto_rawDescData
}

var file_spotify_playback_platform_context_v1_sequence_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spotify_playback_platform_context_v1_sequence_options_proto_goTypes = []any{
	(*SequenceOptions)(nil), // 0: spotify.playback_platform.context.v1.SequenceOptions
}
var file_spotify_playback_platform_context_v1_sequence_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spotify_playback_platform_context_v1_sequence_options_proto_init() }
func file_spotify_playback_platform_context_v1_sequence_options_proto_init() {
	if File_spotify_playback_platform_context_v1_sequence_options_proto != nil {
		return
	}
	file_spotify_playback_platform_context_v1_sequence_options_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotify_playback_platform_context_v1_sequence_options_proto_rawDesc), len(file_spotify_playback_platform_context_v1_sequence_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spotify_playback_platform_context_v1_sequence_options_proto_goTypes,
		DependencyIndexes: file_spotify_playback_platform_context_v1_sequence_options_proto_depIdxs,
		MessageInfos:      file_spotify_playback_platform_context_v1_sequence_options_proto_msgTypes,
	}.Build()
	File_spotify_playback_platform_context_v1_sequence_options_proto = out.File
	file_spotify_playback_platform_context_v1_sequence_options_proto_goTypes = nil
	file_spotify_playback_platform_context_v1_sequence_options_proto_depIdxs = nil
}
