// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: policy/episode_decoration_policy.proto

package cosmos_util

import (
	extendedmetadata "github.com/pyrorhythm/libspot/api/spotify/extendedmetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpisodeDecorationPolicy struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	Link              bool                             `protobuf:"varint,1,opt,name=link,proto3" json:"link,omitempty"`
	Length            bool                             `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Name              bool                             `protobuf:"varint,3,opt,name=name,proto3" json:"name,omitempty"`
	ManifestId        bool                             `protobuf:"varint,4,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	PreviewId         bool                             `protobuf:"varint,5,opt,name=preview_id,json=previewId,proto3" json:"preview_id,omitempty"`
	PreviewManifestId bool                             `protobuf:"varint,6,opt,name=preview_manifest_id,json=previewManifestId,proto3" json:"preview_manifest_id,omitempty"`
	Description       bool                             `protobuf:"varint,7,opt,name=description,proto3" json:"description,omitempty"`
	PublishDate       bool                             `protobuf:"varint,8,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	Covers            bool                             `protobuf:"varint,9,opt,name=covers,proto3" json:"covers,omitempty"`
	FreezeFrames      bool                             `protobuf:"varint,10,opt,name=freeze_frames,json=freezeFrames,proto3" json:"freeze_frames,omitempty"`
	Language          bool                             `protobuf:"varint,11,opt,name=language,proto3" json:"language,omitempty"`
	Available         bool                             `protobuf:"varint,12,opt,name=available,proto3" json:"available,omitempty"`
	MediaTypeEnum     bool                             `protobuf:"varint,13,opt,name=media_type_enum,json=mediaTypeEnum,proto3" json:"media_type_enum,omitempty"`
	Number            bool                             `protobuf:"varint,14,opt,name=number,proto3" json:"number,omitempty"`
	Backgroundable    bool                             `protobuf:"varint,15,opt,name=backgroundable,proto3" json:"backgroundable,omitempty"`
	IsExplicit        bool                             `protobuf:"varint,16,opt,name=is_explicit,json=isExplicit,proto3" json:"is_explicit,omitempty"`
	Type              bool                             `protobuf:"varint,17,opt,name=type,proto3" json:"type,omitempty"`
	IsMusicAndTalk    bool                             `protobuf:"varint,18,opt,name=is_music_and_talk,json=isMusicAndTalk,proto3" json:"is_music_and_talk,omitempty"`
	Extension         []extendedmetadata.ExtensionKind `protobuf:"varint,21,rep,packed,name=extension,proto3,enum=spotify.extendedmetadata.ExtensionKind" json:"extension,omitempty"`
	Is_19PlusOnly     bool                             `protobuf:"varint,22,opt,name=is_19_plus_only,json=is19PlusOnly,proto3" json:"is_19_plus_only,omitempty"`
	IsBookChapter     bool                             `protobuf:"varint,23,opt,name=is_book_chapter,json=isBookChapter,proto3" json:"is_book_chapter,omitempty"`
	IsPodcastShort    bool                             `protobuf:"varint,24,opt,name=is_podcast_short,json=isPodcastShort,proto3" json:"is_podcast_short,omitempty"`
	IsCurated         bool                             `protobuf:"varint,25,opt,name=is_curated,json=isCurated,proto3" json:"is_curated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EpisodeDecorationPolicy) Reset() {
	*x = EpisodeDecorationPolicy{}
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeDecorationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeDecorationPolicy) ProtoMessage() {}

func (x *EpisodeDecorationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeDecorationPolicy.ProtoReflect.Descriptor instead.
func (*EpisodeDecorationPolicy) Descriptor() ([]byte, []int) {
	return file_policy_episode_decoration_policy_proto_rawDescGZIP(), []int{0}
}

func (x *EpisodeDecorationPolicy) GetLink() bool {
	if x != nil {
		return x.Link
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetLength() bool {
	if x != nil {
		return x.Length
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetName() bool {
	if x != nil {
		return x.Name
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetManifestId() bool {
	if x != nil {
		return x.ManifestId
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetPreviewId() bool {
	if x != nil {
		return x.PreviewId
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetPreviewManifestId() bool {
	if x != nil {
		return x.PreviewManifestId
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetDescription() bool {
	if x != nil {
		return x.Description
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetPublishDate() bool {
	if x != nil {
		return x.PublishDate
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetCovers() bool {
	if x != nil {
		return x.Covers
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetFreezeFrames() bool {
	if x != nil {
		return x.FreezeFrames
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetLanguage() bool {
	if x != nil {
		return x.Language
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetMediaTypeEnum() bool {
	if x != nil {
		return x.MediaTypeEnum
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetNumber() bool {
	if x != nil {
		return x.Number
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetBackgroundable() bool {
	if x != nil {
		return x.Backgroundable
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetIsExplicit() bool {
	if x != nil {
		return x.IsExplicit
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetType() bool {
	if x != nil {
		return x.Type
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetIsMusicAndTalk() bool {
	if x != nil {
		return x.IsMusicAndTalk
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetExtension() []extendedmetadata.ExtensionKind {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *EpisodeDecorationPolicy) GetIs_19PlusOnly() bool {
	if x != nil {
		return x.Is_19PlusOnly
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetIsBookChapter() bool {
	if x != nil {
		return x.IsBookChapter
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetIsPodcastShort() bool {
	if x != nil {
		return x.IsPodcastShort
	}
	return false
}

func (x *EpisodeDecorationPolicy) GetIsCurated() bool {
	if x != nil {
		return x.IsCurated
	}
	return false
}

type EpisodeCollectionDecorationPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsFollowingShow bool                   `protobuf:"varint,1,opt,name=is_following_show,json=isFollowingShow,proto3" json:"is_following_show,omitempty"`
	IsInListenLater bool                   `protobuf:"varint,2,opt,name=is_in_listen_later,json=isInListenLater,proto3" json:"is_in_listen_later,omitempty"`
	IsNew           bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EpisodeCollectionDecorationPolicy) Reset() {
	*x = EpisodeCollectionDecorationPolicy{}
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeCollectionDecorationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeCollectionDecorationPolicy) ProtoMessage() {}

func (x *EpisodeCollectionDecorationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeCollectionDecorationPolicy.ProtoReflect.Descriptor instead.
func (*EpisodeCollectionDecorationPolicy) Descriptor() ([]byte, []int) {
	return file_policy_episode_decoration_policy_proto_rawDescGZIP(), []int{1}
}

func (x *EpisodeCollectionDecorationPolicy) GetIsFollowingShow() bool {
	if x != nil {
		return x.IsFollowingShow
	}
	return false
}

func (x *EpisodeCollectionDecorationPolicy) GetIsInListenLater() bool {
	if x != nil {
		return x.IsInListenLater
	}
	return false
}

func (x *EpisodeCollectionDecorationPolicy) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

type EpisodeSyncDecorationPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offline       bool                   `protobuf:"varint,1,opt,name=offline,proto3" json:"offline,omitempty"`
	SyncProgress  bool                   `protobuf:"varint,2,opt,name=sync_progress,json=syncProgress,proto3" json:"sync_progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeSyncDecorationPolicy) Reset() {
	*x = EpisodeSyncDecorationPolicy{}
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeSyncDecorationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeSyncDecorationPolicy) ProtoMessage() {}

func (x *EpisodeSyncDecorationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeSyncDecorationPolicy.ProtoReflect.Descriptor instead.
func (*EpisodeSyncDecorationPolicy) Descriptor() ([]byte, []int) {
	return file_policy_episode_decoration_policy_proto_rawDescGZIP(), []int{2}
}

func (x *EpisodeSyncDecorationPolicy) GetOffline() bool {
	if x != nil {
		return x.Offline
	}
	return false
}

func (x *EpisodeSyncDecorationPolicy) GetSyncProgress() bool {
	if x != nil {
		return x.SyncProgress
	}
	return false
}

type EpisodePlayedStateDecorationPolicy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TimeLeft               bool                   `protobuf:"varint,1,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	IsPlayed               bool                   `protobuf:"varint,2,opt,name=is_played,json=isPlayed,proto3" json:"is_played,omitempty"`
	Playable               bool                   `protobuf:"varint,3,opt,name=playable,proto3" json:"playable,omitempty"`
	PlayabilityRestriction bool                   `protobuf:"varint,4,opt,name=playability_restriction,json=playabilityRestriction,proto3" json:"playability_restriction,omitempty"`
	LastPlayedAt           bool                   `protobuf:"varint,5,opt,name=last_played_at,json=lastPlayedAt,proto3" json:"last_played_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EpisodePlayedStateDecorationPolicy) Reset() {
	*x = EpisodePlayedStateDecorationPolicy{}
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodePlayedStateDecorationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodePlayedStateDecorationPolicy) ProtoMessage() {}

func (x *EpisodePlayedStateDecorationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_episode_decoration_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodePlayedStateDecorationPolicy.ProtoReflect.Descriptor instead.
func (*EpisodePlayedStateDecorationPolicy) Descriptor() ([]byte, []int) {
	return file_policy_episode_decoration_policy_proto_rawDescGZIP(), []int{3}
}

func (x *EpisodePlayedStateDecorationPolicy) GetTimeLeft() bool {
	if x != nil {
		return x.TimeLeft
	}
	return false
}

func (x *EpisodePlayedStateDecorationPolicy) GetIsPlayed() bool {
	if x != nil {
		return x.IsPlayed
	}
	return false
}

func (x *EpisodePlayedStateDecorationPolicy) GetPlayable() bool {
	if x != nil {
		return x.Playable
	}
	return false
}

func (x *EpisodePlayedStateDecorationPolicy) GetPlayabilityRestriction() bool {
	if x != nil {
		return x.PlayabilityRestriction
	}
	return false
}

func (x *EpisodePlayedStateDecorationPolicy) GetLastPlayedAt() bool {
	if x != nil {
		return x.LastPlayedAt
	}
	return false
}

var File_policy_episode_decoration_policy_proto protoreflect.FileDescriptor

const file_policy_episode_decoration_policy_proto_rawDesc = "" +
	"\n" +
	"&policy/episode_decoration_policy.proto\x12\x19spotify.cosmos_util.proto\x1a\x14extension_kind.proto\"\xb8\x06\n" +
	"\x17EpisodeDecorationPolicy\x12\x12\n" +
	"\x04link\x18\x01 \x01(\bR\x04link\x12\x16\n" +
	"\x06length\x18\x02 \x01(\bR\x06length\x12\x12\n" +
	"\x04name\x18\x03 \x01(\bR\x04name\x12\x1f\n" +
	"\vmanifest_id\x18\x04 \x01(\bR\n" +
	"manifestId\x12\x1d\n" +
	"\n" +
	"preview_id\x18\x05 \x01(\bR\tpreviewId\x12.\n" +
	"\x13preview_manifest_id\x18\x06 \x01(\bR\x11previewManifestId\x12 \n" +
	"\vdescription\x18\a \x01(\bR\vdescription\x12!\n" +
	"\fpublish_date\x18\b \x01(\bR\vpublishDate\x12\x16\n" +
	"\x06covers\x18\t \x01(\bR\x06covers\x12#\n" +
	"\rfreeze_frames\x18\n" +
	" \x01(\bR\ffreezeFrames\x12\x1a\n" +
	"\blanguage\x18\v \x01(\bR\blanguage\x12\x1c\n" +
	"\tavailable\x18\f \x01(\bR\tavailable\x12&\n" +
	"\x0fmedia_type_enum\x18\r \x01(\bR\rmediaTypeEnum\x12\x16\n" +
	"\x06number\x18\x0e \x01(\bR\x06number\x12&\n" +
	"\x0ebackgroundable\x18\x0f \x01(\bR\x0ebackgroundable\x12\x1f\n" +
	"\vis_explicit\x18\x10 \x01(\bR\n" +
	"isExplicit\x12\x12\n" +
	"\x04type\x18\x11 \x01(\bR\x04type\x12)\n" +
	"\x11is_music_and_talk\x18\x12 \x01(\bR\x0eisMusicAndTalk\x12E\n" +
	"\textension\x18\x15 \x03(\x0e2'.spotify.extendedmetadata.ExtensionKindR\textension\x12%\n" +
	"\x0fis_19_plus_only\x18\x16 \x01(\bR\fis19PlusOnly\x12&\n" +
	"\x0fis_book_chapter\x18\x17 \x01(\bR\risBookChapter\x12(\n" +
	"\x10is_podcast_short\x18\x18 \x01(\bR\x0eisPodcastShort\x12\x1d\n" +
	"\n" +
	"is_curated\x18\x19 \x01(\bR\tisCuratedJ\x04\b\x13\x10\x14J\x04\b\x14\x10\x15\"\x93\x01\n" +
	"!EpisodeCollectionDecorationPolicy\x12*\n" +
	"\x11is_following_show\x18\x01 \x01(\bR\x0fisFollowingShow\x12+\n" +
	"\x12is_in_listen_later\x18\x02 \x01(\bR\x0fisInListenLater\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNew\"\\\n" +
	"\x1bEpisodeSyncDecorationPolicy\x12\x18\n" +
	"\aoffline\x18\x01 \x01(\bR\aoffline\x12#\n" +
	"\rsync_progress\x18\x02 \x01(\bR\fsyncProgress\"\xd9\x01\n" +
	"\"EpisodePlayedStateDecorationPolicy\x12\x1b\n" +
	"\ttime_left\x18\x01 \x01(\bR\btimeLeft\x12\x1b\n" +
	"\tis_played\x18\x02 \x01(\bR\bisPlayed\x12\x1a\n" +
	"\bplayable\x18\x03 \x01(\bR\bplayable\x127\n" +
	"\x17playability_restriction\x18\x04 \x01(\bR\x16playabilityRestriction\x12$\n" +
	"\x0elast_played_at\x18\x05 \x01(\bR\flastPlayedAtBk\n" +
	"$com.spotify.cosmos.util.policy.protoP\x01ZAgithub.com/pyrorhythm/libspot/api/spotify/cosmos_util;cosmos_utilb\x06proto3"

var (
	file_policy_episode_decoration_policy_proto_rawDescOnce sync.Once
	file_policy_episode_decoration_policy_proto_rawDescData []byte
)

func file_policy_episode_decoration_policy_proto_rawDescGZIP() []byte {
	file_policy_episode_decoration_policy_proto_rawDescOnce.Do(func() {
		file_policy_episode_decoration_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_episode_decoration_policy_proto_rawDesc), len(file_policy_episode_decoration_policy_proto_rawDesc)))
	})
	return file_policy_episode_decoration_policy_proto_rawDescData
}

var file_policy_episode_decoration_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_policy_episode_decoration_policy_proto_goTypes = []any{
	(*EpisodeDecorationPolicy)(nil),            // 0: spotify.cosmos_util.proto.EpisodeDecorationPolicy
	(*EpisodeCollectionDecorationPolicy)(nil),  // 1: spotify.cosmos_util.proto.EpisodeCollectionDecorationPolicy
	(*EpisodeSyncDecorationPolicy)(nil),        // 2: spotify.cosmos_util.proto.EpisodeSyncDecorationPolicy
	(*EpisodePlayedStateDecorationPolicy)(nil), // 3: spotify.cosmos_util.proto.EpisodePlayedStateDecorationPolicy
	(extendedmetadata.ExtensionKind)(0),        // 4: spotify.extendedmetadata.ExtensionKind
}
var file_policy_episode_decoration_policy_proto_depIdxs = []int32{
	4, // 0: spotify.cosmos_util.proto.EpisodeDecorationPolicy.extension:type_name -> spotify.extendedmetadata.ExtensionKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policy_episode_decoration_policy_proto_init() }
func file_policy_episode_decoration_policy_proto_init() {
	if File_policy_episode_decoration_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_episode_decoration_policy_proto_rawDesc), len(file_policy_episode_decoration_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_policy_episode_decoration_policy_proto_goTypes,
		DependencyIndexes: file_policy_episode_decoration_policy_proto_depIdxs,
		MessageInfos:      file_policy_episode_decoration_policy_proto_msgTypes,
	}.Build()
	File_policy_episode_decoration_policy_proto = out.File
	file_policy_episode_decoration_policy_proto_goTypes = nil
	file_policy_episode_decoration_policy_proto_depIdxs = nil
}
