// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: storylines.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarCdnUrl  string                 `protobuf:"bytes,3,opt,name=avatar_cdn_url,json=avatarCdnUrl,proto3" json:"avatar_cdn_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_storylines_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_storylines_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_storylines_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetAvatarCdnUrl() string {
	if x != nil {
		return x.AvatarCdnUrl
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageCdnUrl   string                 `protobuf:"bytes,2,opt,name=image_cdn_url,json=imageCdnUrl,proto3" json:"image_cdn_url,omitempty"`
	ImageWidth    int32                  `protobuf:"varint,3,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight   int32                  `protobuf:"varint,4,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_storylines_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_storylines_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_storylines_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetImageCdnUrl() string {
	if x != nil {
		return x.ImageCdnUrl
	}
	return ""
}

func (x *Card) GetImageWidth() int32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *Card) GetImageHeight() int32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

type Storyline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityUri     string                 `protobuf:"bytes,2,opt,name=entity_uri,json=entityUri,proto3" json:"entity_uri,omitempty"`
	Artist        *Artist                `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Cards         []*Card                `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storyline) Reset() {
	*x = Storyline{}
	mi := &file_storylines_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storyline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storyline) ProtoMessage() {}

func (x *Storyline) ProtoReflect() protoreflect.Message {
	mi := &file_storylines_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storyline.ProtoReflect.Descriptor instead.
func (*Storyline) Descriptor() ([]byte, []int) {
	return file_storylines_proto_rawDescGZIP(), []int{2}
}

func (x *Storyline) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Storyline) GetEntityUri() string {
	if x != nil {
		return x.EntityUri
	}
	return ""
}

func (x *Storyline) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Storyline) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_storylines_proto protoreflect.FileDescriptor

const file_storylines_proto_rawDesc = "" +
	"\n" +
	"\x10storylines.proto\x12\x15spotify.storylines.v1\"T\n" +
	"\x06Artist\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0eavatar_cdn_url\x18\x03 \x01(\tR\favatarCdnUrl\"~\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rimage_cdn_url\x18\x02 \x01(\tR\vimageCdnUrl\x12\x1f\n" +
	"\vimage_width\x18\x03 \x01(\x05R\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\x04 \x01(\x05R\vimageHeight\"\xa4\x01\n" +
	"\tStoryline\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"entity_uri\x18\x02 \x01(\tR\tentityUri\x125\n" +
	"\x06artist\x18\x03 \x01(\v2\x1d.spotify.storylines.v1.ArtistR\x06artist\x121\n" +
	"\x05cards\x18\x04 \x03(\v2\x1b.spotify.storylines.v1.CardR\x05cardsB|\n" +
	"+com.spotify.storylines.v1.extended_metadataB\x0fStorylinesProtoP\x01Z:github.com/pyrorhythm/libspot/api/spotify/storylines/v1;v1b\x06proto3"

var (
	file_storylines_proto_rawDescOnce sync.Once
	file_storylines_proto_rawDescData []byte
)

func file_storylines_proto_rawDescGZIP() []byte {
	file_storylines_proto_rawDescOnce.Do(func() {
		file_storylines_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storylines_proto_rawDesc), len(file_storylines_proto_rawDesc)))
	})
	return file_storylines_proto_rawDescData
}

var file_storylines_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_storylines_proto_goTypes = []any{
	(*Artist)(nil),    // 0: spotify.storylines.v1.Artist
	(*Card)(nil),      // 1: spotify.storylines.v1.Card
	(*Storyline)(nil), // 2: spotify.storylines.v1.Storyline
}
var file_storylines_proto_depIdxs = []int32{
	0, // 0: spotify.storylines.v1.Storyline.artist:type_name -> spotify.storylines.v1.Artist
	1, // 1: spotify.storylines.v1.Storyline.cards:type_name -> spotify.storylines.v1.Card
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storylines_proto_init() }
func file_storylines_proto_init() {
	if File_storylines_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storylines_proto_rawDesc), len(file_storylines_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storylines_proto_goTypes,
		DependencyIndexes: file_storylines_proto_depIdxs,
		MessageInfos:      file_storylines_proto_msgTypes,
	}.Build()
	File_storylines_proto = out.File
	file_storylines_proto_goTypes = nil
	file_storylines_proto_depIdxs = nil
}
