// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: local_list_config.proto

package local_list_config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalListConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUri      string                 `protobuf:"bytes,2,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalListConfig) Reset() {
	*x = LocalListConfig{}
	mi := &file_local_list_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalListConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalListConfig) ProtoMessage() {}

func (x *LocalListConfig) ProtoReflect() protoreflect.Message {
	mi := &file_local_list_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalListConfig.ProtoReflect.Descriptor instead.
func (*LocalListConfig) Descriptor() ([]byte, []int) {
	return file_local_list_config_proto_rawDescGZIP(), []int{0}
}

func (x *LocalListConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalListConfig) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *LocalListConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_local_list_config_proto protoreflect.FileDescriptor

const file_local_list_config_proto_rawDesc = "" +
	"\n" +
	"\x17local_list_config.proto\x12(spotify.playlist.local_list_config.proto\"d\n" +
	"\x0fLocalListConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_uri\x18\x02 \x01(\tR\bimageUri\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionBXZVgithub.com/pyrorhythm/libspot/api/spotify/playlist/local_list_config;local_list_configb\x06proto3"

var (
	file_local_list_config_proto_rawDescOnce sync.Once
	file_local_list_config_proto_rawDescData []byte
)

func file_local_list_config_proto_rawDescGZIP() []byte {
	file_local_list_config_proto_rawDescOnce.Do(func() {
		file_local_list_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_local_list_config_proto_rawDesc), len(file_local_list_config_proto_rawDesc)))
	})
	return file_local_list_config_proto_rawDescData
}

var file_local_list_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_local_list_config_proto_goTypes = []any{
	(*LocalListConfig)(nil), // 0: spotify.playlist.local_list_config.proto.LocalListConfig
}
var file_local_list_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_local_list_config_proto_init() }
func file_local_list_config_proto_init() {
	if File_local_list_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_local_list_config_proto_rawDesc), len(file_local_list_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_local_list_config_proto_goTypes,
		DependencyIndexes: file_local_list_config_proto_depIdxs,
		MessageInfos:      file_local_list_config_proto_msgTypes,
	}.Build()
	File_local_list_config_proto = out.File
	file_local_list_config_proto_goTypes = nil
	file_local_list_config_proto_depIdxs = nil
}
