// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mix_audio_attributes_v2.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioAttributes_Key_Mode int32

const (
	AudioAttributes_Key_MODE_UNKNOWN AudioAttributes_Key_Mode = 0
	AudioAttributes_Key_MODE_MINOR   AudioAttributes_Key_Mode = 1
	AudioAttributes_Key_MODE_MAJOR   AudioAttributes_Key_Mode = 2
)

// Enum value maps for AudioAttributes_Key_Mode.
var (
	AudioAttributes_Key_Mode_name = map[int32]string{
		0: "MODE_UNKNOWN",
		1: "MODE_MINOR",
		2: "MODE_MAJOR",
	}
	AudioAttributes_Key_Mode_value = map[string]int32{
		"MODE_UNKNOWN": 0,
		"MODE_MINOR":   1,
		"MODE_MAJOR":   2,
	}
)

func (x AudioAttributes_Key_Mode) Enum() *AudioAttributes_Key_Mode {
	p := new(AudioAttributes_Key_Mode)
	*p = x
	return p
}

func (x AudioAttributes_Key_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioAttributes_Key_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_mix_audio_attributes_v2_proto_enumTypes[0].Descriptor()
}

func (AudioAttributes_Key_Mode) Type() protoreflect.EnumType {
	return &file_mix_audio_attributes_v2_proto_enumTypes[0]
}

func (x AudioAttributes_Key_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioAttributes_Key_Mode.Descriptor instead.
func (AudioAttributes_Key_Mode) EnumDescriptor() ([]byte, []int) {
	return file_mix_audio_attributes_v2_proto_rawDescGZIP(), []int{0, 0, 0}
}

type AudioAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bpm           float64                `protobuf:"fixed64,1,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Key           *AudioAttributes_Key   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioAttributes) Reset() {
	*x = AudioAttributes{}
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioAttributes) ProtoMessage() {}

func (x *AudioAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioAttributes.ProtoReflect.Descriptor instead.
func (*AudioAttributes) Descriptor() ([]byte, []int) {
	return file_mix_audio_attributes_v2_proto_rawDescGZIP(), []int{0}
}

func (x *AudioAttributes) GetBpm() float64 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *AudioAttributes) GetKey() *AudioAttributes_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type AudioAttributes_Key struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Key           string                          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Mode          AudioAttributes_Key_Mode        `protobuf:"varint,2,opt,name=mode,proto3,enum=spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes_Key_Mode" json:"mode,omitempty"`
	CamelotKey    *AudioAttributes_Key_CamelotKey `protobuf:"bytes,3,opt,name=camelot_key,json=camelotKey,proto3" json:"camelot_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioAttributes_Key) Reset() {
	*x = AudioAttributes_Key{}
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioAttributes_Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioAttributes_Key) ProtoMessage() {}

func (x *AudioAttributes_Key) ProtoReflect() protoreflect.Message {
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioAttributes_Key.ProtoReflect.Descriptor instead.
func (*AudioAttributes_Key) Descriptor() ([]byte, []int) {
	return file_mix_audio_attributes_v2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AudioAttributes_Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AudioAttributes_Key) GetMode() AudioAttributes_Key_Mode {
	if x != nil {
		return x.Mode
	}
	return AudioAttributes_Key_MODE_UNKNOWN
}

func (x *AudioAttributes_Key) GetCamelotKey() *AudioAttributes_Key_CamelotKey {
	if x != nil {
		return x.CamelotKey
	}
	return nil
}

type AudioAttributes_Key_CamelotKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioAttributes_Key_CamelotKey) Reset() {
	*x = AudioAttributes_Key_CamelotKey{}
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioAttributes_Key_CamelotKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioAttributes_Key_CamelotKey) ProtoMessage() {}

func (x *AudioAttributes_Key_CamelotKey) ProtoReflect() protoreflect.Message {
	mi := &file_mix_audio_attributes_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioAttributes_Key_CamelotKey.ProtoReflect.Descriptor instead.
func (*AudioAttributes_Key_CamelotKey) Descriptor() ([]byte, []int) {
	return file_mix_audio_attributes_v2_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AudioAttributes_Key_CamelotKey) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AudioAttributes_Key_CamelotKey) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_mix_audio_attributes_v2_proto protoreflect.FileDescriptor

const file_mix_audio_attributes_v2_proto_rawDesc = "" +
	"\n" +
	"\x1dmix_audio_attributes_v2.proto\x125spotify.playlistmixing.extensions.audio_attributes.v2\"\xec\x03\n" +
	"\x0fAudioAttributes\x12\x10\n" +
	"\x03bpm\x18\x01 \x01(\x01R\x03bpm\x12\\\n" +
	"\x03key\x18\x02 \x01(\v2J.spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.KeyR\x03key\x1a\xe8\x02\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12c\n" +
	"\x04mode\x18\x02 \x01(\x0e2O.spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.ModeR\x04mode\x12v\n" +
	"\vcamelot_key\x18\x03 \x01(\v2U.spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.CamelotKeyR\n" +
	"camelotKey\x1a8\n" +
	"\n" +
	"CamelotKey\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\"8\n" +
	"\x04Mode\x12\x10\n" +
	"\fMODE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"MODE_MINOR\x10\x01\x12\x0e\n" +
	"\n" +
	"MODE_MAJOR\x10\x02B\x9d\x01\n" +
	"?com.spotify.playlistmixing.extensions.audio_attributes.v2.protoZZgithub.com/pyrorhythm/libspot/api/spotify/playlistmixing/extensions/audio_attributes/v2;v2b\x06proto3"

var (
	file_mix_audio_attributes_v2_proto_rawDescOnce sync.Once
	file_mix_audio_attributes_v2_proto_rawDescData []byte
)

func file_mix_audio_attributes_v2_proto_rawDescGZIP() []byte {
	file_mix_audio_attributes_v2_proto_rawDescOnce.Do(func() {
		file_mix_audio_attributes_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mix_audio_attributes_v2_proto_rawDesc), len(file_mix_audio_attributes_v2_proto_rawDesc)))
	})
	return file_mix_audio_attributes_v2_proto_rawDescData
}

var file_mix_audio_attributes_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mix_audio_attributes_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mix_audio_attributes_v2_proto_goTypes = []any{
	(AudioAttributes_Key_Mode)(0),          // 0: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.Mode
	(*AudioAttributes)(nil),                // 1: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes
	(*AudioAttributes_Key)(nil),            // 2: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key
	(*AudioAttributes_Key_CamelotKey)(nil), // 3: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.CamelotKey
}
var file_mix_audio_attributes_v2_proto_depIdxs = []int32{
	2, // 0: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.key:type_name -> spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key
	0, // 1: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.mode:type_name -> spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.Mode
	3, // 2: spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.camelot_key:type_name -> spotify.playlistmixing.extensions.audio_attributes.v2.AudioAttributes.Key.CamelotKey
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mix_audio_attributes_v2_proto_init() }
func file_mix_audio_attributes_v2_proto_init() {
	if File_mix_audio_attributes_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mix_audio_attributes_v2_proto_rawDesc), len(file_mix_audio_attributes_v2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mix_audio_attributes_v2_proto_goTypes,
		DependencyIndexes: file_mix_audio_attributes_v2_proto_depIdxs,
		EnumInfos:         file_mix_audio_attributes_v2_proto_enumTypes,
		MessageInfos:      file_mix_audio_attributes_v2_proto_msgTypes,
	}.Build()
	File_mix_audio_attributes_v2_proto = out.File
	file_mix_audio_attributes_v2_proto_goTypes = nil
	file_mix_audio_attributes_v2_proto_depIdxs = nil
}
