// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: your_library_decorated_entity.proto

package your_library

import (
	cosmos "github.com/pyrorhythm/libspot/api/spotify/playlist/cosmos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YourLibraryEntityInfo_Pinnable int32

const (
	YourLibraryEntityInfo_YES            YourLibraryEntityInfo_Pinnable = 0
	YourLibraryEntityInfo_NO_IN_FOLDER   YourLibraryEntityInfo_Pinnable = 1
	YourLibraryEntityInfo_NOT_VALID_TYPE YourLibraryEntityInfo_Pinnable = 2
)

// Enum value maps for YourLibraryEntityInfo_Pinnable.
var (
	YourLibraryEntityInfo_Pinnable_name = map[int32]string{
		0: "YES",
		1: "NO_IN_FOLDER",
		2: "NOT_VALID_TYPE",
	}
	YourLibraryEntityInfo_Pinnable_value = map[string]int32{
		"YES":            0,
		"NO_IN_FOLDER":   1,
		"NOT_VALID_TYPE": 2,
	}
)

func (x YourLibraryEntityInfo_Pinnable) Enum() *YourLibraryEntityInfo_Pinnable {
	p := new(YourLibraryEntityInfo_Pinnable)
	*p = x
	return p
}

func (x YourLibraryEntityInfo_Pinnable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryEntityInfo_Pinnable) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[0].Descriptor()
}

func (YourLibraryEntityInfo_Pinnable) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[0]
}

func (x YourLibraryEntityInfo_Pinnable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryEntityInfo_Pinnable.Descriptor instead.
func (YourLibraryEntityInfo_Pinnable) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{0, 0}
}

type Offline_Availability int32

const (
	Offline_UNKNOWN     Offline_Availability = 0
	Offline_NO          Offline_Availability = 1
	Offline_YES         Offline_Availability = 2
	Offline_DOWNLOADING Offline_Availability = 3
	Offline_WAITING     Offline_Availability = 4
)

// Enum value maps for Offline_Availability.
var (
	Offline_Availability_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO",
		2: "YES",
		3: "DOWNLOADING",
		4: "WAITING",
	}
	Offline_Availability_value = map[string]int32{
		"UNKNOWN":     0,
		"NO":          1,
		"YES":         2,
		"DOWNLOADING": 3,
		"WAITING":     4,
	}
)

func (x Offline_Availability) Enum() *Offline_Availability {
	p := new(Offline_Availability)
	*p = x
	return p
}

func (x Offline_Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Offline_Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[1].Descriptor()
}

func (Offline_Availability) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[1]
}

func (x Offline_Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Offline_Availability.Descriptor instead.
func (Offline_Availability) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{1, 0}
}

type YourLibraryAlbumExtraInfo_Type int32

const (
	YourLibraryAlbumExtraInfo_ALBUM       YourLibraryAlbumExtraInfo_Type = 0
	YourLibraryAlbumExtraInfo_SINGLE      YourLibraryAlbumExtraInfo_Type = 1
	YourLibraryAlbumExtraInfo_COMPILATION YourLibraryAlbumExtraInfo_Type = 2
	YourLibraryAlbumExtraInfo_EP          YourLibraryAlbumExtraInfo_Type = 3
)

// Enum value maps for YourLibraryAlbumExtraInfo_Type.
var (
	YourLibraryAlbumExtraInfo_Type_name = map[int32]string{
		0: "ALBUM",
		1: "SINGLE",
		2: "COMPILATION",
		3: "EP",
	}
	YourLibraryAlbumExtraInfo_Type_value = map[string]int32{
		"ALBUM":       0,
		"SINGLE":      1,
		"COMPILATION": 2,
		"EP":          3,
	}
)

func (x YourLibraryAlbumExtraInfo_Type) Enum() *YourLibraryAlbumExtraInfo_Type {
	p := new(YourLibraryAlbumExtraInfo_Type)
	*p = x
	return p
}

func (x YourLibraryAlbumExtraInfo_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryAlbumExtraInfo_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[2].Descriptor()
}

func (YourLibraryAlbumExtraInfo_Type) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[2]
}

func (x YourLibraryAlbumExtraInfo_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryAlbumExtraInfo_Type.Descriptor instead.
func (YourLibraryAlbumExtraInfo_Type) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{2, 0}
}

type YourLibraryPlaylistExtraInfo_GenerationStatus int32

const (
	YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_UNKNOWN    YourLibraryPlaylistExtraInfo_GenerationStatus = 0
	YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_SUCCESS    YourLibraryPlaylistExtraInfo_GenerationStatus = 1
	YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_QUEUED     YourLibraryPlaylistExtraInfo_GenerationStatus = 2
	YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_PROCESSING YourLibraryPlaylistExtraInfo_GenerationStatus = 3
	YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_ERROR      YourLibraryPlaylistExtraInfo_GenerationStatus = 4
)

// Enum value maps for YourLibraryPlaylistExtraInfo_GenerationStatus.
var (
	YourLibraryPlaylistExtraInfo_GenerationStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNKNOWN",
		1: "MESSAGE_STATUS_SUCCESS",
		2: "MESSAGE_STATUS_QUEUED",
		3: "MESSAGE_STATUS_PROCESSING",
		4: "MESSAGE_STATUS_ERROR",
	}
	YourLibraryPlaylistExtraInfo_GenerationStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNKNOWN":    0,
		"MESSAGE_STATUS_SUCCESS":    1,
		"MESSAGE_STATUS_QUEUED":     2,
		"MESSAGE_STATUS_PROCESSING": 3,
		"MESSAGE_STATUS_ERROR":      4,
	}
)

func (x YourLibraryPlaylistExtraInfo_GenerationStatus) Enum() *YourLibraryPlaylistExtraInfo_GenerationStatus {
	p := new(YourLibraryPlaylistExtraInfo_GenerationStatus)
	*p = x
	return p
}

func (x YourLibraryPlaylistExtraInfo_GenerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryPlaylistExtraInfo_GenerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[3].Descriptor()
}

func (YourLibraryPlaylistExtraInfo_GenerationStatus) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[3]
}

func (x YourLibraryPlaylistExtraInfo_GenerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryPlaylistExtraInfo_GenerationStatus.Descriptor instead.
func (YourLibraryPlaylistExtraInfo_GenerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{6, 0}
}

type YourLibraryBookExtraInfo_Access int32

const (
	YourLibraryBookExtraInfo_OPEN   YourLibraryBookExtraInfo_Access = 0
	YourLibraryBookExtraInfo_LOCKED YourLibraryBookExtraInfo_Access = 1
	YourLibraryBookExtraInfo_CAPPED YourLibraryBookExtraInfo_Access = 2
)

// Enum value maps for YourLibraryBookExtraInfo_Access.
var (
	YourLibraryBookExtraInfo_Access_name = map[int32]string{
		0: "OPEN",
		1: "LOCKED",
		2: "CAPPED",
	}
	YourLibraryBookExtraInfo_Access_value = map[string]int32{
		"OPEN":   0,
		"LOCKED": 1,
		"CAPPED": 2,
	}
)

func (x YourLibraryBookExtraInfo_Access) Enum() *YourLibraryBookExtraInfo_Access {
	p := new(YourLibraryBookExtraInfo_Access)
	*p = x
	return p
}

func (x YourLibraryBookExtraInfo_Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryBookExtraInfo_Access) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[4].Descriptor()
}

func (YourLibraryBookExtraInfo_Access) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[4]
}

func (x YourLibraryBookExtraInfo_Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryBookExtraInfo_Access.Descriptor instead.
func (YourLibraryBookExtraInfo_Access) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{12, 0}
}

type YourLibraryBookExtraInfo_State int32

const (
	YourLibraryBookExtraInfo_NOT_STARTED YourLibraryBookExtraInfo_State = 0
	YourLibraryBookExtraInfo_IN_PROGRESS YourLibraryBookExtraInfo_State = 1
	YourLibraryBookExtraInfo_FINISHED    YourLibraryBookExtraInfo_State = 2
)

// Enum value maps for YourLibraryBookExtraInfo_State.
var (
	YourLibraryBookExtraInfo_State_name = map[int32]string{
		0: "NOT_STARTED",
		1: "IN_PROGRESS",
		2: "FINISHED",
	}
	YourLibraryBookExtraInfo_State_value = map[string]int32{
		"NOT_STARTED": 0,
		"IN_PROGRESS": 1,
		"FINISHED":    2,
	}
)

func (x YourLibraryBookExtraInfo_State) Enum() *YourLibraryBookExtraInfo_State {
	p := new(YourLibraryBookExtraInfo_State)
	*p = x
	return p
}

func (x YourLibraryBookExtraInfo_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryBookExtraInfo_State) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[5].Descriptor()
}

func (YourLibraryBookExtraInfo_State) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[5]
}

func (x YourLibraryBookExtraInfo_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryBookExtraInfo_State.Descriptor instead.
func (YourLibraryBookExtraInfo_State) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{12, 1}
}

type YourLibraryPreReleaseExtraInfo_Type int32

const (
	YourLibraryPreReleaseExtraInfo_ALBUM YourLibraryPreReleaseExtraInfo_Type = 0
	YourLibraryPreReleaseExtraInfo_BOOK  YourLibraryPreReleaseExtraInfo_Type = 1
)

// Enum value maps for YourLibraryPreReleaseExtraInfo_Type.
var (
	YourLibraryPreReleaseExtraInfo_Type_name = map[int32]string{
		0: "ALBUM",
		1: "BOOK",
	}
	YourLibraryPreReleaseExtraInfo_Type_value = map[string]int32{
		"ALBUM": 0,
		"BOOK":  1,
	}
)

func (x YourLibraryPreReleaseExtraInfo_Type) Enum() *YourLibraryPreReleaseExtraInfo_Type {
	p := new(YourLibraryPreReleaseExtraInfo_Type)
	*p = x
	return p
}

func (x YourLibraryPreReleaseExtraInfo_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryPreReleaseExtraInfo_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[6].Descriptor()
}

func (YourLibraryPreReleaseExtraInfo_Type) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[6]
}

func (x YourLibraryPreReleaseExtraInfo_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryPreReleaseExtraInfo_Type.Descriptor instead.
func (YourLibraryPreReleaseExtraInfo_Type) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{14, 0}
}

type YourLibraryConcertCampaignExtraInfo_Status int32

const (
	YourLibraryConcertCampaignExtraInfo_UNSPECIFIED YourLibraryConcertCampaignExtraInfo_Status = 0
	YourLibraryConcertCampaignExtraInfo_RESERVED    YourLibraryConcertCampaignExtraInfo_Status = 1
	YourLibraryConcertCampaignExtraInfo_FCFS        YourLibraryConcertCampaignExtraInfo_Status = 2
	YourLibraryConcertCampaignExtraInfo_WAITLISTED  YourLibraryConcertCampaignExtraInfo_Status = 3
	YourLibraryConcertCampaignExtraInfo_PURCHASED   YourLibraryConcertCampaignExtraInfo_Status = 4
	YourLibraryConcertCampaignExtraInfo_INELIGIBLE  YourLibraryConcertCampaignExtraInfo_Status = 5
	YourLibraryConcertCampaignExtraInfo_SOLD_OUT    YourLibraryConcertCampaignExtraInfo_Status = 6
	YourLibraryConcertCampaignExtraInfo_CANCELLED   YourLibraryConcertCampaignExtraInfo_Status = 7
	YourLibraryConcertCampaignExtraInfo_SALE_ENDED  YourLibraryConcertCampaignExtraInfo_Status = 8
)

// Enum value maps for YourLibraryConcertCampaignExtraInfo_Status.
var (
	YourLibraryConcertCampaignExtraInfo_Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "RESERVED",
		2: "FCFS",
		3: "WAITLISTED",
		4: "PURCHASED",
		5: "INELIGIBLE",
		6: "SOLD_OUT",
		7: "CANCELLED",
		8: "SALE_ENDED",
	}
	YourLibraryConcertCampaignExtraInfo_Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"RESERVED":    1,
		"FCFS":        2,
		"WAITLISTED":  3,
		"PURCHASED":   4,
		"INELIGIBLE":  5,
		"SOLD_OUT":    6,
		"CANCELLED":   7,
		"SALE_ENDED":  8,
	}
)

func (x YourLibraryConcertCampaignExtraInfo_Status) Enum() *YourLibraryConcertCampaignExtraInfo_Status {
	p := new(YourLibraryConcertCampaignExtraInfo_Status)
	*p = x
	return p
}

func (x YourLibraryConcertCampaignExtraInfo_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (YourLibraryConcertCampaignExtraInfo_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_your_library_decorated_entity_proto_enumTypes[7].Descriptor()
}

func (YourLibraryConcertCampaignExtraInfo_Status) Type() protoreflect.EnumType {
	return &file_your_library_decorated_entity_proto_enumTypes[7]
}

func (x YourLibraryConcertCampaignExtraInfo_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use YourLibraryConcertCampaignExtraInfo_Status.Descriptor instead.
func (YourLibraryConcertCampaignExtraInfo_Status) EnumDescriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{18, 0}
}

type YourLibraryEntityInfo struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	Name                string                         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uri                 string                         `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	GroupLabel          string                         `protobuf:"bytes,5,opt,name=group_label,json=groupLabel,proto3" json:"group_label,omitempty"`
	ImageUri            string                         `protobuf:"bytes,6,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	Pinned              bool                           `protobuf:"varint,7,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Pinnable            YourLibraryEntityInfo_Pinnable `protobuf:"varint,8,opt,name=pinnable,proto3,enum=spotify.your_library.proto.YourLibraryEntityInfo_Pinnable" json:"pinnable,omitempty"`
	OfflineAvailability Offline_Availability           `protobuf:"varint,9,opt,name=offline_availability,json=offlineAvailability,proto3,enum=spotify.your_library.proto.Offline_Availability" json:"offline_availability,omitempty"`
	AddTime             int64                          `protobuf:"varint,11,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"`
	LastPlayed          int64                          `protobuf:"varint,12,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	HasCuratedItems     bool                           `protobuf:"varint,13,opt,name=has_curated_items,json=hasCuratedItems,proto3" json:"has_curated_items,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *YourLibraryEntityInfo) Reset() {
	*x = YourLibraryEntityInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryEntityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryEntityInfo) ProtoMessage() {}

func (x *YourLibraryEntityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryEntityInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryEntityInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{0}
}

func (x *YourLibraryEntityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YourLibraryEntityInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *YourLibraryEntityInfo) GetGroupLabel() string {
	if x != nil {
		return x.GroupLabel
	}
	return ""
}

func (x *YourLibraryEntityInfo) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *YourLibraryEntityInfo) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *YourLibraryEntityInfo) GetPinnable() YourLibraryEntityInfo_Pinnable {
	if x != nil {
		return x.Pinnable
	}
	return YourLibraryEntityInfo_YES
}

func (x *YourLibraryEntityInfo) GetOfflineAvailability() Offline_Availability {
	if x != nil {
		return x.OfflineAvailability
	}
	return Offline_UNKNOWN
}

func (x *YourLibraryEntityInfo) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *YourLibraryEntityInfo) GetLastPlayed() int64 {
	if x != nil {
		return x.LastPlayed
	}
	return 0
}

func (x *YourLibraryEntityInfo) GetHasCuratedItems() bool {
	if x != nil {
		return x.HasCuratedItems
	}
	return false
}

type Offline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offline) Reset() {
	*x = Offline{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{1}
}

type YourLibraryAlbumExtraInfo struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ArtistName    string                         `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	ArtistUri     string                         `protobuf:"bytes,2,opt,name=artist_uri,json=artistUri,proto3" json:"artist_uri,omitempty"`
	Type          YourLibraryAlbumExtraInfo_Type `protobuf:"varint,3,opt,name=type,proto3,enum=spotify.your_library.proto.YourLibraryAlbumExtraInfo_Type" json:"type,omitempty"`
	IsPremiumOnly bool                           `protobuf:"varint,4,opt,name=is_premium_only,json=isPremiumOnly,proto3" json:"is_premium_only,omitempty"`
	NewRelease    bool                           `protobuf:"varint,5,opt,name=new_release,json=newRelease,proto3" json:"new_release,omitempty"`
	ReleaseDate   int64                          `protobuf:"varint,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryAlbumExtraInfo) Reset() {
	*x = YourLibraryAlbumExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryAlbumExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryAlbumExtraInfo) ProtoMessage() {}

func (x *YourLibraryAlbumExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryAlbumExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryAlbumExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{2}
}

func (x *YourLibraryAlbumExtraInfo) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *YourLibraryAlbumExtraInfo) GetArtistUri() string {
	if x != nil {
		return x.ArtistUri
	}
	return ""
}

func (x *YourLibraryAlbumExtraInfo) GetType() YourLibraryAlbumExtraInfo_Type {
	if x != nil {
		return x.Type
	}
	return YourLibraryAlbumExtraInfo_ALBUM
}

func (x *YourLibraryAlbumExtraInfo) GetIsPremiumOnly() bool {
	if x != nil {
		return x.IsPremiumOnly
	}
	return false
}

func (x *YourLibraryAlbumExtraInfo) GetNewRelease() bool {
	if x != nil {
		return x.NewRelease
	}
	return false
}

func (x *YourLibraryAlbumExtraInfo) GetReleaseDate() int64 {
	if x != nil {
		return x.ReleaseDate
	}
	return 0
}

type YourLibraryArtistExtraInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	HasLikedTracksOrAlbums bool                   `protobuf:"varint,1,opt,name=has_liked_tracks_or_albums,json=hasLikedTracksOrAlbums,proto3" json:"has_liked_tracks_or_albums,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *YourLibraryArtistExtraInfo) Reset() {
	*x = YourLibraryArtistExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryArtistExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryArtistExtraInfo) ProtoMessage() {}

func (x *YourLibraryArtistExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryArtistExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryArtistExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{3}
}

func (x *YourLibraryArtistExtraInfo) GetHasLikedTracksOrAlbums() bool {
	if x != nil {
		return x.HasLikedTracksOrAlbums
	}
	return false
}

type NumberOfItemsForLinkType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkType      cosmos.LinkType        `protobuf:"varint,1,opt,name=link_type,json=linkType,proto3,enum=spotify.playlist.cosmos.proto.LinkType" json:"link_type,omitempty"`
	NumItems      int32                  `protobuf:"varint,2,opt,name=num_items,json=numItems,proto3" json:"num_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberOfItemsForLinkType) Reset() {
	*x = NumberOfItemsForLinkType{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberOfItemsForLinkType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberOfItemsForLinkType) ProtoMessage() {}

func (x *NumberOfItemsForLinkType) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberOfItemsForLinkType.ProtoReflect.Descriptor instead.
func (*NumberOfItemsForLinkType) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{4}
}

func (x *NumberOfItemsForLinkType) GetLinkType() cosmos.LinkType {
	if x != nil {
		return x.LinkType
	}
	return cosmos.LinkType(0)
}

func (x *NumberOfItemsForLinkType) GetNumItems() int32 {
	if x != nil {
		return x.NumItems
	}
	return 0
}

type YourLibraryPlaylistFolderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryPlaylistFolderInfo) Reset() {
	*x = YourLibraryPlaylistFolderInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryPlaylistFolderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryPlaylistFolderInfo) ProtoMessage() {}

func (x *YourLibraryPlaylistFolderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryPlaylistFolderInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryPlaylistFolderInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{5}
}

func (x *YourLibraryPlaylistFolderInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *YourLibraryPlaylistFolderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type YourLibraryPlaylistExtraInfo struct {
	state                    protoimpl.MessageState                        `protogen:"open.v1"`
	CreatorName              string                                        `protobuf:"bytes,1,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	CreatorUri               string                                        `protobuf:"bytes,8,opt,name=creator_uri,json=creatorUri,proto3" json:"creator_uri,omitempty"`
	IsLoading                bool                                          `protobuf:"varint,5,opt,name=is_loading,json=isLoading,proto3" json:"is_loading,omitempty"`
	CanView                  bool                                          `protobuf:"varint,6,opt,name=can_view,json=canView,proto3" json:"can_view,omitempty"`
	CanAdd                   bool                                          `protobuf:"varint,9,opt,name=can_add,json=canAdd,proto3" json:"can_add,omitempty"`
	RowId                    string                                        `protobuf:"bytes,7,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	MadeForName              string                                        `protobuf:"bytes,10,opt,name=made_for_name,json=madeForName,proto3" json:"made_for_name,omitempty"`
	MadeForUri               string                                        `protobuf:"bytes,11,opt,name=made_for_uri,json=madeForUri,proto3" json:"made_for_uri,omitempty"`
	NumberOfItemsPerLinkType []*NumberOfItemsForLinkType                   `protobuf:"bytes,12,rep,name=number_of_items_per_link_type,json=numberOfItemsPerLinkType,proto3" json:"number_of_items_per_link_type,omitempty"`
	OwnedBySelf              bool                                          `protobuf:"varint,13,opt,name=owned_by_self,json=ownedBySelf,proto3" json:"owned_by_self,omitempty"`
	FromFolder               *YourLibraryPlaylistFolderInfo                `protobuf:"bytes,14,opt,name=from_folder,json=fromFolder,proto3" json:"from_folder,omitempty"`
	NamePrefix               string                                        `protobuf:"bytes,15,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	MixingActive             bool                                          `protobuf:"varint,16,opt,name=mixing_active,json=mixingActive,proto3" json:"mixing_active,omitempty"`
	IsEmptyPredefined        bool                                          `protobuf:"varint,17,opt,name=is_empty_predefined,json=isEmptyPredefined,proto3" json:"is_empty_predefined,omitempty"`
	PromptGenerationStatus   YourLibraryPlaylistExtraInfo_GenerationStatus `protobuf:"varint,18,opt,name=prompt_generation_status,json=promptGenerationStatus,proto3,enum=spotify.your_library.proto.YourLibraryPlaylistExtraInfo_GenerationStatus" json:"prompt_generation_status,omitempty"`
	PromptIsPersonalized     bool                                          `protobuf:"varint,19,opt,name=prompt_is_personalized,json=promptIsPersonalized,proto3" json:"prompt_is_personalized,omitempty"`
	IsPromptPlaylist         bool                                          `protobuf:"varint,20,opt,name=is_prompt_playlist,json=isPromptPlaylist,proto3" json:"is_prompt_playlist,omitempty"`
	IsPublished              bool                                          `protobuf:"varint,21,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	IsPrivate                bool                                          `protobuf:"varint,22,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *YourLibraryPlaylistExtraInfo) Reset() {
	*x = YourLibraryPlaylistExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryPlaylistExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryPlaylistExtraInfo) ProtoMessage() {}

func (x *YourLibraryPlaylistExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryPlaylistExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryPlaylistExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{6}
}

func (x *YourLibraryPlaylistExtraInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetCreatorUri() string {
	if x != nil {
		return x.CreatorUri
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetIsLoading() bool {
	if x != nil {
		return x.IsLoading
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetCanView() bool {
	if x != nil {
		return x.CanView
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetCanAdd() bool {
	if x != nil {
		return x.CanAdd
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetRowId() string {
	if x != nil {
		return x.RowId
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetMadeForName() string {
	if x != nil {
		return x.MadeForName
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetMadeForUri() string {
	if x != nil {
		return x.MadeForUri
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetNumberOfItemsPerLinkType() []*NumberOfItemsForLinkType {
	if x != nil {
		return x.NumberOfItemsPerLinkType
	}
	return nil
}

func (x *YourLibraryPlaylistExtraInfo) GetOwnedBySelf() bool {
	if x != nil {
		return x.OwnedBySelf
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetFromFolder() *YourLibraryPlaylistFolderInfo {
	if x != nil {
		return x.FromFolder
	}
	return nil
}

func (x *YourLibraryPlaylistExtraInfo) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

func (x *YourLibraryPlaylistExtraInfo) GetMixingActive() bool {
	if x != nil {
		return x.MixingActive
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetIsEmptyPredefined() bool {
	if x != nil {
		return x.IsEmptyPredefined
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetPromptGenerationStatus() YourLibraryPlaylistExtraInfo_GenerationStatus {
	if x != nil {
		return x.PromptGenerationStatus
	}
	return YourLibraryPlaylistExtraInfo_MESSAGE_STATUS_UNKNOWN
}

func (x *YourLibraryPlaylistExtraInfo) GetPromptIsPersonalized() bool {
	if x != nil {
		return x.PromptIsPersonalized
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetIsPromptPlaylist() bool {
	if x != nil {
		return x.IsPromptPlaylist
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *YourLibraryPlaylistExtraInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type YourLibraryShowExtraInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	CreatorName                string                 `protobuf:"bytes,1,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	PublishDate                int64                  `protobuf:"varint,4,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	NumberOfDownloadedEpisodes int32                  `protobuf:"varint,6,opt,name=number_of_downloaded_episodes,json=numberOfDownloadedEpisodes,proto3" json:"number_of_downloaded_episodes,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *YourLibraryShowExtraInfo) Reset() {
	*x = YourLibraryShowExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryShowExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryShowExtraInfo) ProtoMessage() {}

func (x *YourLibraryShowExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryShowExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryShowExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{7}
}

func (x *YourLibraryShowExtraInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *YourLibraryShowExtraInfo) GetPublishDate() int64 {
	if x != nil {
		return x.PublishDate
	}
	return 0
}

func (x *YourLibraryShowExtraInfo) GetNumberOfDownloadedEpisodes() int32 {
	if x != nil {
		return x.NumberOfDownloadedEpisodes
	}
	return 0
}

type YourLibraryFolderExtraInfo struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	NumberOfPlaylists int32                         `protobuf:"varint,2,opt,name=number_of_playlists,json=numberOfPlaylists,proto3" json:"number_of_playlists,omitempty"`
	NumberOfFolders   int32                         `protobuf:"varint,3,opt,name=number_of_folders,json=numberOfFolders,proto3" json:"number_of_folders,omitempty"`
	RowId             string                        `protobuf:"bytes,4,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	Entity            []*YourLibraryDecoratedEntity `protobuf:"bytes,5,rep,name=entity,proto3" json:"entity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YourLibraryFolderExtraInfo) Reset() {
	*x = YourLibraryFolderExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryFolderExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryFolderExtraInfo) ProtoMessage() {}

func (x *YourLibraryFolderExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryFolderExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryFolderExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{8}
}

func (x *YourLibraryFolderExtraInfo) GetNumberOfPlaylists() int32 {
	if x != nil {
		return x.NumberOfPlaylists
	}
	return 0
}

func (x *YourLibraryFolderExtraInfo) GetNumberOfFolders() int32 {
	if x != nil {
		return x.NumberOfFolders
	}
	return 0
}

func (x *YourLibraryFolderExtraInfo) GetRowId() string {
	if x != nil {
		return x.RowId
	}
	return ""
}

func (x *YourLibraryFolderExtraInfo) GetEntity() []*YourLibraryDecoratedEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type YourLibraryLikedSongsExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfSongs int32                  `protobuf:"varint,3,opt,name=number_of_songs,json=numberOfSongs,proto3" json:"number_of_songs,omitempty"`
	IsEmpty       bool                   `protobuf:"varint,4,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryLikedSongsExtraInfo) Reset() {
	*x = YourLibraryLikedSongsExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryLikedSongsExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryLikedSongsExtraInfo) ProtoMessage() {}

func (x *YourLibraryLikedSongsExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryLikedSongsExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryLikedSongsExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{9}
}

func (x *YourLibraryLikedSongsExtraInfo) GetNumberOfSongs() int32 {
	if x != nil {
		return x.NumberOfSongs
	}
	return 0
}

func (x *YourLibraryLikedSongsExtraInfo) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

type YourLibraryNewEpisodesExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishDate   int64                  `protobuf:"varint,1,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryNewEpisodesExtraInfo) Reset() {
	*x = YourLibraryNewEpisodesExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryNewEpisodesExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryNewEpisodesExtraInfo) ProtoMessage() {}

func (x *YourLibraryNewEpisodesExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryNewEpisodesExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryNewEpisodesExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{10}
}

func (x *YourLibraryNewEpisodesExtraInfo) GetPublishDate() int64 {
	if x != nil {
		return x.PublishDate
	}
	return 0
}

type YourLibraryLocalFilesExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfFiles int32                  `protobuf:"varint,1,opt,name=number_of_files,json=numberOfFiles,proto3" json:"number_of_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryLocalFilesExtraInfo) Reset() {
	*x = YourLibraryLocalFilesExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryLocalFilesExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryLocalFilesExtraInfo) ProtoMessage() {}

func (x *YourLibraryLocalFilesExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryLocalFilesExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryLocalFilesExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{11}
}

func (x *YourLibraryLocalFilesExtraInfo) GetNumberOfFiles() int32 {
	if x != nil {
		return x.NumberOfFiles
	}
	return 0
}

type YourLibraryBookExtraInfo struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	AuthorName       string                          `protobuf:"bytes,1,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	Access           YourLibraryBookExtraInfo_Access `protobuf:"varint,2,opt,name=access,proto3,enum=spotify.your_library.proto.YourLibraryBookExtraInfo_Access" json:"access,omitempty"`
	MillisecondsLeft int64                           `protobuf:"varint,3,opt,name=milliseconds_left,json=millisecondsLeft,proto3" json:"milliseconds_left,omitempty"`
	PercentDone      int32                           `protobuf:"varint,4,opt,name=percent_done,json=percentDone,proto3" json:"percent_done,omitempty"`
	State            YourLibraryBookExtraInfo_State  `protobuf:"varint,5,opt,name=state,proto3,enum=spotify.your_library.proto.YourLibraryBookExtraInfo_State" json:"state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *YourLibraryBookExtraInfo) Reset() {
	*x = YourLibraryBookExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryBookExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryBookExtraInfo) ProtoMessage() {}

func (x *YourLibraryBookExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryBookExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryBookExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{12}
}

func (x *YourLibraryBookExtraInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *YourLibraryBookExtraInfo) GetAccess() YourLibraryBookExtraInfo_Access {
	if x != nil {
		return x.Access
	}
	return YourLibraryBookExtraInfo_OPEN
}

func (x *YourLibraryBookExtraInfo) GetMillisecondsLeft() int64 {
	if x != nil {
		return x.MillisecondsLeft
	}
	return 0
}

func (x *YourLibraryBookExtraInfo) GetPercentDone() int32 {
	if x != nil {
		return x.PercentDone
	}
	return 0
}

func (x *YourLibraryBookExtraInfo) GetState() YourLibraryBookExtraInfo_State {
	if x != nil {
		return x.State
	}
	return YourLibraryBookExtraInfo_NOT_STARTED
}

type YourLibraryCachedFilesExtraInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NumberOfItems     int32                  `protobuf:"varint,1,opt,name=number_of_items,json=numberOfItems,proto3" json:"number_of_items,omitempty"`
	DurationInSeconds int32                  `protobuf:"varint,2,opt,name=duration_in_seconds,json=durationInSeconds,proto3" json:"duration_in_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YourLibraryCachedFilesExtraInfo) Reset() {
	*x = YourLibraryCachedFilesExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryCachedFilesExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryCachedFilesExtraInfo) ProtoMessage() {}

func (x *YourLibraryCachedFilesExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryCachedFilesExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryCachedFilesExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{13}
}

func (x *YourLibraryCachedFilesExtraInfo) GetNumberOfItems() int32 {
	if x != nil {
		return x.NumberOfItems
	}
	return 0
}

func (x *YourLibraryCachedFilesExtraInfo) GetDurationInSeconds() int32 {
	if x != nil {
		return x.DurationInSeconds
	}
	return 0
}

type YourLibraryPreReleaseExtraInfo struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	ArtistName    string                              `protobuf:"bytes,1,opt,name=artist_name,json=artistName,proto3" json:"artist_name,omitempty"`
	ArtistUri     string                              `protobuf:"bytes,2,opt,name=artist_uri,json=artistUri,proto3" json:"artist_uri,omitempty"`
	Type          YourLibraryPreReleaseExtraInfo_Type `protobuf:"varint,3,opt,name=type,proto3,enum=spotify.your_library.proto.YourLibraryPreReleaseExtraInfo_Type" json:"type,omitempty"`
	AlbumType     YourLibraryAlbumExtraInfo_Type      `protobuf:"varint,4,opt,name=album_type,json=albumType,proto3,enum=spotify.your_library.proto.YourLibraryAlbumExtraInfo_Type" json:"album_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryPreReleaseExtraInfo) Reset() {
	*x = YourLibraryPreReleaseExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryPreReleaseExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryPreReleaseExtraInfo) ProtoMessage() {}

func (x *YourLibraryPreReleaseExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryPreReleaseExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryPreReleaseExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{14}
}

func (x *YourLibraryPreReleaseExtraInfo) GetArtistName() string {
	if x != nil {
		return x.ArtistName
	}
	return ""
}

func (x *YourLibraryPreReleaseExtraInfo) GetArtistUri() string {
	if x != nil {
		return x.ArtistUri
	}
	return ""
}

func (x *YourLibraryPreReleaseExtraInfo) GetType() YourLibraryPreReleaseExtraInfo_Type {
	if x != nil {
		return x.Type
	}
	return YourLibraryPreReleaseExtraInfo_ALBUM
}

func (x *YourLibraryPreReleaseExtraInfo) GetAlbumType() YourLibraryAlbumExtraInfo_Type {
	if x != nil {
		return x.AlbumType
	}
	return YourLibraryAlbumExtraInfo_ALBUM
}

type YourLibraryEventExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationName  string                 `protobuf:"bytes,1,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CityName      string                 `protobuf:"bytes,3,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryEventExtraInfo) Reset() {
	*x = YourLibraryEventExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryEventExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryEventExtraInfo) ProtoMessage() {}

func (x *YourLibraryEventExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryEventExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryEventExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{15}
}

func (x *YourLibraryEventExtraInfo) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *YourLibraryEventExtraInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *YourLibraryEventExtraInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

type YourLibraryAuthorExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryAuthorExtraInfo) Reset() {
	*x = YourLibraryAuthorExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryAuthorExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryAuthorExtraInfo) ProtoMessage() {}

func (x *YourLibraryAuthorExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryAuthorExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryAuthorExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{16}
}

type YourLibraryVenueExtraInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressName   string                 `protobuf:"bytes,1,opt,name=address_name,json=addressName,proto3" json:"address_name,omitempty"`
	CityName      string                 `protobuf:"bytes,2,opt,name=city_name,json=cityName,proto3" json:"city_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryVenueExtraInfo) Reset() {
	*x = YourLibraryVenueExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryVenueExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryVenueExtraInfo) ProtoMessage() {}

func (x *YourLibraryVenueExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryVenueExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryVenueExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{17}
}

func (x *YourLibraryVenueExtraInfo) GetAddressName() string {
	if x != nil {
		return x.AddressName
	}
	return ""
}

func (x *YourLibraryVenueExtraInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

type YourLibraryConcertCampaignExtraInfo struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	Status        YourLibraryConcertCampaignExtraInfo_Status `protobuf:"varint,1,opt,name=status,proto3,enum=spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo_Status" json:"status,omitempty"`
	StartTime     int64                                      `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                                      `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryConcertCampaignExtraInfo) Reset() {
	*x = YourLibraryConcertCampaignExtraInfo{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryConcertCampaignExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryConcertCampaignExtraInfo) ProtoMessage() {}

func (x *YourLibraryConcertCampaignExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryConcertCampaignExtraInfo.ProtoReflect.Descriptor instead.
func (*YourLibraryConcertCampaignExtraInfo) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{18}
}

func (x *YourLibraryConcertCampaignExtraInfo) GetStatus() YourLibraryConcertCampaignExtraInfo_Status {
	if x != nil {
		return x.Status
	}
	return YourLibraryConcertCampaignExtraInfo_UNSPECIFIED
}

func (x *YourLibraryConcertCampaignExtraInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *YourLibraryConcertCampaignExtraInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type YourLibraryDecoratedEntity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityInfo *YourLibraryEntityInfo `protobuf:"bytes,1,opt,name=entity_info,json=entityInfo,proto3" json:"entity_info,omitempty"`
	// Types that are valid to be assigned to Entity:
	//
	//	*YourLibraryDecoratedEntity_Album
	//	*YourLibraryDecoratedEntity_Artist
	//	*YourLibraryDecoratedEntity_Playlist
	//	*YourLibraryDecoratedEntity_Show
	//	*YourLibraryDecoratedEntity_Folder
	//	*YourLibraryDecoratedEntity_LikedSongs
	//	*YourLibraryDecoratedEntity_NewEpisodes
	//	*YourLibraryDecoratedEntity_LocalFiles
	//	*YourLibraryDecoratedEntity_Book
	//	*YourLibraryDecoratedEntity_CachedFiles
	//	*YourLibraryDecoratedEntity_Prerelease
	//	*YourLibraryDecoratedEntity_Event
	//	*YourLibraryDecoratedEntity_Author
	//	*YourLibraryDecoratedEntity_Venue
	//	*YourLibraryDecoratedEntity_ConcertCampaign
	Entity        isYourLibraryDecoratedEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YourLibraryDecoratedEntity) Reset() {
	*x = YourLibraryDecoratedEntity{}
	mi := &file_your_library_decorated_entity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YourLibraryDecoratedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YourLibraryDecoratedEntity) ProtoMessage() {}

func (x *YourLibraryDecoratedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_your_library_decorated_entity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YourLibraryDecoratedEntity.ProtoReflect.Descriptor instead.
func (*YourLibraryDecoratedEntity) Descriptor() ([]byte, []int) {
	return file_your_library_decorated_entity_proto_rawDescGZIP(), []int{19}
}

func (x *YourLibraryDecoratedEntity) GetEntityInfo() *YourLibraryEntityInfo {
	if x != nil {
		return x.EntityInfo
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetEntity() isYourLibraryDecoratedEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetAlbum() *YourLibraryAlbumExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Album); ok {
			return x.Album
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetArtist() *YourLibraryArtistExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Artist); ok {
			return x.Artist
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetPlaylist() *YourLibraryPlaylistExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Playlist); ok {
			return x.Playlist
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetShow() *YourLibraryShowExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Show); ok {
			return x.Show
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetFolder() *YourLibraryFolderExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Folder); ok {
			return x.Folder
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetLikedSongs() *YourLibraryLikedSongsExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_LikedSongs); ok {
			return x.LikedSongs
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetNewEpisodes() *YourLibraryNewEpisodesExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_NewEpisodes); ok {
			return x.NewEpisodes
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetLocalFiles() *YourLibraryLocalFilesExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_LocalFiles); ok {
			return x.LocalFiles
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetBook() *YourLibraryBookExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Book); ok {
			return x.Book
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetCachedFiles() *YourLibraryCachedFilesExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_CachedFiles); ok {
			return x.CachedFiles
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetPrerelease() *YourLibraryPreReleaseExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Prerelease); ok {
			return x.Prerelease
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetEvent() *YourLibraryEventExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetAuthor() *YourLibraryAuthorExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Author); ok {
			return x.Author
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetVenue() *YourLibraryVenueExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_Venue); ok {
			return x.Venue
		}
	}
	return nil
}

func (x *YourLibraryDecoratedEntity) GetConcertCampaign() *YourLibraryConcertCampaignExtraInfo {
	if x != nil {
		if x, ok := x.Entity.(*YourLibraryDecoratedEntity_ConcertCampaign); ok {
			return x.ConcertCampaign
		}
	}
	return nil
}

type isYourLibraryDecoratedEntity_Entity interface {
	isYourLibraryDecoratedEntity_Entity()
}

type YourLibraryDecoratedEntity_Album struct {
	Album *YourLibraryAlbumExtraInfo `protobuf:"bytes,2,opt,name=album,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Artist struct {
	Artist *YourLibraryArtistExtraInfo `protobuf:"bytes,3,opt,name=artist,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Playlist struct {
	Playlist *YourLibraryPlaylistExtraInfo `protobuf:"bytes,4,opt,name=playlist,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Show struct {
	Show *YourLibraryShowExtraInfo `protobuf:"bytes,5,opt,name=show,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Folder struct {
	Folder *YourLibraryFolderExtraInfo `protobuf:"bytes,6,opt,name=folder,proto3,oneof"`
}

type YourLibraryDecoratedEntity_LikedSongs struct {
	LikedSongs *YourLibraryLikedSongsExtraInfo `protobuf:"bytes,8,opt,name=liked_songs,json=likedSongs,proto3,oneof"`
}

type YourLibraryDecoratedEntity_NewEpisodes struct {
	NewEpisodes *YourLibraryNewEpisodesExtraInfo `protobuf:"bytes,10,opt,name=new_episodes,json=newEpisodes,proto3,oneof"`
}

type YourLibraryDecoratedEntity_LocalFiles struct {
	LocalFiles *YourLibraryLocalFilesExtraInfo `protobuf:"bytes,11,opt,name=local_files,json=localFiles,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Book struct {
	Book *YourLibraryBookExtraInfo `protobuf:"bytes,12,opt,name=book,proto3,oneof"`
}

type YourLibraryDecoratedEntity_CachedFiles struct {
	CachedFiles *YourLibraryCachedFilesExtraInfo `protobuf:"bytes,13,opt,name=cached_files,json=cachedFiles,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Prerelease struct {
	Prerelease *YourLibraryPreReleaseExtraInfo `protobuf:"bytes,15,opt,name=prerelease,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Event struct {
	Event *YourLibraryEventExtraInfo `protobuf:"bytes,16,opt,name=event,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Author struct {
	Author *YourLibraryAuthorExtraInfo `protobuf:"bytes,17,opt,name=author,proto3,oneof"`
}

type YourLibraryDecoratedEntity_Venue struct {
	Venue *YourLibraryVenueExtraInfo `protobuf:"bytes,19,opt,name=venue,proto3,oneof"`
}

type YourLibraryDecoratedEntity_ConcertCampaign struct {
	ConcertCampaign *YourLibraryConcertCampaignExtraInfo `protobuf:"bytes,20,opt,name=concert_campaign,json=concertCampaign,proto3,oneof"`
}

func (*YourLibraryDecoratedEntity_Album) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Artist) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Playlist) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Show) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Folder) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_LikedSongs) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_NewEpisodes) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_LocalFiles) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Book) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_CachedFiles) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Prerelease) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Event) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Author) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_Venue) isYourLibraryDecoratedEntity_Entity() {}

func (*YourLibraryDecoratedEntity_ConcertCampaign) isYourLibraryDecoratedEntity_Entity() {}

var File_your_library_decorated_entity_proto protoreflect.FileDescriptor

const file_your_library_decorated_entity_proto_rawDesc = "" +
	"\n" +
	"#your_library_decorated_entity.proto\x12\x1aspotify.your_library.proto\x1a.policy/supported_link_types_in_playlists.proto\"\xf3\x03\n" +
	"\x15YourLibraryEntityInfo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x1f\n" +
	"\vgroup_label\x18\x05 \x01(\tR\n" +
	"groupLabel\x12\x1b\n" +
	"\timage_uri\x18\x06 \x01(\tR\bimageUri\x12\x16\n" +
	"\x06pinned\x18\a \x01(\bR\x06pinned\x12V\n" +
	"\bpinnable\x18\b \x01(\x0e2:.spotify.your_library.proto.YourLibraryEntityInfo.PinnableR\bpinnable\x12c\n" +
	"\x14offline_availability\x18\t \x01(\x0e20.spotify.your_library.proto.Offline.AvailabilityR\x13offlineAvailability\x12\x19\n" +
	"\badd_time\x18\v \x01(\x03R\aaddTime\x12\x1f\n" +
	"\vlast_played\x18\f \x01(\x03R\n" +
	"lastPlayed\x12*\n" +
	"\x11has_curated_items\x18\r \x01(\bR\x0fhasCuratedItems\"9\n" +
	"\bPinnable\x12\a\n" +
	"\x03YES\x10\x00\x12\x10\n" +
	"\fNO_IN_FOLDER\x10\x01\x12\x12\n" +
	"\x0eNOT_VALID_TYPE\x10\x02\"U\n" +
	"\aOffline\"J\n" +
	"\fAvailability\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x06\n" +
	"\x02NO\x10\x01\x12\a\n" +
	"\x03YES\x10\x02\x12\x0f\n" +
	"\vDOWNLOADING\x10\x03\x12\v\n" +
	"\aWAITING\x10\x04\"\xcf\x02\n" +
	"\x19YourLibraryAlbumExtraInfo\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"artist_uri\x18\x02 \x01(\tR\tartistUri\x12N\n" +
	"\x04type\x18\x03 \x01(\x0e2:.spotify.your_library.proto.YourLibraryAlbumExtraInfo.TypeR\x04type\x12&\n" +
	"\x0fis_premium_only\x18\x04 \x01(\bR\risPremiumOnly\x12\x1f\n" +
	"\vnew_release\x18\x05 \x01(\bR\n" +
	"newRelease\x12!\n" +
	"\frelease_date\x18\x06 \x01(\x03R\vreleaseDate\"6\n" +
	"\x04Type\x12\t\n" +
	"\x05ALBUM\x10\x00\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x01\x12\x0f\n" +
	"\vCOMPILATION\x10\x02\x12\x06\n" +
	"\x02EP\x10\x03\"X\n" +
	"\x1aYourLibraryArtistExtraInfo\x12:\n" +
	"\x1ahas_liked_tracks_or_albums\x18\x01 \x01(\bR\x16hasLikedTracksOrAlbums\"}\n" +
	"\x18NumberOfItemsForLinkType\x12D\n" +
	"\tlink_type\x18\x01 \x01(\x0e2'.spotify.playlist.cosmos.proto.LinkTypeR\blinkType\x12\x1b\n" +
	"\tnum_items\x18\x02 \x01(\x05R\bnumItems\"E\n" +
	"\x1dYourLibraryPlaylistFolderInfo\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xcc\b\n" +
	"\x1cYourLibraryPlaylistExtraInfo\x12!\n" +
	"\fcreator_name\x18\x01 \x01(\tR\vcreatorName\x12\x1f\n" +
	"\vcreator_uri\x18\b \x01(\tR\n" +
	"creatorUri\x12\x1d\n" +
	"\n" +
	"is_loading\x18\x05 \x01(\bR\tisLoading\x12\x19\n" +
	"\bcan_view\x18\x06 \x01(\bR\acanView\x12\x17\n" +
	"\acan_add\x18\t \x01(\bR\x06canAdd\x12\x15\n" +
	"\x06row_id\x18\a \x01(\tR\x05rowId\x12\"\n" +
	"\rmade_for_name\x18\n" +
	" \x01(\tR\vmadeForName\x12 \n" +
	"\fmade_for_uri\x18\v \x01(\tR\n" +
	"madeForUri\x12u\n" +
	"\x1dnumber_of_items_per_link_type\x18\f \x03(\v24.spotify.your_library.proto.NumberOfItemsForLinkTypeR\x18numberOfItemsPerLinkType\x12\"\n" +
	"\rowned_by_self\x18\r \x01(\bR\vownedBySelf\x12Z\n" +
	"\vfrom_folder\x18\x0e \x01(\v29.spotify.your_library.proto.YourLibraryPlaylistFolderInfoR\n" +
	"fromFolder\x12\x1f\n" +
	"\vname_prefix\x18\x0f \x01(\tR\n" +
	"namePrefix\x12#\n" +
	"\rmixing_active\x18\x10 \x01(\bR\fmixingActive\x12.\n" +
	"\x13is_empty_predefined\x18\x11 \x01(\bR\x11isEmptyPredefined\x12\x83\x01\n" +
	"\x18prompt_generation_status\x18\x12 \x01(\x0e2I.spotify.your_library.proto.YourLibraryPlaylistExtraInfo.GenerationStatusR\x16promptGenerationStatus\x124\n" +
	"\x16prompt_is_personalized\x18\x13 \x01(\bR\x14promptIsPersonalized\x12,\n" +
	"\x12is_prompt_playlist\x18\x14 \x01(\bR\x10isPromptPlaylist\x12!\n" +
	"\fis_published\x18\x15 \x01(\bR\visPublished\x12\x1d\n" +
	"\n" +
	"is_private\x18\x16 \x01(\bR\tisPrivate\"\x9e\x01\n" +
	"\x10GenerationStatus\x12\x1a\n" +
	"\x16MESSAGE_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15MESSAGE_STATUS_QUEUED\x10\x02\x12\x1d\n" +
	"\x19MESSAGE_STATUS_PROCESSING\x10\x03\x12\x18\n" +
	"\x14MESSAGE_STATUS_ERROR\x10\x04\"\xa3\x01\n" +
	"\x18YourLibraryShowExtraInfo\x12!\n" +
	"\fcreator_name\x18\x01 \x01(\tR\vcreatorName\x12!\n" +
	"\fpublish_date\x18\x04 \x01(\x03R\vpublishDate\x12A\n" +
	"\x1dnumber_of_downloaded_episodes\x18\x06 \x01(\x05R\x1anumberOfDownloadedEpisodes\"\xdf\x01\n" +
	"\x1aYourLibraryFolderExtraInfo\x12.\n" +
	"\x13number_of_playlists\x18\x02 \x01(\x05R\x11numberOfPlaylists\x12*\n" +
	"\x11number_of_folders\x18\x03 \x01(\x05R\x0fnumberOfFolders\x12\x15\n" +
	"\x06row_id\x18\x04 \x01(\tR\x05rowId\x12N\n" +
	"\x06entity\x18\x05 \x03(\v26.spotify.your_library.proto.YourLibraryDecoratedEntityR\x06entity\"c\n" +
	"\x1eYourLibraryLikedSongsExtraInfo\x12&\n" +
	"\x0fnumber_of_songs\x18\x03 \x01(\x05R\rnumberOfSongs\x12\x19\n" +
	"\bis_empty\x18\x04 \x01(\bR\aisEmpty\"D\n" +
	"\x1fYourLibraryNewEpisodesExtraInfo\x12!\n" +
	"\fpublish_date\x18\x01 \x01(\x03R\vpublishDate\"H\n" +
	"\x1eYourLibraryLocalFilesExtraInfo\x12&\n" +
	"\x0fnumber_of_files\x18\x01 \x01(\x05R\rnumberOfFiles\"\x97\x03\n" +
	"\x18YourLibraryBookExtraInfo\x12\x1f\n" +
	"\vauthor_name\x18\x01 \x01(\tR\n" +
	"authorName\x12S\n" +
	"\x06access\x18\x02 \x01(\x0e2;.spotify.your_library.proto.YourLibraryBookExtraInfo.AccessR\x06access\x12+\n" +
	"\x11milliseconds_left\x18\x03 \x01(\x03R\x10millisecondsLeft\x12!\n" +
	"\fpercent_done\x18\x04 \x01(\x05R\vpercentDone\x12P\n" +
	"\x05state\x18\x05 \x01(\x0e2:.spotify.your_library.proto.YourLibraryBookExtraInfo.StateR\x05state\"*\n" +
	"\x06Access\x12\b\n" +
	"\x04OPEN\x10\x00\x12\n" +
	"\n" +
	"\x06LOCKED\x10\x01\x12\n" +
	"\n" +
	"\x06CAPPED\x10\x02\"7\n" +
	"\x05State\x12\x0f\n" +
	"\vNOT_STARTED\x10\x00\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02\"y\n" +
	"\x1fYourLibraryCachedFilesExtraInfo\x12&\n" +
	"\x0fnumber_of_items\x18\x01 \x01(\x05R\rnumberOfItems\x12.\n" +
	"\x13duration_in_seconds\x18\x02 \x01(\x05R\x11durationInSeconds\"\xad\x02\n" +
	"\x1eYourLibraryPreReleaseExtraInfo\x12\x1f\n" +
	"\vartist_name\x18\x01 \x01(\tR\n" +
	"artistName\x12\x1d\n" +
	"\n" +
	"artist_uri\x18\x02 \x01(\tR\tartistUri\x12S\n" +
	"\x04type\x18\x03 \x01(\x0e2?.spotify.your_library.proto.YourLibraryPreReleaseExtraInfo.TypeR\x04type\x12Y\n" +
	"\n" +
	"album_type\x18\x04 \x01(\x0e2:.spotify.your_library.proto.YourLibraryAlbumExtraInfo.TypeR\talbumType\"\x1b\n" +
	"\x04Type\x12\t\n" +
	"\x05ALBUM\x10\x00\x12\b\n" +
	"\x04BOOK\x10\x01\"|\n" +
	"\x19YourLibraryEventExtraInfo\x12#\n" +
	"\rlocation_name\x18\x01 \x01(\tR\flocationName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x1b\n" +
	"\tcity_name\x18\x03 \x01(\tR\bcityName\"\x1c\n" +
	"\x1aYourLibraryAuthorExtraInfo\"[\n" +
	"\x19YourLibraryVenueExtraInfo\x12!\n" +
	"\faddress_name\x18\x01 \x01(\tR\vaddressName\x12\x1b\n" +
	"\tcity_name\x18\x02 \x01(\tR\bcityName\"\xcf\x02\n" +
	"#YourLibraryConcertCampaignExtraInfo\x12^\n" +
	"\x06status\x18\x01 \x01(\x0e2F.spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"\x8d\x01\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bRESERVED\x10\x01\x12\b\n" +
	"\x04FCFS\x10\x02\x12\x0e\n" +
	"\n" +
	"WAITLISTED\x10\x03\x12\r\n" +
	"\tPURCHASED\x10\x04\x12\x0e\n" +
	"\n" +
	"INELIGIBLE\x10\x05\x12\f\n" +
	"\bSOLD_OUT\x10\x06\x12\r\n" +
	"\tCANCELLED\x10\a\x12\x0e\n" +
	"\n" +
	"SALE_ENDED\x10\b\"\x9b\v\n" +
	"\x1aYourLibraryDecoratedEntity\x12R\n" +
	"\ventity_info\x18\x01 \x01(\v21.spotify.your_library.proto.YourLibraryEntityInfoR\n" +
	"entityInfo\x12M\n" +
	"\x05album\x18\x02 \x01(\v25.spotify.your_library.proto.YourLibraryAlbumExtraInfoH\x00R\x05album\x12P\n" +
	"\x06artist\x18\x03 \x01(\v26.spotify.your_library.proto.YourLibraryArtistExtraInfoH\x00R\x06artist\x12V\n" +
	"\bplaylist\x18\x04 \x01(\v28.spotify.your_library.proto.YourLibraryPlaylistExtraInfoH\x00R\bplaylist\x12J\n" +
	"\x04show\x18\x05 \x01(\v24.spotify.your_library.proto.YourLibraryShowExtraInfoH\x00R\x04show\x12P\n" +
	"\x06folder\x18\x06 \x01(\v26.spotify.your_library.proto.YourLibraryFolderExtraInfoH\x00R\x06folder\x12]\n" +
	"\vliked_songs\x18\b \x01(\v2:.spotify.your_library.proto.YourLibraryLikedSongsExtraInfoH\x00R\n" +
	"likedSongs\x12`\n" +
	"\fnew_episodes\x18\n" +
	" \x01(\v2;.spotify.your_library.proto.YourLibraryNewEpisodesExtraInfoH\x00R\vnewEpisodes\x12]\n" +
	"\vlocal_files\x18\v \x01(\v2:.spotify.your_library.proto.YourLibraryLocalFilesExtraInfoH\x00R\n" +
	"localFiles\x12J\n" +
	"\x04book\x18\f \x01(\v24.spotify.your_library.proto.YourLibraryBookExtraInfoH\x00R\x04book\x12`\n" +
	"\fcached_files\x18\r \x01(\v2;.spotify.your_library.proto.YourLibraryCachedFilesExtraInfoH\x00R\vcachedFiles\x12\\\n" +
	"\n" +
	"prerelease\x18\x0f \x01(\v2:.spotify.your_library.proto.YourLibraryPreReleaseExtraInfoH\x00R\n" +
	"prerelease\x12M\n" +
	"\x05event\x18\x10 \x01(\v25.spotify.your_library.proto.YourLibraryEventExtraInfoH\x00R\x05event\x12P\n" +
	"\x06author\x18\x11 \x01(\v26.spotify.your_library.proto.YourLibraryAuthorExtraInfoH\x00R\x06author\x12M\n" +
	"\x05venue\x18\x13 \x01(\v25.spotify.your_library.proto.YourLibraryVenueExtraInfoH\x00R\x05venue\x12l\n" +
	"\x10concert_campaign\x18\x14 \x01(\v2?.spotify.your_library.proto.YourLibraryConcertCampaignExtraInfoH\x00R\x0fconcertCampaignB\b\n" +
	"\x06entityBEZCgithub.com/pyrorhythm/libspot/api/spotify/your_library;your_libraryb\x06proto3"

var (
	file_your_library_decorated_entity_proto_rawDescOnce sync.Once
	file_your_library_decorated_entity_proto_rawDescData []byte
)

func file_your_library_decorated_entity_proto_rawDescGZIP() []byte {
	file_your_library_decorated_entity_proto_rawDescOnce.Do(func() {
		file_your_library_decorated_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_your_library_decorated_entity_proto_rawDesc), len(file_your_library_decorated_entity_proto_rawDesc)))
	})
	return file_your_library_decorated_entity_proto_rawDescData
}

var file_your_library_decorated_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_your_library_decorated_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_your_library_decorated_entity_proto_goTypes = []any{
	(YourLibraryEntityInfo_Pinnable)(0),                // 0: spotify.your_library.proto.YourLibraryEntityInfo.Pinnable
	(Offline_Availability)(0),                          // 1: spotify.your_library.proto.Offline.Availability
	(YourLibraryAlbumExtraInfo_Type)(0),                // 2: spotify.your_library.proto.YourLibraryAlbumExtraInfo.Type
	(YourLibraryPlaylistExtraInfo_GenerationStatus)(0), // 3: spotify.your_library.proto.YourLibraryPlaylistExtraInfo.GenerationStatus
	(YourLibraryBookExtraInfo_Access)(0),               // 4: spotify.your_library.proto.YourLibraryBookExtraInfo.Access
	(YourLibraryBookExtraInfo_State)(0),                // 5: spotify.your_library.proto.YourLibraryBookExtraInfo.State
	(YourLibraryPreReleaseExtraInfo_Type)(0),           // 6: spotify.your_library.proto.YourLibraryPreReleaseExtraInfo.Type
	(YourLibraryConcertCampaignExtraInfo_Status)(0),    // 7: spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo.Status
	(*YourLibraryEntityInfo)(nil),                      // 8: spotify.your_library.proto.YourLibraryEntityInfo
	(*Offline)(nil),                                    // 9: spotify.your_library.proto.Offline
	(*YourLibraryAlbumExtraInfo)(nil),                  // 10: spotify.your_library.proto.YourLibraryAlbumExtraInfo
	(*YourLibraryArtistExtraInfo)(nil),                 // 11: spotify.your_library.proto.YourLibraryArtistExtraInfo
	(*NumberOfItemsForLinkType)(nil),                   // 12: spotify.your_library.proto.NumberOfItemsForLinkType
	(*YourLibraryPlaylistFolderInfo)(nil),              // 13: spotify.your_library.proto.YourLibraryPlaylistFolderInfo
	(*YourLibraryPlaylistExtraInfo)(nil),               // 14: spotify.your_library.proto.YourLibraryPlaylistExtraInfo
	(*YourLibraryShowExtraInfo)(nil),                   // 15: spotify.your_library.proto.YourLibraryShowExtraInfo
	(*YourLibraryFolderExtraInfo)(nil),                 // 16: spotify.your_library.proto.YourLibraryFolderExtraInfo
	(*YourLibraryLikedSongsExtraInfo)(nil),             // 17: spotify.your_library.proto.YourLibraryLikedSongsExtraInfo
	(*YourLibraryNewEpisodesExtraInfo)(nil),            // 18: spotify.your_library.proto.YourLibraryNewEpisodesExtraInfo
	(*YourLibraryLocalFilesExtraInfo)(nil),             // 19: spotify.your_library.proto.YourLibraryLocalFilesExtraInfo
	(*YourLibraryBookExtraInfo)(nil),                   // 20: spotify.your_library.proto.YourLibraryBookExtraInfo
	(*YourLibraryCachedFilesExtraInfo)(nil),            // 21: spotify.your_library.proto.YourLibraryCachedFilesExtraInfo
	(*YourLibraryPreReleaseExtraInfo)(nil),             // 22: spotify.your_library.proto.YourLibraryPreReleaseExtraInfo
	(*YourLibraryEventExtraInfo)(nil),                  // 23: spotify.your_library.proto.YourLibraryEventExtraInfo
	(*YourLibraryAuthorExtraInfo)(nil),                 // 24: spotify.your_library.proto.YourLibraryAuthorExtraInfo
	(*YourLibraryVenueExtraInfo)(nil),                  // 25: spotify.your_library.proto.YourLibraryVenueExtraInfo
	(*YourLibraryConcertCampaignExtraInfo)(nil),        // 26: spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo
	(*YourLibraryDecoratedEntity)(nil),                 // 27: spotify.your_library.proto.YourLibraryDecoratedEntity
	(cosmos.LinkType)(0),                               // 28: spotify.playlist.cosmos.proto.LinkType
}
var file_your_library_decorated_entity_proto_depIdxs = []int32{
	0,  // 0: spotify.your_library.proto.YourLibraryEntityInfo.pinnable:type_name -> spotify.your_library.proto.YourLibraryEntityInfo.Pinnable
	1,  // 1: spotify.your_library.proto.YourLibraryEntityInfo.offline_availability:type_name -> spotify.your_library.proto.Offline.Availability
	2,  // 2: spotify.your_library.proto.YourLibraryAlbumExtraInfo.type:type_name -> spotify.your_library.proto.YourLibraryAlbumExtraInfo.Type
	28, // 3: spotify.your_library.proto.NumberOfItemsForLinkType.link_type:type_name -> spotify.playlist.cosmos.proto.LinkType
	12, // 4: spotify.your_library.proto.YourLibraryPlaylistExtraInfo.number_of_items_per_link_type:type_name -> spotify.your_library.proto.NumberOfItemsForLinkType
	13, // 5: spotify.your_library.proto.YourLibraryPlaylistExtraInfo.from_folder:type_name -> spotify.your_library.proto.YourLibraryPlaylistFolderInfo
	3,  // 6: spotify.your_library.proto.YourLibraryPlaylistExtraInfo.prompt_generation_status:type_name -> spotify.your_library.proto.YourLibraryPlaylistExtraInfo.GenerationStatus
	27, // 7: spotify.your_library.proto.YourLibraryFolderExtraInfo.entity:type_name -> spotify.your_library.proto.YourLibraryDecoratedEntity
	4,  // 8: spotify.your_library.proto.YourLibraryBookExtraInfo.access:type_name -> spotify.your_library.proto.YourLibraryBookExtraInfo.Access
	5,  // 9: spotify.your_library.proto.YourLibraryBookExtraInfo.state:type_name -> spotify.your_library.proto.YourLibraryBookExtraInfo.State
	6,  // 10: spotify.your_library.proto.YourLibraryPreReleaseExtraInfo.type:type_name -> spotify.your_library.proto.YourLibraryPreReleaseExtraInfo.Type
	2,  // 11: spotify.your_library.proto.YourLibraryPreReleaseExtraInfo.album_type:type_name -> spotify.your_library.proto.YourLibraryAlbumExtraInfo.Type
	7,  // 12: spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo.status:type_name -> spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo.Status
	8,  // 13: spotify.your_library.proto.YourLibraryDecoratedEntity.entity_info:type_name -> spotify.your_library.proto.YourLibraryEntityInfo
	10, // 14: spotify.your_library.proto.YourLibraryDecoratedEntity.album:type_name -> spotify.your_library.proto.YourLibraryAlbumExtraInfo
	11, // 15: spotify.your_library.proto.YourLibraryDecoratedEntity.artist:type_name -> spotify.your_library.proto.YourLibraryArtistExtraInfo
	14, // 16: spotify.your_library.proto.YourLibraryDecoratedEntity.playlist:type_name -> spotify.your_library.proto.YourLibraryPlaylistExtraInfo
	15, // 17: spotify.your_library.proto.YourLibraryDecoratedEntity.show:type_name -> spotify.your_library.proto.YourLibraryShowExtraInfo
	16, // 18: spotify.your_library.proto.YourLibraryDecoratedEntity.folder:type_name -> spotify.your_library.proto.YourLibraryFolderExtraInfo
	17, // 19: spotify.your_library.proto.YourLibraryDecoratedEntity.liked_songs:type_name -> spotify.your_library.proto.YourLibraryLikedSongsExtraInfo
	18, // 20: spotify.your_library.proto.YourLibraryDecoratedEntity.new_episodes:type_name -> spotify.your_library.proto.YourLibraryNewEpisodesExtraInfo
	19, // 21: spotify.your_library.proto.YourLibraryDecoratedEntity.local_files:type_name -> spotify.your_library.proto.YourLibraryLocalFilesExtraInfo
	20, // 22: spotify.your_library.proto.YourLibraryDecoratedEntity.book:type_name -> spotify.your_library.proto.YourLibraryBookExtraInfo
	21, // 23: spotify.your_library.proto.YourLibraryDecoratedEntity.cached_files:type_name -> spotify.your_library.proto.YourLibraryCachedFilesExtraInfo
	22, // 24: spotify.your_library.proto.YourLibraryDecoratedEntity.prerelease:type_name -> spotify.your_library.proto.YourLibraryPreReleaseExtraInfo
	23, // 25: spotify.your_library.proto.YourLibraryDecoratedEntity.event:type_name -> spotify.your_library.proto.YourLibraryEventExtraInfo
	24, // 26: spotify.your_library.proto.YourLibraryDecoratedEntity.author:type_name -> spotify.your_library.proto.YourLibraryAuthorExtraInfo
	25, // 27: spotify.your_library.proto.YourLibraryDecoratedEntity.venue:type_name -> spotify.your_library.proto.YourLibraryVenueExtraInfo
	26, // 28: spotify.your_library.proto.YourLibraryDecoratedEntity.concert_campaign:type_name -> spotify.your_library.proto.YourLibraryConcertCampaignExtraInfo
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_your_library_decorated_entity_proto_init() }
func file_your_library_decorated_entity_proto_init() {
	if File_your_library_decorated_entity_proto != nil {
		return
	}
	file_your_library_decorated_entity_proto_msgTypes[19].OneofWrappers = []any{
		(*YourLibraryDecoratedEntity_Album)(nil),
		(*YourLibraryDecoratedEntity_Artist)(nil),
		(*YourLibraryDecoratedEntity_Playlist)(nil),
		(*YourLibraryDecoratedEntity_Show)(nil),
		(*YourLibraryDecoratedEntity_Folder)(nil),
		(*YourLibraryDecoratedEntity_LikedSongs)(nil),
		(*YourLibraryDecoratedEntity_NewEpisodes)(nil),
		(*YourLibraryDecoratedEntity_LocalFiles)(nil),
		(*YourLibraryDecoratedEntity_Book)(nil),
		(*YourLibraryDecoratedEntity_CachedFiles)(nil),
		(*YourLibraryDecoratedEntity_Prerelease)(nil),
		(*YourLibraryDecoratedEntity_Event)(nil),
		(*YourLibraryDecoratedEntity_Author)(nil),
		(*YourLibraryDecoratedEntity_Venue)(nil),
		(*YourLibraryDecoratedEntity_ConcertCampaign)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_your_library_decorated_entity_proto_rawDesc), len(file_your_library_decorated_entity_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_your_library_decorated_entity_proto_goTypes,
		DependencyIndexes: file_your_library_decorated_entity_proto_depIdxs,
		EnumInfos:         file_your_library_decorated_entity_proto_enumTypes,
		MessageInfos:      file_your_library_decorated_entity_proto_msgTypes,
	}.Build()
	File_your_library_decorated_entity_proto = out.File
	file_your_library_decorated_entity_proto_goTypes = nil
	file_your_library_decorated_entity_proto_depIdxs = nil
}
